### ISSUE TITLE
[Bug] ETQ pro, je vois l'ensemble des bénéficiaires pour lesquels j’apparais dans les groupes de suivi, via mon annuaire des bénéficiaires

### ISSUE THREAD

**Issue by Pauldoliveira** [gip-inclusion/carnet-de-bord#1006]
### Problème

Armelle, professionnelle de la structure API, nous contact via le tchat, pour nous signaler qu'elle ne parvient pas à trouver le dossier d'une bénéficiaire dans son "annuaire des bénéficiaires". Elle nous signal également ne pas parvenir a trouver la bénéficiaire en effectuant une recherche par "nom et prénom".
Cependant, lorsque par téléphone, nous essayons une recherche de bénéficiaire via l'ID CAF alors le carnet de bord de la bénéficiaire apparaît et elle peut y accéder.
complément: en consultant le carnet de bord de la bénéficiaire on constate que Armelle est bien la **référente** de cette bénéficiaire, par conséquent la bénéficiaire devrait apparaître dans "l'annuaire des bénéficiaires" d'Armelle mais aussi apparaître en résultat lors d'une recherche par le nom et prénom.
**2 situations dans lesquels un bénéficiaire n’apparaît pas dans l'annuaire des bénéficiaires:**
- Dans le groupe de suivi il y a 2 professionnels l'un comme référent l'autre non
- Dans le groupe de suivi il y a 2 professionnel les deux sont référents

### Solution : 
Permettre à l'ensemble du groupe de suivi de trouver le bénéficiaire dans l'item "annuaire de mes bénéficiaires" et de trouver le bénéficiaire via la recherche nom et prénom.

### Test : 
ETQ professionnel référencé dans l'item "groupe de suivi" du carnet de bord d'un bénéficiaire
QUAND j'effectue une recherche par nom et prénom
ALORS je vois le bénéficiaire

ETQ professionnel référencé dans l'item "groupe de suivi" du carnet de bord d'un bénéficiaire
QUAND je consultes l'annuaire de mes bénéficiaires
ALORS je vois le bénéficiaire

_prendre contact avec les professionnels qui ont fait remonter le bugg et effectuer le test ci-dessus_
_dans le [thread Matermost](https://mattermost.incubateur.net/betagouv/pl/t3oc4kyeh3r38d6xpzuwagcqmr) vous trouverez les copie écran des situations décrite plus haut_

**Comment by lkouad** [comment]
@Pauldoliveira c'est toujours d'actualité ou pas?

**Comment by Pauldoliveira** [comment]
Je n'ai pas détecter de nouvelle demande dans la tchat donc je dirai que non c'es n'est plus d'actualité cependant dans tout les cas je penses que tu peux la cloturer si tu le souhaites puisque les US d'accès à tout les carnet vu hier en refiment y répondront.
