### ISSUE TITLE
En tant que admin d'un département lorsque j'importe une liste de bénéficiaire pour la réorientation alors certain ne sont pas trouvés

### ISSUE THREAD

**Issue by Pauldoliveira** [gip-inclusion/carnet-de-bord#1010]
### Problème ###
Marie-Lisa nous transmet via le SAV une liste de bénéficiaires qu'elle n'accompagnent plus, et nous demande de retirer son nom comme référente. 
Lors de l'import via le compte admin CD08 , 2 bénéficiaires ne sont pas trouvés alors qu'ils disposent d'un carnet de bord. 
Les données obligatoires et les formats sont respectés lors de l'import et pourtant le matching ne se fait pas.
(note: on remarque que les deux bénéficiaires concernés ont deux référents dans l'item "groupe de suivi" de leur carnet)

![image](https://user-images.githubusercontent.com/300823/186439202-f36def9f-b690-4d6f-8ab7-0c4755a2feb0.png)

* screen avec requête dans le thread privé carnet de bord

Quand on inspecte de la requête effectuée lors de l'import, on voit que :
 * la requête GraphQL émise mentionne bien les bénéficiaires présents dans le fichier
![image](https://user-images.githubusercontent.com/300823/186438064-29e85aa5-7be0-4f7a-a717-5ee7b8ac32b7.png)
 * la réponse du serveur inclut quand même un des deux bénéficiaires recherchés, bien que les deux soient signalés manquants
![image](https://user-images.githubusercontent.com/300823/186438537-de33c37c-e205-47ea-b109-729e40663f59.png)

**Comment by jonathanperret** [comment]
Après investigation :
 * le bénéficiaire qui ne remontait pas dans la réponse GraphQL n'avait pas la date de naissance indiquée dans le fichier, ce qui explique pourquoi il n'était pas trouvé ;
 * en supprimant ce "mauvais" bénéficiaire du fichier (en ne laissant que celui qui était trouvé dans la base donc), l'import n'affichait toujours pas le "bon" bénéficiaire ;
 * en changeant la casse dans le fichier pour que le nom et prénom du bénéficiaire en question soient entièrement en capitales, comme c'était le cas dans la base, l'import des données de ce bénéficiaire s'est bien déroulé.

Il semble donc que l'import de bénéficiaires avec une casse dans le fichier qui ne corresponde pas à celle utilisée dans la base ne fonctionne pas : bien que la requête GraphQL utilise l'opérateur `_ilike` qui permet bien de retrouver le bénéficiaire, le code client qui traite ensuite le résultat de requête ne doit pas être insensible à la casse.
