### ISSUE TITLE
ETQ manager, je souhaite pouvoir fournir le NIR lorsque j'importe des bénéficiaires.

### ISSUE THREAD

**Issue by bChiquet** [gip-inclusion/carnet-de-bord#1039]
**Problème :**
Quand j'importe un fichier de bénéficiaires actuellement, les bénéficiaires sont identifiés uniquement par l'**Internal ID** (un champ unique du logiciel que j'utilise).
J'aimerais également pouvoir ajouter le **NIR** (i.e. numéro de sécu), qui est plus généralisé.

**Proposition :**
Quand j'importe un bénéficiaire dans Carnet de Bord, mon fichier comporte une colonne **NIR**.
Cette colonne identifie uniquement un bénéficiaire : 
* Si j'importe un bénéficiaire avec le même **NIR** qu'un bénéficiaire existant, alors cet import est considérée comme une update de ce bénéficiaire.
* Si j'attribue le même **NIR** à deux bénéficiaires possédant un **internal ID** différent, alors une alerte est levée.

**Points en suspens :**
* Le **NIR** doit-il rester optionnel tant que tous les bénéficiaires déjà dans Carnet de Bord n'ont pas été actualisés ?
* L'**internal ID** peut-il être supprimé une fois que tous les bénéficiaires dans Carnet de Bord possèdent un **NIR** ?

**Comment by lionelB** [comment]
Il y a aussi une contrainte d'unicité sur nom + prenom + date de naissance + deploymentId

**Comment by lionelB** [comment]
il s'est avéré que la contrainte de l'internal_id n'est pas suffisament sure (on a eu le cas de doublons avec des internal ID différents) du coup j'aurais tendance a identifié plutot sur nom + prenom + date de naissance + deploymentid qui me parait plus robuste

**Comment by bChiquet** [comment]
> on a eu le cas de doublons avec des internal ID différents

C'est pas un truc dont on devrait être avertis par :
* Si j'attribue le même NIR à deux bénéficiaires possédant un internal ID différent, alors une alerte est levée.
Si oui, j'imagine que de notre côté les doublons ont soit été résolus, soit ça vaut le coup d'avoir les alertes ?

**Comment by lionelB** [comment]
ca me parait sain de lever une alerte si on essaie de réattibuer un nir censé être unique
