### ISSUE TITLE
ETQ manager, lors de l'import de bénéficiaires, je veux assigner un seul référent unique

### ISSUE THREAD

**Issue by lionelB** [gip-inclusion/carnet-de-bord#1090]
Lors de l'import des bénéficiaires, j'ai la possibilité d'assigner une ou plusieurs structure ainsi qu'un ou plusieurs référent.
On souhaitait laisser un maximum de liberté lors de l'import. 

On souhaite désormais arrêter les multiple assignation (structures / pro) lors des import de bénéficiaires.

## :robot: Fonctionnement des champs structure / professionnels
 3 cas de figure
- On a définie la structure : on assigne le bénéficiaire à la structure 
- On a définie le pro : on assigne le pro au groupe de suivi en tant que référent et on assigne le bénéficiaire à la structure. 
On affiche la structure dans la recap du parsing *
ex : 

| nom | prenom | date de naissance | structure | référent |
|---|---|---|---|---|
| Jean | Villars | 1943-10-21 | Centre commual | Pierre Chevalier |
 
- 0n a définie une structure et un pro: Dans ce cas __on ne tient pas compte de la structure fournie__. On ajoute le pro en tant que référent,  on assigne le bénéficiaire à la structure du pro (et on affiche la structure du pro et le pro dans le récap

**Comment by lkouad** [comment]
ETQ manager quand j'importe des bénéficiaires avec uniquement la structure (sans référent)
Alors les bénéficiaire n'apparaissent pas dans la liste du gestionnaire de structure
Voici le test
Import du manager:
Il importe CharlotteSA (import avec Structure+Accompagnateur), Charlotte S (import avec Structure uniquement), CharlotteA (import avec Accompagnateur uniquement)
image
Vu admin structure
Il manque Charlotte S (import avec Structure uniquement),
image
