### ISSUE TITLE
ETQ gestionnaire de structure je veux voir seulement les bénéficiaires rattaché à ma structure

### ISSUE THREAD

**Issue by lionelB** [gip-inclusion/carnet-de-bord#1091]
Actuellement dans la liste des bénéficiaire, en plus d'afficher les bénéficiaires assigné à la structure, on affiche / compte aussi les bénéficiaire avec un pro de la structure dans le groupe de suivi. 

On souhaite désormais limité l'affichage au seuls bénéficiaires assigné à la structure

**Comment by lkouad** [comment]
@lionelB le probleme est le suivant
ETQ manager quand j'importe des bénéficiaires avec uniquement la structure (sans référent) 
Alors les bénéficiaire n'apparaissent pas dans la liste du gestionnaire de structure
 Voici le test
Import du manager:
Il importe CharlotteSA (import avec Structure+Accompagnateur), Charlotte S (import avec Structure uniquement), CharlotteA (import avec Accompagnateur uniquement)
![image](https://user-images.githubusercontent.com/83343517/190994407-37799efa-d7e9-4bab-98bf-49c3ebc8479e.png)
Vu admin structure
Il manque Charlotte S (import avec Structure uniquement),
![image](https://user-images.githubusercontent.com/83343517/190994542-aba49512-e11b-4103-a202-63538d4b8adf.png)
