### ISSUE TITLE
Quand on tente de se connecter avec un compte non confirmé, il faudrait avoir un message d'erreur

### ISSUE THREAD

**Issue by jonathanperret** [gip-inclusion/carnet-de-bord#1142]
# 💣 Problème

Quand je saisis une adresse mail associée à un compte existant dans CdB mais non confirmé (`account.confirmed == false`), le formulaire de connexion ne me donne aucun retour indiquant que je n'ai pas le droit de me connecter. La connexion est bien refusée par le serveur (code 403), c'est côté front que ce n'est pas géré apparemment.

Pour tester : utiliser le compte bienvenu.lejeune@mission-locale.fr qui n'est pas confirmé.

https://user-images.githubusercontent.com/300823/193250226-2af8d29f-e741-4564-98f3-5ebfa613dee3.mov

# 🌈 Comportement attendu

On devrait avoir un message d'erreur clair indiquant que le compte n'est pas confirmé. Peut-être le même genre de message que lorsque le compte n'existe pas ?

<img width="412" alt="image" src="https://user-images.githubusercontent.com/300823/193250479-c23c9e43-e786-42e6-972b-2f38d6f41a06.png">

**Comment by lkouad** [comment]
Hello @jonathanperret j'ai testé et j'ai l'impression que c'est résolu pouvons nous fermer?

**Comment by jonathanperret** [comment]
@lkouad Ça a effectivement été corrigé au passage dans #1220, je ferme.

**Comment by jbuget** [comment]
Tel que c'est fait dans #1298 j'ai l'impression que les 2 cas en erreurs tels qu'ils sont pris en compte, ne posent pas de problème de sécurité, et que c'est bon. Mais je me méfie de mon incompétence / ignorance. C'est ok pour vous ?

**Comment by jonathanperret** [comment]
@jbuget alors pour le contexte, j'ai créé cette issue-ci au départ parce qu'il y avait un bug qui bloquait l'UI sans aucun message quand le compte n'était pas activé (techniquement, l'API renvoie un `403` dans ce cas or le front ne gérait que le `401` et le `200`). Ce problème a été corrigé au passage dans #1220 et donc aujourd'hui, que le compte soit inexistant ou non activé on a le message "Ce courriel n'est pas rattaché à un compte existant". L'information "est-ce que ce compte existe" était donc exposée avant #1220, c'est juste que son affichage était défaillant.

Ce qui est proposé dans #1298, c'est d'afficher un message différent quand le compte est existant mais inactif. Ce qui expose une information supplémentaire à l'utilisateur ; mais il faut noter que l'API elle-même expose déjà cette information (code `401` pour compte inexistant, `403` pour non activé). Donc là encore, ça n'implique pas de nouvelle exposition d'information sur les comptes.

En termes de "sécurité", tout comportement différent pour un compte inexistant/inactif par rapport à un compte existant peut être considéré comme un risque parce que ça peut notamment faciliter l'énumération de comptes. Mais il semble que ce point ait déjà été discuté et tranché en faveur d'exposer quand même l'information, pour faciliter l'accès des utilisateurs légitimes. Voir notamment #554 qui a été fermée sans résolution, et l'implémentation proposée dans #700 qui n'a pas été intégrée.

**Comment by jbuget** [comment]
Merci @jonathanperret pour le contexte (et le travail d'archéologie derrière) 🙏.
