### ISSUE TITLE
Simplifier le processus d'import des fichiers des bénéficiaires

### ISSUE THREAD

**Issue by lionelB** [gip-inclusion/carnet-de-bord#1154]
Actuellement, l'import initial de bRsa dans carnet de bord est une douleur au niveau du département car il demande de faire plusieurs extraction depuis leur SI et d'ensuite fusionner les différents fichiers.

Ce processus est chronophage tout en étant source d'erreurs.

**Comment by lkouad** [comment]
Mais surtout changer la valeur de certains champs.

**Comment by lionelB** [comment]
je ferme car il est possible de faire du réimport partiel et cela devrait simplifier la mise à jour des champs "non-pivots'
