### ISSUE TITLE
En tant que CO je réoriente ou maintiens l’accompagnement d’un bénéficiaire depuis la liste des demandes de réorientation

### ISSUE THREAD

**Issue by JonathanRaimond** [gip-inclusion/carnet-de-bord#1166]
## Problème :

Les Chargés d’orientation n’ont pas la possibilité de répondre aux demandes de réorientation effectuées par les référents au travers de Carnet de bord.

## Scénario:

Le Chargé d’orientation consulte la liste des demandes de réorientation et réoriente ou maintien l’accompagnement d’un bénéficiaire.

## Critères d’acceptation

**Étant donné que,** je suis connecté à mon compte CO et que je suis sur la liste des demandes de réorientation
**Lorsque,** je clic sur l’icône “Motif”
**Alors,** je peux consulter le motif de la demande de réorientation, saisie par le référent du bénéficiaire.

**Étant donné que,** je suis connecté à mon compte CO et que je suis sur la liste des demandes de réorientation
**Lorsque,** je clic sur l’icône “Voir le carnet”
**Alors,** je peux consulter le carnet du bénéficiaire.

**Étant donné que,** je suis connecté à mon compte CO et que je suis sur le carnet du bénéficiaire.
**Lorsque,** je clic sur le bouton “Réorienter”
**Alors,** le système affiche le formulaire de réorientation.

**Étant donné que,** je suis sur le formulaire “Réorienter un bénéficiaire”
**Lorsque,** je sélectionne via des menus déroulants, le type d’orientation*, nom de la structure* d’accueil et le nom du référent* (*Champs obligatoires) puis que je clic sur le btn “Valider”
**Alors,** le système affiche un message de confirmation “Êtes-vous sûr de vouloir réorienter le bénéficiaire  ? (Si validé par l’utilisateur, le système n’affiche plus la demande dans la liste des demandes de réorientation)

**Étant donné que,** je suis sur le formulaire “Réorienter un bénéficiaire”
**Lorsque,** je clique sur le menu déroulant pour sélectionner une structure
**Alors,** le système affiche la liste des structures avec le nombre de bénéficiaires pris en charge pour chaque structure.

**Étant donné que,** je suis connecté à mon compte CO et que je suis sur le carnet du bénéficiaire.
**Lorsque,** je clic sur le bouton ”Maintenir l’accompagnement”
**Alors,** le système affiche un message de confirmation “Êtes-vous sûr de vouloir maintenir l’accompagnement ?”.

## Maquette

[https://www.figma.com/file/OEoXoZj2QLqePvxrnuKHBT/MAQ---V1.7---CHARGÉ-D'ORIENTATION?node-id=746%3A98981](https://www.figma.com/file/OEoXoZj2QLqePvxrnuKHBT/MAQ---V1.7---CHARG%C3%89-D'ORIENTATION?node-id=746%3A98981)

**Comment by HEYGUL** [comment]
On n'a jamais de limite de nombre de caractères, on est sûr qu'on veut imposer 255 car. max pour le motif ?

**Comment by JonathanRaimond** [comment]
De mémoire lors des échanges avec les départements sur le parcours de réo, j'avais noté qu'il y avait une limite de caractère  pour le motif. Cependant on peut ne pas mettre de limite dans un premier temps et l'ajouter ultérieurement si le besoin remonte du terrain.

**Comment by HEYGUL** [comment]
@JonathanRaimond est-ce que dans le formulaire de réorientation tous les champs sont obligatoires (Orientation / Structure d'accompagnement / Référent Unique) ?

**Comment by HEYGUL** [comment]
Ok, mais dans l'application il est déjà possible de choisir uniquement une structure.
Ici une démo quand tu es connecté en tant que "manager"
![QuickTime movie](https://user-images.githubusercontent.com/2989532/202271103-dd4bbb92-e19a-4885-9744-eece81411db3.gif)

**Comment by JonathanRaimond** [comment]
Ok pour moi. Finalement je ne vais pas ajouter d'issue spécifique pour le comptage des bénéficiaires car ça doit faire partie de cette issue. J’ai ajouté sur la maquette un écran pour l'affichage du nombre de bénéficiaires par structure et j’ai mis à jour l’issue en ajoutant un critère d’acceptation.
