### ISSUE TITLE
ETQ ancien référent je reste actif pendant 30 jours

### ISSUE THREAD

**Issue by JonathanRaimond** [gip-inclusion/carnet-de-bord#1167]
### Problème :

Les référents ont parfois besoins de renseigner un changement de situation pendant la transition entre l’ancien accompagnement et le nouveau mais n’ont plus accès au carnet.

### Scénario:

Le référent se connecte à son compte pour mettre à jour le carnet du bénéficiaire.

### Critères d’acceptation

- **Étant donné que,** je suis connecté à mon compte pro et que je suis sur la page d’accueil
- **Lorsque,** je clic sur l’onglet “Annuaire de mes bénéficiaires”
- **Alors,** j’ai accès en lecture et écriture au carnet du bénéficiaire pendant 30 jours à partir de la date de réorientation (l’ancien référent reste actif mais n’a plus le statut de référent).

**Comment by jonathanperret** [comment]
@JonathanRaimond @lkouad en parlant de cette issue tout à l'heure avec les devs, on se demandait si l'accès maintenu pendant 30 jours était un besoin métier ou simplement une proposition pour laisser à l'ancien référent le temps d'aller confirmer que le bénéficiaire a bien été réorienté.

Si c'est cette dernière raison, comme alternative moins coûteuse, on peut par exemple envisager que le référent voie la liste des demandes de réorientation qu'il a effectuées avec un statut "acceptée/refusée".

S'il y a en revanche un vrai besoin de conserver l'accès pendant 30 jours, alors il faudra probablement qu'on introduise une notion de date limite d'accès à un carnet et exposer cette information dans tous les bons endroits. D'autres questions apparaissent comme par exemple, cette règle des 30 jours s'appliquerait-elle pour toute réorientation faite par le conseiller d'orientation même si elle ne fait pas suite à une demande émanant du référent ?

**Comment by JonathanRaimond** [comment]
Hello, désolé pour le délai de réponse.
Le maintien de l’ancien référent dans le groupe de suivi, est un besoin métier.
Exemple de M. Bertrand, qui vient de terminer son premier accompagnement et qui fait face à un problème de logement alors qu’il ne connaît pas encore son nouveau référent, il appelle son ancien référent qu’il connaît et avec qui il a instauré une relation de confiance. Le référent n’a plus accès au carnet du bénéficiaire et donc il ne peut plus mettre à jour son diagnostic ou ajouter un plan d’action. Ces informations ne peuvent pas être partagées avec le nouveau référent.
Concernant la période de 30 jours, elle permet de laisser suffisamment de temps pour faire la transition avec le nouveau référent. J’ai eu un retour d’une conseillère qui me confiait ne plus avoir accès au carnet d’un bénéficiaire pour renseigner un changement de situation socio professionnelle.

**Comment by jonathanperret** [comment]
@JonathanRaimond OK merci pour ces précisions. Ce besoin est donc à prendre en compte, indépendamment du mécanisme spécifique de réorientation.

**Comment by bChiquet** [comment]
Discussion avec Laetitia et Jonathan : 
* réaffirmation que le point important est que l'ancien conseiller garde l'accès au carnet après la réaffectation, pas tant le fait de couper l'accès au carnet après 30 jours (ce qui est déjà le cas avec l'implémentation actuelle).
* Avec l'arrivée prochaine de features pour qu'un conseiller puisse directement s'assigner et se retirer d'un carnet, le retrait du carnet après 30 jours est moins prioritaire.
* L'ancient référent doit être identifiable dans le carnet.
* Ce serait bien d'avoir l'historique du groupe de suivi.

Exploration: 
* Actuellement, lorsqu'une réorientation est acceptée, le référent devient `former referent`. La modification n'est pas datée.
* Si cet ancient référent redevient référent, c'est la même ligne qui est fixée à `referent`, sans date de modification.
