### ISSUE TITLE
ETQ ancien référent je suis notifié de la décision du CO suite à ma demande de réorientation

### ISSUE THREAD

**Issue by JonathanRaimond** [gip-inclusion/carnet-de-bord#1222]
### Problème :

Les référents ne sont pas notifié du résultat de leur demande de réorientation (maintien de l’accompagnement ou réorientation).

### Scénario:

Le référent se connecte à son compte pour consulter l’état de la demande de réorientation de l’un de ses bénéficiaires.

### Critères d’acceptation

**Étant donné que,** j’ai reçu un courriel de notification
**Lorsque,** j’ouvre le courriel
**Alors,** je peux consulter la décision prise par le Chargé d’orientation.

**Étant donné que,** je suis connecté à mon compte pro et que je suis sur “Annuaire de mes bénéficiaires”
**Lorsque,** je clic sur l’icône “Voir le carnet”
**Alors,** je peux consulter la décision prise par le Chargé d’orientation. (demande de réorientation effectuée le jj/mm/aaaa et le statut de la demande

**Étant donné que,** je suis connecté à mon compte PRO et que je suis sur la page d’accueil
**Lorsque,** je clic sur l’onglet “Mes bénéficiaires”
**Alors,** je suis redirigé sur la liste de mes bénéficiaires et je peux différencier visuellement les bénéficiaires sans demande de réorientation de ceux avec demande de réorientation (demande de réorientation effectuée le jj/mm/aaaa et le statut de la demande)

### Maquette

[https://www.figma.com/file/LxSA1VswWm0ugNpHQ2tssG/MAQ---V1.7---PRO?node-id=198%3A58436](https://www.figma.com/file/LxSA1VswWm0ugNpHQ2tssG/MAQ---V1.7---PRO?node-id=198%3A58436)

![Desktop - 148](https://user-images.githubusercontent.com/85908681/202699256-196adbf1-6454-40c8-8986-4892e3216ca0.png)

**Comment by HEYGUL** [comment]
@JonathanRaimond J'ai fait des retours sur les modèles de courriel directement dans Figma.
Je pense qu'il manque également les courriels lors d'un maintien de l'orientation.
Doit-on envoyer un courriel pour toute réorientation (ie que l'on passe par une demande / que l'on change l'affectation depuis une liste / etc ...)
