### ISSUE TITLE
ETQ CO je réoriente ou maintien l’accompagnement d’un bénéficiaire depuis la liste des bénéficiaires

### ISSUE THREAD

**Issue by JonathanRaimond** [gip-inclusion/carnet-de-bord#1223]
### ### Problème :

Les Chargés d’orientation ont besoin d’appréhender le parcours et la situation d’un bénéficiaire (éventuellement mettre à jour le carnet) pour adapter son orientation lors d’un comité de suivi 

### ### Scénario:

Le Chargé d’orientation consulte le carnet du bénéficiaire pour adapter le type d’orientation 

### ### Critères d’acceptation

**Étant donné que,** je suis connecté à mon compte CO et que je suis sur le carnet du bénéficiaire.
**Lorsque,** je clic sur le bouton “Réorienter”
**Alors,** le système affiche le formulaire de réorientation.

**Étant donné que,** je suis sur le formulaire “Réorienter un bénéficiaire”
**Lorsque,** je sélectionne via des menus déroulants, le type d’orientation, nom de la structure d’accueil et le nom du référent puis que je clic sur le btn “Valider”
**Alors,** le système affiche un message de confirmation “Êtes-vous sûr de vouloir réorienter le bénéficiaire  ? (Si validé par l’utilisateur, le système n’affiche plus la demande dans la liste des demandes de réorientation)

### ### Maquette

[https://www.figma.com/file/OEoXoZj2QLqePvxrnuKHBT/MAQ---V1.7---CHARGÉ-D'ORIENTATION?node-id=746%3A98918](https://www.figma.com/file/OEoXoZj2QLqePvxrnuKHBT/MAQ---V1.7---CHARG%C3%89-D'ORIENTATION?node-id=746%3A98918)

**Comment by HEYGUL** [comment]
@JonathanRaimond 
Lors de la réorientation, sur les maquettes et lors d'un traitement d'une demande, il n'y a pas de message de confirmation.
Je le supprime des critères d'acceptation.

Autre point, parfois on affiche l'orientation et parfois le type d'orientation. C'est subtil mais dans les maquettes on a un mélange féminin / masculin.
Pour la cohérence et la simplicité, peut-on choisir un terme (et par conséquent el genre) unique ?

**Comment by JonathanRaimond** [comment]
Pour le type d'orientation, je pense que ce serait mieux de remplacer "Type d'orientation" par "Orientation" et de mettre les différents types au féminin.
Modifications à réalisées sur :
• Le champs de saisie sur le formulaire d'orientation et de réorientation
• Titre de colonne dans le tableau des bénéficiaires

**Comment by lionelB** [comment]
J'étais parti sur `Type d'orientation` car on  a aussi  Orientation avec `orienté` et `à orienté`

**Comment by JonathanRaimond** [comment]
Actuellement on a un filtre « Statut » pour filtrer la colonne « Orientation » ce qui n'est pas très intuitif. Voici ce que je propose…

« Type d'orientation » >> « Orientation » 
- Sociale
- Professionnelle
- Socioprofessionnelle

« Orientation » >> « Statut »
- À orienter
- Orienté
