### ISSUE TITLE
Je veux pouvoir identifier rapidement la situation personnelle et professionnelle du bénéficiaire afin de l'accompagner (refonte design)

### ISSUE THREAD

**Issue by lkouad** [gip-inclusion/carnet-de-bord#1257]
Problème: Actuellement les informations sont silotées dans des blocs accordéons et ne permettent pas au pro d'avoir une vue rapide de l'ensemble des informations personnelles et professionnelles.

Solution: Enlever les accordéons et restructurer l'informations à fin d'avoir une vue d'ensemble lisible et compréhensible rapidement 

Maquette : [Lien Figma](https://www.figma.com/file/LxSA1VswWm0ugNpHQ2tssG/MAQ---V1.7---PRO?node-id=101%3A16299&t=iBZoq36n6PTYPAro-1)

![Image](https://user-images.githubusercontent.com/85908681/202584810-f8b788c2-9e72-4e20-9297-4b4effaa8f28.png)

Correspondance des données :

![Image](https://user-images.githubusercontent.com/115156041/208065947-448beb9e-9b14-4737-ac53-57a73a27f0da.png)

![Image](https://user-images.githubusercontent.com/115156041/208065971-a0b89342-d3bd-42bc-857c-dd645f125dbe.png)

**Comment by jonathanperret** [comment]
Créée par erreur dans le mauvais repo.

**Comment by jonathanperret** [comment]
Oups, j'ai fermé par erreur celle qui était dans le bon repo 🤦‍♂️

**Comment by jonathanperret** [comment]
Les accordéons ont été enlevés dans #1242 .

**Comment by lkouad** [comment]
@jonathanperret nouas avons restructurer l'info

**Comment by jonathanperret** [comment]
@lkouad Oui c'est clair pour moi que cette issue n'est pas terminée avec la suppression des accordéons, désolé si j'ai été trop bref, je voulais simplement noter qu'une première partie avait été faite dans la PR mentionnée.
