### ISSUE TITLE
ETQ pro, je peux trouver un bénéficiaire (BRSA ou non-BRSA) sans être dans son groupe de suivi 

### ISSUE THREAD

**Issue by lkouad** [gip-inclusion/carnet-de-bord#1270]
## Problème: 
Depuis l'annuaire un pro accède uniquement à l'annuaire de ses bénéficiaires la barre de recherche de l'écran d'accueil ne lui permet pas de voir ceux dont il n'est pas dans le groupe de suivi  
## Solution: 
Permettre aux profils `professional` de rechercher, et d'accéder au carnet de bord de n'importe quel bénéficiaire uniquement en lecture 
## Critères d'acceptation
Scénario: l'utilisateur `professional` recherche un bénéficiaire sans être dans son "notebook-member' 
```gherkin
Étant donné que je suis un `professional` et que je suis connecté à la page accueil  
Quand je recherche un bénéficiaire par les critères de la barre de recherche  
Lorsque je clique sur rechercher
Alors Je vois la liste des bénéficiaires qui correspondent

**Comment by jonathanperret** [comment]
> Dépendance: US je peux demander mon accès en écriture depuis le carnet de bord d'un bénéficiaire.

Pour clarifier, dans quel sens est-ce que tu vois la dépendance @lkouad ? Il faut avoir cette possibilité de demander l'accès en écriture avant de leur ouvrir l'accès en lecture, ou bien il faut que l'accès en lecture soit généralisé avant qu'ils puissent demander un accès en écriture ?

**Comment by lkouad** [comment]
Pour Info https://github.com/gip-inclusion/carnet-de-bord/issues/424

**Comment by lionelB** [comment]
@JonathanRaimond  @jujumoreau  EC'est ok si on renomme la page `Annuaire de mes bénéficiaires` en `Bénéficiaires` 
et que par défaut sur cette page on n'affiche des bénéficiaires sur forme de table qu'une fois qu'on a fait une recherche ?

**Comment by lkouad** [comment]
> @JonathanRaimond @jujumoreau EC'est ok si on renomme la page `Annuaire de mes bénéficiaires` en `Bénéficiaires`
> et que par défaut sur cette page on n'affiche des bénéficiaires sur forme de table qu'une fois qu'on a fait une recherche ?

@vjousse tu parles de cette question?

**Comment by lkouad** [comment]
#### Probleme #1:  depuis la page d'accueil je peux rechercher tous les bénéficiaires sans être dans le notebook member

Senario: je recherche un bénéficiaire depuis l'accueil sans être dans le notebook member
`gherkin
Étant donné que je suis connecté à la page accueil  
Quand je recherche un bénéficiaire dont je ne suis pas dans le notebbook member
Lorsque je rentre les critères dans la barre de recherche  de l'ecran d'accueil
Lorsque je clique sur rechercher
Alors Je vois la liste des bénéficiaires qui correspondent sur l'ecran d'acceuil
Lorsque je clique sur le resulat de recherche 
Alors le carnet s'ouvre en lecture`

Senario 2: je recherche un bénéficiaire dont je suis dans le notebook number depuis l'écran d'accueil
`gherkin
Étant donné que je suis connecté à la page accueil  
Quand je recherche un bénéficiaire dont je suis dans le notebbook member
Lorsque je rentre les critères dans la barre de recherche  de l'ecran d'accueil
Lorsque je clique sur rechercher
Alors Je vois la liste des bénéficiaires qui correspondent sur l'ecran d'acceuil
Lorsque je clique sur le resulat de recherche 
Alors le carnet s'ouvre en ecriture

#### Probleme 2: depuis l'annuaire de mes beneficiaires je doit acceder uniquement au bénéficiaire pour lesquels je suis dans le notebook member
Senario: j'accède à l'annuaire de mes bénéficiaires
`gherkin
Étant donné que je suis sur l'annuaire de mes beneficiaires
Quand je recherche un bénéficiaire dont je suis  dans le notebbook member
Lorsque je clique sur rechercher
Alors Je vois les resultats dans ma liste 
Lorsque je clique sur le carnet
Alors le carnet s'ouvre en ecriture`

Senario: j'accède à l'annuaire de mes bénéficiaires et recherche un benéficiaire dont je ne suis  dans le notebook member
`gherkin
Étant donné que je suis sur l'annuaire de mes beneficiaires
Quand je recherche un bénéficiaire dont je ne suis pas dans le notebbook member
Lorsque je clique sur rechercher
Alors Je vois un message "aucun resultat dans mon annuaire. Souhaitez-vous étendre votre recherche sur le territoire?
Lorsque je clique sur oui 
Alors je suis renvoyé sur la page d'accueil`

@vjousse et @lionelB je pense que nous pouvons simplifier mais en gros voici le parcours
