### ISSUE TITLE
Corriger la prise en compte des accents dans la recherche de bénéficiaires

### ISSUE THREAD

**Issue by jbuget** [gip-inclusion/carnet-de-bord#1280]
Bug vu en démo sprint 22.

Etant donné que je suis connecté en tant que admin PDI
Et que j'ai ajouté au préalable un bénéficiaire dont le nom est "Démo"
Et que je suis sur la page de listing des bénéficiaires
Quand j'effectue une recherche en saisissant le nom "Démo"
Alors je vois bien l'utilisateur remonter

Cas de tests : 
- étienne
- Bugé
-émiliañho 🇧🇷

**Comment by lionelB** [comment]
closed by #1306
