### ISSUE TITLE
Corriger les résultats remontés dans la recherche de bénéficiaires

### ISSUE THREAD

**Issue by jbuget** [gip-inclusion/carnet-de-bord#1281]
Bug vu en démo sprint 22.

### Ce qu'on a

Aujourd'hui il y a un comportement étrange, en tant que Admin PDI ou CO, lorsque l'on utilise la recherche de bénéficiaires par nom.

Imaginons que j'ai un usager "Demototo", les cas suivants ne remontent pas l'utilisateur : 
- "Demo"
- "emoto"
- "mot"
- "moto"

En revanche les cas suivants fonctionnent : 
- "oto"
- "moto"
- "mototo"

### Ce à quoi on s'attend

On aimerait que l'usager soit remonté pour chacun des cas énoncé ci-dessus.

**Comment by lionelB** [comment]
closed by 1306
