### ISSUE TITLE
ETQ pro je peux accéder à un carnet de bord en lecture sans être membre du groupe de suivi

### ISSUE THREAD

**Issue by lkouad** [gip-inclusion/carnet-de-bord#1324]
## Problème:
Les professionnels ne peuvent pas accéder aux informations d'un bénéficiaire afin de les renseigner si ils ne sont pas dans le groupe de suivi
## Solution
Permettre aux profils pro de pouvoir accéder en lecture aux informations du carnet de la personne
## Acceptance
Scénario: l'utilisateur `professional` souhaite accéder au informations d'une personne sans être dans son "notebook-member' 
```gherkin
Étant donné que la fonction recherche  m'affiche la liste des bénéficiaires correspondant
Lorsque je clique sur le bénéficiaire
Alors J'accède en lecture aux Informations personnelles
Alors j'accède en lecture aux informations "groupe de suivi"

**Comment by lionelB** [comment]
Est il possible de préciser si il faut aussi afficher le les informations socio-pro, le plan d'action et l'historique de parcours

**Comment by jujumoreau** [comment]
![Desktop - 131](https://user-images.githubusercontent.com/115156041/206170239-563a72a6-324e-48b8-a0a0-d94a5c681470.png)

**Comment by lionelB** [comment]
merci @jujumoreau :+1:

**Comment by lionelB** [comment]
les rendez vous c'est vouly ou c'est un oubli ?

**Comment by lkouad** [comment]
@lionelB  avec @jujumoreau nous comprenons pas la question sur les RDV
