### ISSUE TITLE
ETQ pro je peux demander d'être détaché d'un carnet afin de ne plus acceder à celui ci

### ISSUE THREAD

**Issue by lkouad** [gip-inclusion/carnet-de-bord#1335]
## Problème: 
Les professionnels rattaché à un carnet peuvent pour diverses raisons (erreur, fin d'accompagnement...) demander à se détacher du groupe de suivi d'un bénéficiaire, 
## Solution: 
Permettre aux profils `professional` de se détacher  depuis le carnet de la personne ETQ référent
## Critères d'acceptation
Scénario: l'utilisateur `professional` se detache d'un bénéficiaire ETQ référent 
```gherkin
Étant donné que je suis un `professional` membre du groupe de suivi d'un bénéficiaire 
Quand j'accède au groupe de suivi du bénéficiaire
Alors je vois une ligne qui comporte mon nom
Lorsque je clique sur le bouton "se détacher"
Alors un formulaire me demande de "Vous souhaitez être retiré du carnet de bord et ne plus accéder à celui ci? "
Lorsque je clique oui 
Alors je donne le motif: (à decrire)
Lorsque je clique sur valider
Alors je suis inactif
Alors le motif et la date de ma demande de retrait sont historisé
```

**Comment by lionelB** [comment]
On le fait pas !  C'est l'admin de structure qui le fera

**Comment by HEYGUL** [comment]
Le message de confirmation est un peu trompeur car le professionnel aura toujours accès au carnet.
De plus, le bouton se nomme "Se détacher" mais on parle de "retiré" dans le message de confirmation, ce serait mieux de garder un nom de concept unique pour cette action.

**Comment by jujumoreau** [comment]
Après éclaircissement, les conditions de Charles sont les bonnes. 
- Si le référent est le seul à intervenir de la structure, lorsqu'il se détache, que ça détache aussi l'usager de la structure.
- S'il y a d'autres pros de la structure, le détachement de la structure ne se fait pas.

Pour le message de confirmation, on lui notifie qu'il n'aura plus accès en écriture au carnet, car effectivement il aura toujours accès en lecture. 

Et en ce qui concerne le bouton, effectivement il est mieux de rester sur le même verbe d'action, donc "détacher".

**Comment by jujumoreau** [comment]
## Critères d'acceptation (mise à jour)
Scénario: l'utilisateur `professional` se detache d'un bénéficiaire ETQ référent 
```gherkin
Étant donné que je suis un `professional` membre du groupe de suivi d'un bénéficiaire et que je suis le seul de ma structure à l'être
Quand j'accède au groupe de suivi du bénéficiaire
Alors je vois une ligne qui comporte mon nom
Lorsque je clique sur le bouton "se détacher"
Alors un formulaire me demande "Souhaitez-vous être détaché du carnet de bord et ne plus accéder en écriture à celui-ci ?"
Lorsque je clique oui 
Alors je suis inactif
Alors la date du détachement est historisée
Alors le bénéficiaire est aussi détaché de la structure
```

```gherkin
Étant donné que je suis un `professional` membre du groupe de suivi d'un bénéficiaire et que je ne suis pas le seul de ma structure à l'être
(...)
Alors le bénéficiaire n'est pas détaché de la structure
```
