### ISSUE TITLE
Historisation des mouvements de membres dans le groupe de suivi

### ISSUE THREAD

**Issue by lionelB** [gip-inclusion/carnet-de-bord#1340]
En tant que pro ou chargé d'orientation, il est utile de pouvoir consulter un historique du groupe de suivi pour mieux comprendre le parcours d'accompagnement du bénéficiaire.

**Comment by jbuget** [comment]
Ce qui a été fait en lien avec cette issue, c'est qu'on stocke des données qui devraient permettre un jour d'afficher l'historique. On a donc bien de l'historisation, mais pas de consultation.
