### ISSUE TITLE
Migrer Metabase de la Fabrique vers Scalingo

### ISSUE THREAD

**Issue by jbuget** [gip-inclusion/carnet-de-bord#1345]
Un chantier est entamé pour migrer les services infogérés via la Fabrique des Ministères sociaux vers l'infra du GIP.

Parmi les composants à migrer, il y a Metabase.

- l'adresse existante : https://matomo-metabase-carnetdebord.fabrique.social.gouv.fr
- l'adresse cible (en attendant d'avoir une URL définitive) : https://cdb-metabase-production.osc-secnum-fr1.scalingo.io

**Comment by jbuget** [comment]
TODO : 
- [ ] assurer de la rétrocompatibilité : faire en sorte que l'ancienne URL pointe vers la nouvelle instance (`ALIAS` / `CNAME`, tout ça…)

**Comment by lionelB** [comment]
je ferme. Metabase a été migré https://cdb-metabase-production.osc-secnum-fr1.scalingo.io
