### ISSUE TITLE
Migrer Tipimail de la Fabrique vers compte Tipimail ou SendInBlue (transactionnel CDB)

### ISSUE THREAD

**Issue by jbuget** [gip-inclusion/carnet-de-bord#1347]
Dans le cadre de la migration de services depuis l'infra de la Fabrique vers celle du GIP, on se propose de changer de fournisseur de SMTP : passer de Tipimail à Sendinblue (pour lequel le GIP a déjà un compte).

- [ ] Obtenir des identifiants SMTP pour le compte SendInBlue du GIP
- [ ] Modifier la configuration d'envoi d'email en production (`cdb-app` et `cdb-backend`)

**Comment by lionelB** [comment]
je ferme, on est finalement passé sur le tipimail du gip (et pas sendinblue pour des raison pragmatique d'aipd)

**Comment by jonathanperret** [comment]
Oui, on a ouvert un Tipimail pour le GIP avec un sous-compte pour CdB. Et toutes les applications sont migrées dessus.
