### ISSUE TITLE
L'import de rattachement de bénéficiaires par le permet de créer des référents en doublon.

### ISSUE THREAD

**Issue by bChiquet** [gip-inclusion/carnet-de-bord#1354]
Actuellement, le rattachement de bénéficiaires à un référent par import effectué par un admin structure ne gère pas l'unicité de référent. Il permet donc de créer des doublons de référents.

Ce comportement ne sera plus possible avec cette PR:
https://github.com/gip-inclusion/carnet-de-bord/pull/1353
Le message qui apparaîtra sera : 'Ce rattachement existe déjà.'

Un test présent pour valider cette feature introduisait un doublon de référent. Le doublon a été supprimé dans ce commit:
https://github.com/gip-inclusion/carnet-de-bord/pull/1353/commits/0b47e69970219d2907a36c165ddde2496994b8af

Reste à trancher : comment le rattachement de bénéficiaire par l'admin de structure doit-il fonctionner quand un référent est déjà attaché au bénéficiaire ?

**Comment by lionelB** [comment]
est ce qu'on laisse cette feature ?
