### ISSUE TITLE
ETQ Admin de Territoire, je veux faire en sorte qu'il y ait un fichier unique d'import des données bénéficaires dans RDV-I et CDB

### ISSUE THREAD

**Issue by jbuget** [gip-inclusion/carnet-de-bord#1368]
Ajouter la colonne `role` (ou vérifier qu'on peut supporter d'avoir des colonnes dont on ne fait rien sans que ça ne casse l'import).

Critères / démo : 
- je me connecte à RDV-I, je fais un import avec un fichier -> ca marche (mais on n'importe pas les données inutiles)
- je fais la même dans CDB -> ça marche aussi

Notes
- pour RDV-I le numéro de CAF est obligatoire mais pas dans CDB ; on assume que la solution n'est pas parfaite

**Comment by jbuget** [comment]
Obtenir un accès auprès de RDV-I.
Obtenir des jeux de fichier.

**Comment by bChiquet** [comment]
https://rdv-insertion.gitbook.io/guide-dutilisation-rdv-insertion/detail-des-actions-par-role/le-secretaire/importer-et-inviter-des-usagers

**Comment by bChiquet** [comment]
Ticket bloqué parce qu'après discussion de daily, on ne sait pas si c'est la bonne chose à faire : https://www.figma.com/file/QQ8WGwp0dB1V7eQsgDGHIZ/Untitled?node-id=0%3A1&t=fQpbjnf4gIyJz3mq-1

**Comment by lionelB** [comment]
remplacé par #1440
