### ISSUE TITLE
ETQ CO je dois pouvoir me rattacher à un carnet

### ISSUE THREAD

**Issue by chdechamps** [gip-inclusion/carnet-de-bord#1371]
**Problème :** 
Suite à la suppression des anciens formulaires de changement d'orientation, de référent et de structure. #1352 le chargé d'orientation ne peut plus s'assigner à un carnet.

**Solution :**
Permettre aux Chargés d'Orientation de s'assigner à nouveau à un carnet en tant que CO.

**Comment by lionelB** [comment]
fixed in #1338
