### ISSUE TITLE
Si c'est rapide et pertinent et possible (timebox 1/2 journée) traquer le bouton "se rattacher à un groupe de suivi" depuis la page Inscription

### ISSUE THREAD

**Issue by bChiquet** [gip-inclusion/carnet-de-bord#1372]

**Comment by bChiquet** [comment]
Après discussion avec @jbuget, c'est lié à la [PR #1365](https://github.com/orgs/gip-inclusion/projects/6/views/1).
Du coup, c'est le rattachement d'un pro à un carnet qu'on souhaite tracker.

**Comment by bChiquet** [comment]
commité au sein de #1365

**Comment by lionelB** [comment]
J'ia du mal à voir le rapport avec la #1365 car cette issue par du principe que le pro n'est pas encore inscrit à la plateforme
