### ISSUE TITLE
ETQ admin de structure lorsque je choisi Tous dans la liste des bénéficiaires je vois trop de bénéficiaires

### ISSUE THREAD

**Issue by lionelB** [gip-inclusion/carnet-de-bord#1380]
On voit des bénéficiaires qui ne sont pas dans ma structure

**Comment by JonathanRaimond** [comment]
Hello.
Est-ce que les référents grisés (btn inactif) dans la liste des bénéficiaires, sont des référents d’une autre structure ?
Si oui, on peut toujours voir des bénéficiaires suivent par d’autres structures

Pour info on a encore des soucis sur les compteurs du nombre de bénéficiaires : 

**Jacque Celaire** (7 bénéficiaires dont le référent est grisé)
Carte (Accueil) > 39
Dashboard > Rattachés : 7 Non rattachés : 27 = 34
Liste bénéficiaires (tous) > 39

**Vincent Timaitre** (4 bénéficiaires dont le référent est grisé)
Carte (Accueil) > 23	
Dashboard > Rattachés : 7 Non rattachés : 16 = 23
Liste bénéficiaires (tous) > 25

**Comment by chdechamps** [comment]
Également, quand un pro se détache, le bénéficiaire n'apparait plus dans la liste des bénéficiaires de la structure sauf : 
- sur le total de bénéficiaire depuis la carte (accueil)
- dans la liste des bénéficiaires lorsque le responsable de structure sélectionne "tous" (mais il ne peu pas désigner de pro en référent unique, probablement du fait que le pro se soit retiré)

**Comment by lionelB** [comment]
> Est-ce que les référents grisés (btn inactif) dans la liste des bénéficiaires, sont des référents d’une autre structure ?
> Si oui, on peut toujours voir des bénéficiaires suivent par d’autres structures

le bénéficiaire grisé = un pro de la structure est dans son groupe de suivi mais le bénéficiaire n'est pas assigné à la structure

sur le pb du nb dans la tuile, j'avais effectivement vu, je pensais le faire dans une autre pr
