### ISSUE TITLE
Remettre en place la thématique "numérique" dans les axes de travail.

### ISSUE THREAD

**Issue by bChiquet** [gip-inclusion/carnet-de-bord#1386]
Y migrer les situations suivantes : 
- Absence d'adresse de messagerie
- Absence d'équipement ou de connexion
- Accès ou utilisation difficile des outils numériques

**Comment by bChiquet** [comment]
Actuellement, les objectifs/actions sont sélectionnées en fonction du hème sélectionné.
Du coup, il n'y a pas d'objectif/action disponible une fois l'axe de travail créé.

Proposition : dupliquer les actions disponibles pour numérique

**Comment by bChiquet** [comment]
Pour le moment j'ai ajouté les target suivantes pour le thème numérique :
* Travailler l’accès à une prestation
* Accompagnement dans les démarches numériques
* Mise en place d'une mesure d'accompagnement adapté

**Comment by JonathanRaimond** [comment]
Ok pour moi.

**Comment by lionelB** [comment]
Close by #1400
