### ISSUE TITLE
ETQ CO, je veux voir les structures par type d'accompagnement (dispositif) pour une orientation ou une réorientation

### ISSUE THREAD

**Issue by JonathanRaimond** [gip-inclusion/carnet-de-bord#1394]
## :thinking: Contexte et problème observé
> En tant que chargé d'orientation, j’ai besoin de trouver une structure/référent dont le dispositif est adapté au besoin du bénéficiaire afin de l’orienter/réorienter.

### :horse: Proposition de solution
Dans la liste déroulante des types d’orientation, afficher les différents types d’orientation (pro, sociopro, social). Si le type d’orientation est rattachés à des dispositifs, afficher une nouvelle liste déroulante contenant la liste des types de dispositifs correspondant au type d’orientation sélectionné.

### :unicorn:  Solutions écartées
Dans la liste déroulante des types d’orientation, remplacer les types d’orientation par les types de dispositifs serait bloquant pour certains départements qui n’ont pas de dispositifs mais seulement des types d’orientation.

Suite de cette issue : https://github.com/gip-inclusion/carnet-de-bord/issues/1395

**Comment by jbuget** [comment]
Ex: ce qu'on a actuellement et qu'on aimerait ne plus avoir
1. se connecter avec Giulia (CO)
2. accéder au carnet de "Etta Bullock" (bénéficiaire orienté)
3. entamer la procédure de "réorientation"
4. saisir "social" comme type d'accompagnement
5. 🐞 on peut sélectionner comme structure "Pole emploi" alors que c'est une structure de type "profesionnel"

=> on voudrait ne voir que les structures de type "social"

**Comment by JonathanRaimond** [comment]
Suite au point fait avec Charles au daily, la proposition de solution à été modifiée afin de simplifier le formulaire. Vous trouverez ci-dessous la nouvelle proposition.

### :horse: Proposition de solution
Dans la liste déroulante des types d’orientation, afficher les différents types de dispositif en précisant entre parenthèse le type d’orientation (ex: RIA (pro)). Si un type d'orientation n'est pas rattaché à des dispositifs, le type d'orientation (Pro, Sociopro, Social) est affiché par défaut.

Veuillez trouver ci-dessous un schéma permettant de mieux comprendre ce qui doit être enregistré en base et ce qui doit être affiché.

<img width="636" alt="Capture d’écran 2023-01-06 à 15 14 35" src="https://user-images.githubusercontent.com/85908681/211030169-7b0d6047-94f9-4192-92a0-836554a16cf3.png">

**Comment by vjousse** [comment]
:horse: Proposition de solution reformulée

Dans la liste déroulante des types d’orientation, disponible sur le notebook d'un bénéficiaire à orienter (connexion avec `giulia.diaby` -> 3 bénificiaires à orienter -> Voir le carnet de `Benjamin Whitley` -> Bouton Orienter)

![Screenshot from 2023-01-12 16-10-33](https://user-images.githubusercontent.com/154904/212107374-aa7c8c35-1939-4602-8af6-03789ad541f2.png)

Afficher les différents types d’orientation (pro, sociopro, social).

Si le type d’orientation est rattaché à des dispositifs pour le déploiement concerné, afficher une nouvelle liste déroulante contenant la liste des types de dispositifs correspondant au type d’orientation sélectionné.

Ces deux filtres (type d'orientation et dispositif si disponibles) vont permettre de n'afficher que les structures et les pros ayant ce type d'orientation / dispositif.
Le type/dispositif d'orientation possibles pour une structure est calculé/déduit automatiquement à partir des types/dispositifs affectés préalablement (grâce à l'issue #1395 ) à chacun de ses membres.

**Comment by JonathanRaimond** [comment]
Il ne doit y avoir qu'un seul menu déroulant qui s'appel "Type d'orientation" comprenant les types d'orientation + dispositifs (cf schéma ci-dessus)

**Comment by JonathanRaimond** [comment]
Pour faire suite au refinement, voici les pré-requis pour finaliser cette issue :
1. Récupérer du CD (08) un fichier contenant la liste des structures du déploiement et leurs dispositifs associés
3. Assigner en BDD les dispositifs du déploiement
4. Assigner en BDD les dispositifs pris en charge par chaque structure
5. Permettre à l’admin de structure de rattacher aux pros les dispositifs affectés à la structure
