### ISSUE TITLE
ETQ Admin Structure Je peux definir les types d'accompagnement par référent afin de faciliter l'orientation et la réorientation

### ISSUE THREAD

**Issue by JonathanRaimond** [gip-inclusion/carnet-de-bord#1395]
## :thinking: Contexte et problème observé

En tant que chargé d'orientation, j’ai besoin de trouver une structure/référent dont le dispositif est adapté au besoin du bénéficiaire afin de l’orienter.

### :horse: Proposition de solution

Dans le formulaire « Mettre à jour les informations du professionnel » (compte Admin structure), afficher une liste déroulante pour sélectionner le type d’orientation. Si des dispositifs sont rattachés au type d’orientation sélectionné, afficher une liste déroulante pour sélectionner le type de dispositif.

### :unicorn:  Solutions écartées
Dans le formulaire « Mettre à jour les informations du professionnel », afficher uniquement une liste déroulante des types de dispositifs serait bloquant pour certains départements qui n’ont pas de dispositifs mais seulement des types d’orientation.

![Image](https://user-images.githubusercontent.com/85908681/210381262-46a2993f-8590-49fa-b8da-5b142afae556.png)

**Comment by lionelB** [comment]
on peut créer un réutiliser la table orientation_type
changer le champ id en uuid
rajouter une colonne deployment_id (clé étrangère)
modifier les endroit on l'on affiche les type d'orientation (attention dans le backend on utilise une enum en dur)

**Comment by JonathanRaimond** [comment]
Suite au point fait avec Charles au daily, la proposition de solution à été modifiée afin de simplifier le formulaire. Vous trouverez ci-dessous la nouvelle proposition.

### :horse: Proposition de solution
Dans le formulaire « Mettre à jour les informations du professionnel » (compte Admin structure), afficher dans le menu déroulant "Dispositif d'accompagnement" les différents types de dispositif en précisant entre parenthèse le type d’orientation (ex: RIA (pro)).

Veuillez trouver ci-dessous un schéma permettant de mieux comprendre ce qui doit être enregistré en base et ce qui doit être affiché.

<img width="636" alt="Capture d’écran 2023-01-06 à 15 14 35" src="https://user-images.githubusercontent.com/85908681/211032975-e7bdc26f-71b1-460d-b9c3-114fc3e41643.png">

**Comment by vjousse** [comment]
Un peu plus de contexte dans ce thread Mattermost : https://mattermost.incubateur.net/betagouv/pl/hx9baccbs3nsupuy79waoy511w

**Comment by vjousse** [comment]
Suite à discussion avec @JonathanRaimond et @HEYGUL il y a donc trois niveaux d'affectation de type d'orientation et/ou de structure :
- Déploiement : on doit pouvoir attribuer des types d'orientations et des dispositifs à un déploiement. Ce sont les choix d'affectation qui seront proposés pour les structures du déploiement
- Structure : on doit pouvoir attribuer des types d'orientations et des dispositifs à une structure. Ce sont les choix d'affectation qui seront proposés pour les pros appartenant à cette structure
- Pro : on doit pouvoir affecter à un pro les types d'orientation / dispositifs choisis précédemment pour la structure

**Comment by JonathanRaimond** [comment]
C'est ok
