### ISSUE TITLE
ETQ Admin structure Je suis notifié du besoin de rattacher un pro à un bénéficiaire orienté vers ma structure (action nécessaire de la part du responsable)

### ISSUE THREAD

**Issue by JonathanRaimond** [gip-inclusion/carnet-de-bord#1398]
## :thinking: Contexte et problème observé
En tant qu’administrateur de structure j’ai besoin d'être notifié quand des nouveaux bénéficiaires sont orientés ou réorientés vers ma structure sans référent pour effectuer le rattachement aux professionnels.

#### Acceptable
Envoyer un mail de récap tous les jours (7am) pour informer le gestionnaire de structure de tous les bénéficiaires orientés vers sa structure sans référent désigné dans leur portefeuille d'accompagnement (orientation et réorientation).

<img width="760" alt="Capture d’écran 2023-01-16 à 17 21 40" src="https://user-images.githubusercontent.com/85908681/212724837-fc7335fc-7a8d-460d-962a-d22e7f8cc074.png">

#### Optimale
Faire la distinction entre les derniers entrants et ceux en attente. (Liste nominatives des bénéficiaires de la veille + mention de x carnets en attente dont x depuis plus de 7jour)
Envoyer un seul mail si l'admin structure a la gestion de plusieurs structures en séparant les informations de chaque structure.

**Comment by HEYGUL** [comment]
@JonathanRaimond as-tu le template du courriel à envoyer ?
Qu'appelle-t-on nouvelles entrées ?
Est-ce que le courriel contient tous les bénéficiaires de la structure qui n'ont pas de référent ?

Bonus : as-tu la possibilité d'utiliser le nouveau template de ticket ?

Merci !

**Comment by JonathanRaimond** [comment]
L'issue a été mise à jour

**Comment by HEYGUL** [comment]
Merci @JonathanRaimond .
