### ISSUE TITLE
Améliorer l'information du pro après une demande de réorientation

### ISSUE THREAD

**Issue by JonathanRaimond** [gip-inclusion/carnet-de-bord#1399]
Lorsqu'un pro demande de réorienter un bénéficiaire vers un type d'orientation (par exemple professionnel) et que le CO décide d'un type différent (par exemple socio pro), le pro voit dans le bandeau l'orientation qu'il a recommandé et ne sais pas que la décision est différente.

Remplacer "Orientation recommandée" par "Décision d'orientation" et afficher l'orientation validée

![image](https://user-images.githubusercontent.com/117724992/206852259-7ed065e8-2352-4792-9de4-125303673e66.png)

**Comment by JonathanRaimond** [comment]
Il n'y a pas de branche de test ?

**Comment by bChiquet** [comment]
Plus maintenant.
Tu peux check en préprod.
