### ISSUE TITLE
bug: le décompte des bénéficiaires d'une structure pour un administrateur de structure peut être faux

### ISSUE THREAD

**Issue by lionelB** [gip-inclusion/carnet-de-bord#1407]
# 🐛 Problème

⚠️ L'exemple ci-dessus ne fonctionne pas avec les données de seed, les données avaient été modifiées en pré-production lors du test ⚠️ 

Charger les données de seed. Se connecter avec le compte `lara.pafromage` qui est administrateur de structure.

Constater que dans la liste de ses structures, on a une structure (CCAS Livry-Gargan) qui est indiquée comme ayant 33 bénéficiaires :

<img width="438" alt="image" src="https://user-images.githubusercontent.com/300823/210542766-cc634e27-51d2-4a52-a4f5-dad920abac88.png">

Or quand on clique sur cette structure, on voit que le total de bénéficiaires (accompagnés + non accompagnés) est de 34 :

<img width="1044" alt="image" src="https://user-images.githubusercontent.com/300823/210543173-20448ea1-a497-4696-acf2-8b9da814176a.png">

Noter que ce bug apparaît après la correction de #1388 qui portait sur la même fonctionnalité.

## Hypothèse

cas : 1 bénéficiaire affecté à la structure avec 1 `notebook_member` non référent d'une autre structure  dans le groupe de suivi

le problème vient des filtres appliqués pour limiter les lignes du aux jointure 
```
( BS.structure_id = structure_row.id AND BS.status <> 'outdated' AND (P.structure_id IS NULL OR P.structure_id = structure_row.id))
```

**Comment by JonathanRaimond** [comment]
Charger les données de seed ?
Si je me connecte avec la rapafromage ça me donne ceci :

Centre  communal d’action social Livry-Gargan
Carte : 32
Dashboard (8 Bénéficiaires accompagnés + 26 Bénéficiaires non accompagnés) : 34
Liste : 34

Groupe NS
Carte : 21
Dashboard (6 Bénéficiaires accompagnés + 15 Bénéficiaires non accompagnés) : 21
Liste : 21
