### ISSUE TITLE
Page figée après un rattachement

### ISSUE THREAD

**Issue by chdechamps** [gip-inclusion/carnet-de-bord#1427]
Demande reçue sur le chat : 

![Image](https://user-images.githubusercontent.com/117724992/212305086-ffcbd4f3-d4d0-4f71-8748-178973a6d7a3.png)

**Comment by chdechamps** [comment]
Pour info, exemple de ce que ça fait en prod. 

![Image](https://user-images.githubusercontent.com/117724992/212358828-6948f059-a809-499f-b6b8-8d3d6ce16369.png)

**Comment by lionelB** [comment]
Proposer de se deconnecter / reconnecter et voir si le pb persiste

**Comment by chdechamps** [comment]
Quand la personne se déconnecte, elle peux a nouveau accéder a d'autres dossiers, mais le bug persiste (retour utilisateur il y a 1h).

**Comment by JonathanRaimond** [comment]
J'ai remis cette us en in progress car elle a été réouverte et depuis elle est restée non cloturée.

**Comment by HEYGUL** [comment]
Avez-vous des exemples d'utilisateurs qui rencontrent encore le problème. Cela nous aidera à l'analyse.

**Comment by chdechamps** [comment]
En dehors du screen fait et anonymisé qui montre bien le volet figé blanc sans contenu affiché... Je n'ai pas d'autre élément. De quoi a tu besoin ?

**Comment by HEYGUL** [comment]
Quel type de compte fait un rattachement sur quel carnet pour qu'on essaie de reproduire le pb ?
De notre côté on n'a plus du tout aucune alerte sur cette fonctionnalité.
