### ISSUE TITLE
Voir le nombre des bénéficiaire dans le portefeuille d’une structure

### ISSUE THREAD

**Issue by JonathanRaimond** [gip-inclusion/carnet-de-bord#1436]
# Contexte/problème
ETQ Admin structure Je vois le décompte du nombre de bénéficiaires par structure sur l'accueil et que je fais la somme des bénéficiaires accompagnés et non accompagnés de la structure, je n'ai pas le même nombre

Théoriquement, ce nombre devrait correspondre à la capacité d'accompagnement d'une structure (connu par les personnes de la structure). Ce n'est pas le cas car dans les "bénéficiaires accompagnés" on ne se limite pas à dénombrer le nombre de bénéficiaires rattachés à la structure avec un référent, mais on prend tous les bénéficiaires avec un pro active de la structure dans le groupe de suivi.

Cela a pour effet de gonfler le nombre de personnes accompagnées.

## À noter

Nous n'arrivons pas à reproduire le bug en dev avec les données de seed. Il est probablement du à des soucis de liens dans `beneficiary_structure` qui pourraient être du à une mauvaise utilisation de l'import du fichier de réorientation.
En effet, la structure actuelle de la base permet des états qui devraient être impossibles, comme avoir un bénéficiaire rattaché dans `beneficiary_structure` à une structure `A` et un notebook_member référent attaché à une structure `B`.

## Proposition de solution :
Modifier le calcul des bénéficiaires accompagnés en partant des bénéficiaires rattachés à une structure (lien dans la table `beneficiary_structure`) et qui ont comme référent une personne appartenant à la structure.

EX : 25 bénéficiaires = 20 bénéficiaires rattachés à la structure avec un référent + 5 bénéficiaires rattachés à la structure sans référent de la structure

**Comment by HEYGUL** [comment]
Quand je lis l'exemple je comprend l'inverse de la description de la solution.
Est-ce qu'on peut donner des cas plus concrets ?
Par exemple, quel nombre doit-on affiché si 1 bénéficiaires a un référent et une liaison bénéficiaire/structure et 1 bénéficiaire a un référent mais pas de liaison bénéficiaire/structure ?

**Comment by lionelB** [comment]
@HEYGUL j'ai mis à jour la description de l'issue
