### ISSUE TITLE
Mise à jour du référentiel Thème/Objectif

### ISSUE THREAD

**Issue by JonathanRaimond** [gip-inclusion/carnet-de-bord#1437]
## Contexte :
Dans le cadre de l'amélioration continue, suite au dernier retour d'enquête utilisateur, amélioration du référentiel situation et objectifs. 

## Solution proposée : 
Mettre à jour le référentiel de situation et le référentiel objectifs : https://www.notion.so/gip-inclusion/Refonte-situation-et-ref-5a17fe935c0040b196be10390f95186f

**Comment by lionelB** [comment]
en adaptant un peut le fichier excel, on doit pouvoir réutiliser un précédant outil de génération de migration pour les mise à jour du référentiel. https://github.com/gip-inclusion/carnet-de-bord-outils-referentiel/
