### ISSUE TITLE
ETQ CO / PRO j'ai besoin de consulter un projet professionnel

### ISSUE THREAD

**Issue by JonathanRaimond** [gip-inclusion/carnet-de-bord#1439]
Redécoupée :
- #1521 
- #1522
- #1535 

## :thinking: Contexte et problème observé

Un bénéficiaire en accompagnement peu avoir différents projets professionnels et chacun d'eux peuvent être différent, tant dans leurs spécificités que dans le niveau de maturité.
Les items des blocs formations et emploi devraient être défini selon le(s) projet(s) pro (wanted_job) et non être généralisé dans un axe de travail.

En tant que chargé d'orientation/ référent de parcours, j’ai besoin de consulter le ou les projets professionnels (wanted_job) aux diagnostic socio-prop d'un bénéficiaire et les préciser :
* Par les critères d'offre raisonable d'emploi (salaire minimum attendu (en brut horaire), rayon de mobilité (en km), spécificité de l'emploi (temps plein, partie, horaire adapté, ...)
* par l'identification de points forts et de besoin d'accompagnement parmi les thématiques suivantes "choisir un métier", "se former", Préparer sa candidature", "trouver un emploi", "Créer une entreprise" et "S'ouvrir à l'international".

### :horse: Proposition de solution

Afficher dans le diagnostic socioprofessionnel, un bloc « Projet professionnel » contenant les informations suivantes :
 
- Date de création du projet pro
- Nom de l'auteur du projet pro
- Date de la dernière mise à jour du projet pro
- Nom de l'auteur de la dernière mise à jour du projet pro
- Zone de mobilité
- Salaire minimum
- Temps de travail
- Points d’appui
- Besoins
- État d’avancement du projet pro

Salaire minimum :
Salaire inférieur ou égal à 11,27€ = SMIC
-> Si le salaire renseigné dans le formulaire est inférieur ou égal à 11,27€ alors en front on affiche la valeur “SMIC” au lieu d'un montant en euro
ATTENTION, penser à une solution permettant la mise à jour  automatique chaque année du montant brut/horaire du SMIC.

### :art: Maquette

https://www.figma.com/file/LxSA1VswWm0ugNpHQ2tssG/MAQ---V1.7---PRO?node-id=967%3A74890&t=SfmYJmH2fEnlkTRa-1

<img width="800" alt="Capture d’écran 2023-01-24 à 13 24 27" src="https://user-images.githubusercontent.com/85908681/214291973-62c3c3ed-57d2-4828-b049-f8de01ada4a7.png">

## ℹ : Référentiel objectif (bullet) par thème (number)
1. Choisir un métier
* Identifier ses points fort et ses compétences
*  Connaitre les opportunités d'emploi
* Découvrir un métier ou un secteur d'activité
* Confirmer son choix de métier
2. Se former
* Trouver sa formation
* Monter son dossier de formation
3. Préparer sa candidature
* Valoriser ses compétences
* Réaliser un CV et/ou une lettre de motivation
* Développer son réseau
* Organiser ses démarches de recherche d'emploi
4. Trouver un emploi
* Répondre des offre d'emploi
* Faire des candidatures spontanée
* Suivre ses candidatures et relancer les recruteurs
* Convaincre et recruter en entretien
5. Créer une entreprise
* Définir son projet de création d'entreprise
* Structurer son projet de création d'entreprise
* Développer son entreprise
6. S'ouvrir à l'international
* connaitre les opportunité d'emploi à l'étranger
* S'informer sur les aides pour travailler à l'étranger
* S'organiser suite à son retour en France

**Comment by lionelB** [comment]
Possibilité de n projet pro. 

1 projet pro = 

- 1 wanted_job
- Zone de mobilité (en km).
- Salaire minimum brut horaire (par défaut vide, ou valeur (+règle affichage si valeur < SMIC))
- Temps de travail (par défaut vide) (temps plein / temps partiel)
- date de création
- le créateur
- date de mise à jour
- le metteur à jour (oui, oui!)

et 6 thèmes parmi (bouton radio : Point d'appuis OU Besoins OU non exploré : par défaut non exploré) :
- Choisir un métier
- Se former
- Préparer sa candidature
- Trouver un emploi
- Créer une entreprise
- S'ouvrir à l'international


:waffle:  On ne tient pas compte de la jauge en % sur la maquette.

Point d'attention: 
Nous souhaitons pouvoir lier un objectif (target) à un des 6 thèmes du projet pro.

maquette 
![image](https://user-images.githubusercontent.com/160320/214348402-49dc63a9-a057-4a34-99d4-4d11a341bf1e.png)
