### ISSUE TITLE
[Support 93] Effacement d'un compte

### ISSUE THREAD

**Issue by chdechamps** [gip-inclusion/carnet-de-bord#1498]
### Problème : 
L'admin de territoire s'est accidentellement créée en gestionnaire de structure au lieu d'utiliser son autre email. 

ID concernés : c6ad06d5-2638-42f7-af7b-aff3d94bbc89 & 24e9f902-3995-4f04-a6a3-b84fc1001644

### Solution : 
Supprimer : c6ad06d5-2638-42f7-af7b-aff3d94bbc89 (admin de structure) pour permettre a l'autre compte de se connecter avec l'email (username transmis mais pas friendly).

**Comment by HEYGUL** [comment]
Fait !
