### ISSUE TITLE
ETQ CO Je peux ajouter un motif d'orientation/réorientation

### ISSUE THREAD

**Issue by JonathanRaimond** [gip-inclusion/carnet-de-bord#1514]
## :raised_hand: À faire avant de mettre cette issue dans le sprint backlog…
-> Cette issue est déjà raffinée
-> Pour passer cette issue dans le sprint backlog il faut préalablement raffiner l'issue suivante : [ETQ Pro j'ai besoin de consulter la décision et le motif d'orientation#1536](https://github.com/gip-inclusion/carnet-de-bord/issues/1536) 

## :thinking: Contexte et problème observé
En tant que Manager / Chargé d’orientation, j’ai besoin de saisir le motif d’orientation/réorientation afin de permettre au nouveau référent de prendre connaissance des éléments expliquants la décision d’orientation/réorientation et d’adapté son accompagnement.

### :horse: Proposition de solution
Permettre au Manager et au Chargé d'orientation de saisir un motif d'orientation/réorientation depuis le formulaire "Orienter/réorienter un bénéficiaire" en ajoutant un champ de saisie libre, comme dans le formulaire "Demander une réorientation" (profil pro).

### :ok_hand: Critères d'acceptation

**Etant donnée que** je suis Manager et que je suis sur la liste des bénéficiaires de mon territoire,
**Lorsque** je clique sur le référent unique ("nom du pro" ou "Non rattaché") d'un bénéficiaire,
**Alors** le système affiche le formulaire "Orienter/réorienter un bénéficiaire" où je peux renseigner le type du dispositif, la structure, le référent et le motif d'orientation/réorientation.

**Etant donnée que** je suis Manager/Chargé d'orientation et que je suis sur le carnet d'un bénéficiaire,
**Lorsque** je clique sur le bouton "Orienter/Réorienter",
**Alors** le système affiche le formulaire "Orienter/réorienter un bénéficiaire" où je peux renseigner le type du dispositif, la structure, le référent et le motif d'orientation/réorientation.

**Etant donnée que** je suis Chargé d'orientation et que je suis sur la liste des bénéficiaires,
**Lorsque** je clique sur le référent unique ("nom du pro" ou "Non rattaché") d'un bénéficiaire,
**Alors** le système affiche le formulaire "Orienter/réorienter un bénéficiaire" où je peux renseigner le type du dispositif, la structure, le référent et le motif d'orientation/réorientation.

![Capture d’écran 2023-02-15 à 12 26 35](https://user-images.githubusercontent.com/85908681/219016838-d1db9331-8daf-41f6-a024-32206a0eb970.png)

**Comment by HEYGUL** [comment]
A quel endroit affiche-t-on le motif saisi ?

**Comment by JonathanRaimond** [comment]
Hello, je pense qu'il faut le rendre accessible depuis le bandeau d'orientation.
Sur figma, j'ai regroupé tous les bandeaux d'orientations (pro + co) pour voir ou et quand on doit afficher le btn "Voir le motif d'orientation"

https://www.figma.com/file/LxSA1VswWm0ugNpHQ2tssG/MAQ---V1.7---PRO?node-id=1800%3A115428&t=sggBizxyQ6xXR5mM-1

**Comment by lionelB** [comment]
ce que vous décrivez fait pensais à une demande d'orientation "auto validée" par le CO
