### ISSUE TITLE
Transformer le rayon de mobilité de tranche vers unité kilométrique

### ISSUE THREAD

**Issue by JonathanRaimond** [gip-inclusion/carnet-de-bord#1521]
## :thinking: Contexte et problème observé
Lorsque j'accompagne un bénéficiaire, je peux saisir une tranche de mobilité (moins de 10km, 10 à 20, 20 à 30 ou plus de 30 km). 
Ce rayon de mobilité manque de précision, ce qui rends l'information obsolète lors de son partage a un autre pro. 

Un bénéficiaire non mobile sera identifié comme étant mobile à moins de 10km, de même que celui mobile en transport en commun...
Par ailleurs, un bénéficiaire mobile dans le département sera peut être mobile a 35km contre 500 pour quelqu'un acceptant de déménager partout en France, or tous deux seront identifiés comme mobile a plus de 30km.

Lié à #1439 

### :horse: Proposition de solution
- Transformer les données de mobilité (rattaché au projet pro) en unité kilométrique au lieu d'utiliser une système par tranche.

- Remplacer les boutons radio par un champ de saisie.

- Afin de conserver les données déjà saisies, transformer les tranches en km en conservant la valeur maxi de la tranche. 
  - moins de 10km = 10km
  - 10 à 20km = 20 km
  - 20 à 30 = 30km 
  - plus de 30 = 30km

![Image](https://user-images.githubusercontent.com/85908681/218986959-d3eb2170-f96d-4ba6-ae14-c7aafb840d33.png)

![Image](https://user-images.githubusercontent.com/85908681/218986230-92b0ec4b-3441-4f9d-b3c9-7fa9681fc3c6.png)

**Comment by HEYGUL** [comment]
ok pour moi
