### ISSUE TITLE
En tant que Pro j'ai besoin de consulter les changements de situations d'un bénéficiaire

### ISSUE THREAD

**Issue by JonathanRaimond** [gip-inclusion/carnet-de-bord#1523]
## :thinking: Contexte et problème observé

En tant que professionnel, j'ai besoin de consulter l'évolution de la situation personnelle du bénéficiaire afin d'adapter son accompagnement.

Lié à https://github.com/gip-inclusion/carnet-de-bord/issues/1461

### :horse: Proposition de solution

Historiser la suppression des situations personnelles lors de la mise à jour du diagnostic.

Données à historiser :
- Date de suppression
- Prénom + Nom de l'auteur de la suppression
- Nom de la structure de l'auteur de la suppression

### :ok_hand: Critères d'acceptation

**Etant donnée que** je suis sur le formulaire "Mettre à jour le diagnostic",
**Lorsque** je clique sur une situation pour la désactiver et que je valide les modifications,
**Alors** le système historise la date, mon prénom et nom, ainsi que le nom de ma structure.

**Comment by chdechamps** [comment]
Pour l'historisation, la prendre en compte lors de la validation de la modification et non directement lorsque la case est cochée ou décochée. 
Dans le cadre d'un diagnostic par exemple, un CO peu être amené à cocher une case puis à obtenir des infos supplémentaires sur l'usager qui contredise ce qu'il avait coché (ou qui fait en tout cas état d'une situation différente).

**Comment by HEYGUL** [comment]
Je n'avais pas fait attention en première lecture mais le problème observé est **le besoin de consulter l'évolution** de la situation personnelle alors que la solution n'affiche pas l'évolution.
