### ISSUE TITLE
ETQ CO Je ne dois plus voir le motif de demande de réorientation lorsque j'ai réorienté ou maintenu l'accompagnement du bénéficiaire

### ISSUE THREAD

**Issue by JonathanRaimond** [gip-inclusion/carnet-de-bord#1531]
## :thinking: Contexte et problème observé

Lorsqu'un CO oriente ou maintien l'accompagnement d'un bénéficiaire, le motif de la demande de réorientation est toujours affiché dans la liste des bénéficiaires, ce qui ne permet pas de distinguer les demandes traitées de celles qui ne le sont pas  et oblige le chargé d'orientation à ouvrir le carnet pour vérifier que la demande a bien été traitée.

## :horse: Proposition de solution

Ne plus afficher le motif de demande de réorientation suite à la réorientation ou maintien de l'accompagnement.

## :ok_hand: Critères d'acceptation

- **Etant donné que** je suis sur le carnet d'un bénéficiaire dont le référent a fait une demande de réorientation,
- **Lorsque** je clique sur le bouton "Réorienter" et que je retourne sur la liste des bénéficiaires,
- **Alors** le motif de demande de réorientation n'est plus affiché.

![Image](https://user-images.githubusercontent.com/85908681/219732621-fdbb56a1-4975-4ea5-8b0b-6edb928215b9.png)

**Comment by lionelB** [comment]
il faut rajouter un `where: {decidedAt: {_is_null: true}}` dans la query `getBeneficiariesWithOrientationRequest.gql`
