### ISSUE TITLE
ETQ Pro j'ai besoin de consulter la décision et le motif d'orientation

### ISSUE THREAD

**Issue by JonathanRaimond** [gip-inclusion/carnet-de-bord#1536]
## :thinking: Contexte et problème observé
ETQ Pro (nouveau référent) le diagnostic et l'historique de parcours est parfois insuffisant pour me permettre de comprendre la décision d'orientation/réorientation lorsqu'un bénéficiaire m'est orienté/réorienté.
ETQ Pro (ancien référent) je manque parfois d'informations sur une fin de mandat lorsqu'elle est décidée par le département (soit dans le cadre d'une réorientation, soit d'une sortie de parcours / fin de droit).
ETQ Pro (référent) j'ai parfois besoin d'informations lorsque ma demande de réo est refusée (maintenir l'accompagnement).

## :horse: Proposition de solution
- Permettre au pro (nouveau référent) de consulter le motif d'orientation saisie par le chargé d'orientation ou le manager lorsqu'un bénéficiaire lui a été orienté.
- Permettre au pro (ancien référent) de consulter le motif d'orientation saisie par le chargé d'orientation ou le manager suite à la réorientation du bénéficiaire vers un autre référent.
- Permettre au pro (référent) de consulter le motif d'orientation saisie par le chargé d'orientation ou le manager suite à un maintien d'accompagnement.

## :ok_hand: Critères d'acceptation
**Etant donnée que** je suis sur le carnet du bénéficiaire qui m'a été orienté/réorienté,
**Lorsque** je clique sur le btn "Voir le motif d'orientation/réorientation",
**Alors** Le système affiche une pôp-up contenant le motif d'orientation.

**Etant donnée que** que je suis sur le carnet d'un bénéficiaire réorienté à ma demande,
**Lorsque** je clique sur le btn "Voir le motif de réorientation",
**Alors** Le système affiche une pôp-up contenant le motif d'orientation.

**Etant donnée que** que je suis sur le carnet d'un bénéficiaire pour lequel ma demande de réorientation a été refusée,
**Lorsque** je clique sur le btn "Voir le motif d'orientation",
**Alors** Le système affiche une pôp-up contenant le motif d'orientation.

## :art: Maquette

https://www.figma.com/file/LxSA1VswWm0ugNpHQ2tssG/MAQ---V1.7---PRO?node-id=1800%3A115428&t=PrzVAk6GEyXO6kN3-1

![Capture d’écran 2023-02-22 à 12 35 27](https://user-images.githubusercontent.com/85908681/220608966-76189bad-de75-4d2a-9dd6-4f1322985d48.png)

## :rocket: Pour aller plus loin
Harmoniser les bandeaux d'orientation/réorientation

![Capture d’écran 2023-02-22 à 12 34 27](https://user-images.githubusercontent.com/85908681/220608809-b89eb2ed-bc5e-4708-a3e5-2924e60c2fec.png)

**Comment by HEYGUL** [comment]
@JonathanRaimond le motif est bien un motif différent du motif saisi lors de la demande de réorientation ?
Affiche-t-on le bouton `Voir le motif d'orientation` si aucun motif n'est connu (ce sera le cas de tous les carnets lors de la mise en production) ?

**Comment by HEYGUL** [comment]
Autre question @JonathanRaimond , un changement d'orientation ne passe pas forcément par une demande de réorientation.
Est-ce qu'on affiche le bouton `Voir le motif d'orientation` pour l'ancien référent quel que soit le parcours l'ayant entrainé à être l'ancien référent ?
Est-ce qu'on affiche le bouton seulement pour le dernier "ancien" référent ou toutes personnes ayant été référent à un instant t ?

**Comment by HEYGUL** [comment]
En attendant les réponses à https://github.com/gip-inclusion/carnet-de-bord/issues/1536#issuecomment-1480227812
je suis parti sur un nouveau champ (donc un motif différent de celui de la demande de réorientation) et un affichage permanent du bouton (le motif affiché est `Non défini` si celui-ci n'a pas été saisi).
