### ISSUE TITLE
Création d'un compte pro après suppression d'un compte gestionnaire a partir du meme email

### ISSUE THREAD

**Issue by chdechamps** [gip-inclusion/carnet-de-bord#1548]
### :footprints: Étapes pour reproduire

En tant qu'admin, 'scarava' a été créée en tant que gestionnaire de structure. 
Après échange avec la structure, 'scarava' est devenue pro et a été supprimée de gestionnaire. 
'scarava1' a été importée (elle apparait dans metabase mais pas dans la vue gestionnaire) :

![Image](https://user-images.githubusercontent.com/117724992/221180020-0e9fdbf1-5868-4473-8a50-e24050186146.png)

Lors d'une nouvelle tentative d'import, un message d'erreur indique qu'elle existe déjà : 

![Image](https://user-images.githubusercontent.com/117724992/221179770-4868bf8d-5a57-4583-b4f3-1a600a4611df.png)

Dans métabase, elle apparait avec 10 notebook dans la base, mais les bénéficiaires qui lui sont orientés normalement apparaissent dans le mail des bénéficiaires pour lesquels un référent doit etre désigner. 

## :dart: Comportement attendu

Afficher le profil pro de 'scarava1' dans la structure abeille et lui rattacher les notebooks.

**Comment by HEYGUL** [comment]
Quand je regarde les données dans metabase, le compte `professionnel` a été supprimé, par contre le compte `gestionnaire de structure` est toujours actif.
C'est la raison pour laquelle ce profil n'apparait pas dans la structure abeille.

**Comment by chdechamps** [comment]
Le truc c'est qu'en prod, elle n'est pas parmi les 4 gestionnaires de structures, ni dans les 2 pro de la structures ...

**Comment by chdechamps** [comment]
j'ai supprimé le gestionnaire de structure et l'ai recréer avec le mail de la personne (a l'origine, le département a modifié le compte de S.C. en celui de G.D. sans le supprimer, mais en modifiant le compte et notamment le mail, d'ou le fait que les usernames soient restés). 
Pour autant, quand j'essaye de crééer en pro dans la structure le compte de S.C. dans la structure, ca me met le message d'erreur en screen dans l'issue. 
J'ai besoin que le pro ait un compte pro.

**Comment by HEYGUL** [comment]
le compte pro a été "dé-supprimé"
