### ISSUE TITLE
[SUPPORT 91] : suppression de structures

### ISSUE THREAD

**Issue by chdechamps** [gip-inclusion/carnet-de-bord#1550]
## Liste des structures à supprimer dans le déploiement 91

- [ ] VITA-LIS Palaiseau
- [ ] AAPISE
- [ ] AAPISE Inter'Val
- [ ] AAPISE Le Phare
- [ ] AAPISE Alliance
- [ ] Mission Locale Vita-lis
- [ ] Colombbus
- [ ] ME Vigneux
- [ ] JARDIN DE COCAGNE SIAE
- [ ] GERMINAL SIAE
- [ ] Mission Locale du Sud Essonne
- [ ] ME Yerres
- [ ] ACTION EMPLOI
- [ ] RE-SACLAY EI
- [ ] VITA-LIS les Ulis
- [ ] MISSION LOCALE DU VAL D ORGE
- [ ] REPERES
- [ ] Point Information Jeunesse Montgeron

**Comment by HEYGUL** [comment]
On veut une suppression complète (en faisant comme si ces structures n'avaient jamais existé) ou un soft delete ?

**Comment by lionelB** [comment]
suppression des structures et professionnels et admin de structures et account (et structure_orientation_system)
