### ISSUE TITLE
[SUPPORT 86] : suppression de deux CO

### ISSUE THREAD

**Issue by chdechamps** [gip-inclusion/carnet-de-bord#1555]
## Account ID à supprimer : 

- [ ] 406f2564-1c13-46d2-9314-1892a9feb5ad
- [ ] d30f1f4d-dea1-461d-98b3-bdf433d485ed

**Comment by HEYGUL** [comment]
Traité via un soft delete (en cas de soucis, on peut revenir en arrière :-) )
