### ISSUE TITLE
Création d'un "wantedjob" 'Projet professionnel non défini'

### ISSUE THREAD

**Issue by chdechamps** [gip-inclusion/carnet-de-bord#1558]
## :thinking: Contexte et problème observé
Certains accompagnement concernent des publics en grande difficultés sociales et pour lesquelles le retour (immédiat) vers l'emploi n'est, à date, pas un sujet. 
D'autres usagers, notamment en accompagnement suite à une inaptitude au poste, ceux n'ayant pas de formation ni d'expérience, ... peuvent ne pas avoir de projet pro défini. Pour autant, ils peuvent avoir besoin d'explorer différentes pistes et donc réaliser des objectifs de recherches d'emploi ("identifier ses points forts et compétences" par exemple). 

### :horse: Proposition de solution
Ajouter la possibilité de définir un projet pro : "Projet professionnel non défini" lorsqu'aucun projet pro n'existe (afin de pouvoir quand même y rattacher des objectifs et actions). 

Cela implique : 
- Créer le projet pro "Projet professionnel non défini" pour tous les carnets sans wantedjob.
- Permettre a un pro de supprimer l'ensemble des wantedjob (lorsque le dernier wantedjob est supprimé, ajout par défaut de "Projet professionnel non défini" (qui lui ne peut etre que modifié). 
- Lorsqu'un carnet n'a pas de projet pro (et donc un projet pro et un axe "projet professionnel non défini"), et que le pro veux ajouter un projet pro, il doit modifier le "projet professionnel non défini" en un métier recherché (wantedjob). Il peu ensuite ajouter "n" autres projets pro dans la limite de 5 maximum.

**Comment by lionelB** [comment]
Fait dans #1575. Si le métier recherché est indéfini on affiche "Projet en construction" 
Ne sont pas actuellement traité
- la règle d'ajout automatique du projet pro quand on supprime tout les projets. L'utilisateur à la possibilité de rajouter un projet pro en construction, si cela est necessaire on pourra ouvrir une nouvelle issue
- l'ajout de projet pro indéfini pour tout les carnets sans projet pro n'est pas fait (cela pose la question de savoir qui à "créer" le projet pro)
