### ISSUE TITLE
BUG: Lorsque je supprime un axe de travail, la situation lié a la thématique disparait du diagnostic

### ISSUE THREAD

**Issue by chdechamps** [gip-inclusion/carnet-de-bord#1559]
### :footprints: Étapes pour reproduire

1. Je suis référent d'un bénéficiaire qui m'indique avoir des soucis de logement, j'actualise sa situation en indiquant qu'il est hébergé chez un tiers et doit quitter le logement. L'axe de travail logement se créer automatiquement (ça c'est top)
2. Je vais ajouter un objectif dans l'axe de travail, a savoir accéder a un logement, et une action dans l'objectif qui est la demande de logement social. 
3. Une fois réalisé, j'accède au carnet, modifie le statut de l'action et de l'objectif en réalisé
4. Je met a jour le diag (il est désormais locataire du parc social).
5. Je n'ai plus d'action a réalisé sur le logement et supprime donc l'axe de travail Logement. 

https://user-images.githubusercontent.com/117724992/221421345-07d96fe9-e211-4f2b-ac5c-3221e45fb5e2.mp4

### :crying_cat_face:  Comportement observé

Lorsque je supprime l'axe de travail Logement, les informations sur la situation personnelle relative au logement disparaissent du diagnostic, je perds donc des infos sur le fait que ce bénéficiaire est locataire du parc privé. 

### :dart: Comportement attendu

La suppression d'un axe de travail ne doit pas entrainer la suppression des infos relatives a la thématique.

**Comment by lionelB** [comment]
c'est un comportement normal de l'application car les situations sont des propriétés des axes de travail
L'ui porte à confusion et la prochaine [PR 1554](https://github.com/gip-inclusion/carnet-de-bord/pull/1554) devrait
 corriger ce problème
