### ISSUE TITLE
Refonte du header à la sauce GIP

### ISSUE THREAD

**Issue by JonathanRaimond** [gip-inclusion/carnet-de-bord#1596]
## :thinking: Contexte et problème observé

Dans le cadre de l'harmonisation des outils numériques portés par le GIP, le header et le footer doivent faire l'objet d'une refonte. 
De plus les utilisateurs n’ont pas accès au Helpdesk et à l'infolettre du GIP depuis l’interface. 

## :horse: Proposition de solution

Harmoniser le header avec ceux des autres startups (boutons, espacements,…)
* Charter le header avec la nouvelle identité graphique de CDB (logos, textes, couleurs,…)
* Ajout d’un bouton `Infolettre` pour accéder/s’inscrire à l’infolettre du GIP.
* Ajout d’un bouton `Besoin d’aide ?` permettant la redirection vers le centre d'aide de Carnet de bord sur la Communauté
* Conserver `Mon compte` et `Déconnexion` (suite au refinement)

## Non retenu suite au refinement : 
* Remplacer les boutons "Mon compte" et "Déconnexion" par un bouton "Mon espace" avec menu déroulant donnant accès aux boutons "Mon compte" et "Déconnexion"

## :link: Liens
`Besoin d'aide ?`:
https://communaute.inclusion.beta.gouv.fr/forum/carnet-de-bord-77/

`Infolettre` :
https://981c5932.sibforms.com/serve/MUIEAJHvob2zXVxoW2gIQspSQwuw7sIUK8W0Cygv0WJd68eW-Toq9LQkBI8Xffv_I5a-1iLZMGwhxjdD7SPCjWT8YMWC6WoK11MNDycQJ8Uoi4Grdf_3oqrUlc7UvhLy8qhs_OC_ezebGm-2kshIP0kbaaxHmkh7MyZQsm-bRyyEN8Zxn4yhJitOdCJoJL-y4SQxe5Uxen9w0Ksy

## :building_construction: A faire côté Design
- [ ] Lier les fichiers Figma à une librairie partagée avec le Gip
- [ ] Voir avec le GIP pour préciser le formulaire de l'infolettre 

## :art: Maquette

https://www.figma.com/file/LxSA1VswWm0ugNpHQ2tssG/MAQ---V1.7---PRO?node-id=2479%3A114301&t=g5yP7HGl56qXu4DF-1

![Capture d’écran 2023-03-30 à 17 45 01](https://user-images.githubusercontent.com/85908681/228896036-cd500f7f-82ea-4ccd-806c-6a52a2cda081.png)

## Impact envisagé
Augmentation de la consultation du centre d'aide > donc meilleur connaissance de l'outil > amélioration du NPS (prévoir de tracer les clics vers le centre d'aide).

**Comment by lionelB** [comment]
c'est étrange de mettre en action principale le` Mon compte` plutôt que `Déconnexion`

**Comment by JonathanRaimond** [comment]
C'est vrai que mon compte n'est pas l'action principale car le btn Déconnexion est surement plus utilisé que mon compte. Cependant je ne suis pas convaincu qu'il faille mettre en avant le btn de déconnexion.
Pour l'instant c'est pas encore figé, j'ai posé une première pierre avec cette issue, mais nous avons besoin de faire un point avec Antoine Poindron avant de la faire passer en dev.

**Comment by lionelB** [comment]
merci pour ta réponse

**Comment by chdechamps** [comment]
Moi je suis plutôt OK avec déconnexion tout en bas. Il me semble que c'est le cas partout en fait. Un peu la norme

Communauté de l'inclusion : 
![Image](https://user-images.githubusercontent.com/117724992/233608331-10023b3b-60a2-418a-92ec-dd2c272dc749.png)

GitHub : 
![Image](https://user-images.githubusercontent.com/117724992/233608478-4c8364c0-cd05-4b42-be8c-dba9689e6213.png)

Gmail : 
![Image](https://user-images.githubusercontent.com/117724992/233608811-df6f5216-3950-41aa-82a1-93d0072afda4.png)

**Comment by chdechamps** [comment]
En attente d'un patch GIP DSFR. 
Ok pour le changement logo + 4 lien en une ligne.

**Comment by JonathanRaimond** [comment]
Suite au refinement, la maquette à été modifiée. Le bouton « mon espace » a été remplacé par deux boutons « mon compte » et « Déconnexion ». Je sais que le footer n'est pas prévu pour tout de suite mais est-il possible de JUSTE^^ remplacer le logo « Ministère du travail, du plein emploi, et de l’insertion » par le logo « République Française » afin d’harmoniser avec le header svp ?

![Image](https://github.com/gip-inclusion/carnet-de-bord/assets/85908681/aa43699d-93e5-4865-8478-82147d589722)


![Image](https://github.com/gip-inclusion/carnet-de-bord/assets/85908681/b5ff9352-23d3-483f-bad9-4e98f41cb500)
