### ISSUE TITLE
Bug / Support [08 / 81] : Orientation extradépartementale

### ISSUE THREAD

**Issue by chdechamps** [gip-inclusion/carnet-de-bord#1599]
### Support / bug / situation étrange. 

Le CD81 a importé des bénéficiaires via csv avec désignation de la structure dans le fichier d'import. 
Parmi eux, 10 bénéficiaires était orientés vers la structure "CMA", or CMA est une structure du 08 (il y avais eu un bug sur ce sujet, mais je ne retrouve plus le ticket (mais les messages mattermost), en tout cas, les structures du 81 ont depuis été renommées avec l'ajout du N° de département après en CMA81). 
Le support est contacté ce jour par la CMA 08 qui identifie des bénéficiaires du TARN dans carnet de bord et souhaite les réorienter vers le TARN.

### Comportement attendu : 
Vérification que les bénéficiaires du 81 soient bien dans le 81
suppression du lien de ces bénéficiaires avec le 08 et la structure CMA (du 08).

### Discussion mattermost liée : 
- https://mattermost.incubateur.net/betagouv/pl/1rb7muu9wjfg3xqztwg47tejxo + sujets du 3 février sur le canal ticket.

**Comment by HEYGUL** [comment]
[En groupant les bénéficiaires de la structure CCI (du cd08) par déploiement](https://metabase.carnetdebord.inclusion.beta.gouv.fr/question#eyJuYW1lIjpudWxsLCJkYXRhc2V0X3F1ZXJ5Ijp7InF1ZXJ5Ijp7InNvdXJjZS10YWJsZSI6MTEsImZpbHRlciI6WyJhbmQiLFsiPSIsWyJmaWVsZCIsMzIyLG51bGxdLCIxOTY5ZjdhYi1kZjkxLTRjMTQtYjY4Ni1lYWExNTdlMTJiM2MiXV19LCJ0eXBlIjoicXVlcnkiLCJkYXRhYmFzZSI6M30sImRpc3BsYXkiOiJ0YWJsZSIsInZpc3VhbGl6YXRpb25fc2V0dGluZ3MiOnt9fQ==) je ne trouve aucun bénéficiaire d'un autre déploiement que cd08.

Le bug permettant cette incohérence à l'import a été corrigé récemment.

**Comment by HEYGUL** [comment]
Fermée en faveur de #1711 et #1712
