### ISSUE TITLE
[Support] : déplacement de deux pro de CD81 vers CCI81

### ISSUE THREAD

**Issue by chdechamps** [gip-inclusion/carnet-de-bord#1600]
Professionnel à déplacer de la structure "CD81 - Cohorte MD" vers la structure "CCI 81"

- 40b94107-a5c0-4f84-b449-cf39f1b64c6a 
- fb196f54-bf0b-4341-a626-940ed4f6bd25

**Comment by HEYGUL** [comment]
Déplacement ok : https://metabase.carnetdebord.inclusion.beta.gouv.fr/question#eyJkYXRhc2V0X3F1ZXJ5Ijp7InR5cGUiOiJxdWVyeSIsInF1ZXJ5Ijp7InNvdXJjZS10YWJsZSI6MzMsImZpbHRlciI6WyJhbmQiLFsiPSIsWyJmaWVsZCIsMjU5LG51bGxdLCJmYjE5NmY1NC1iZjBiLTQzNDEtYTYyNi05NDBlZDRmNmJkMjUiLCI0MGI5NDEwNy1hNWMwLTRmODQtYjQ0OS1jZjM5ZjFiNjRjNmEiXV19LCJkYXRhYmFzZSI6M30sImRpc3BsYXkiOiJ0YWJsZSIsInZpc3VhbGl6YXRpb25fc2V0dGluZ3MiOnt9LCJvcmlnaW5hbF9jYXJkX2lkIjpudWxsfQ==
