### ISSUE TITLE
ETQ pro/CO, je veux récupérer les infos des situations de France Travail (PE).

### ISSUE THREAD

**Issue by chdechamps** [gip-inclusion/carnet-de-bord#1643]
## :thinking: Contexte et problème observé

En tant que professionnel / CO, je veux pouvoir récupérer les informations du diagnostic existants chez pôle emploi afin de pouvoir capitaliser dessus et accélérer ma prise en charge et ne pas avoir à les ressaisir dans carnet de bord. 

### :horse: Proposition de solution

Utilisation des API de Pole Emploi (via pe.io) :

- Utiliser l'API de recherche usager pour obtenir l'identifiant PE du bénéficiaire.
- Utiliser l'API contraintes pour récupérer les situations et objectifs.

Ce ticket ne traite que la lecture des situations et objectifs du diagnostic.
D'autres tickets suivront pour traiter l'écriture et la lecture des autres informations (métiers recherchés, etc).

Flow des évènements 

![Image](https://github.com/gip-inclusion/carnet-de-bord/assets/160320/e4b44d71-b25c-477a-be72-8829a416f2ec)

**Comment by HEYGUL** [comment]
en attente de compléments (jeux de données) de PE
