### ISSUE TITLE
ETQ pro/co, je veux que les éléments du diagnostic pole emploi soient récupérés dans carnet de bord

### ISSUE THREAD

**Issue by chdechamps** [gip-inclusion/carnet-de-bord#1644]

**Comment by lionelB** [comment]
premiere etape dans #1884

**Comment by vjousse** [comment]
Actuellement du code pour récupérer les contraintes / objectif / situations a été commité dans #1884 et placé sous le feature flag `ENABLE_SYNC_CONTRAINTES`. Bien qu'on production, ce code n'écrit rien dans la base pour l'instant.

Cette PR étant trop large à la base, je propose de la fermer comme complétée par la #1884 .

La PR qui suivra sera celle qui permettra de faire un `dry-run` sur la #1884 pour « se rendre compte » de ce que lancer la synchro en live donnerait.
