### ISSUE TITLE
[Support 08] : Modification email pro

### ISSUE THREAD

**Issue by chdechamps** [gip-inclusion/carnet-de-bord#1664]
Il y a une erreur dans l'adresse email de Clotilde GIORGINI (pro) à la MDS de ROCROI, dans son prénom il n’y a pas de « h », donc pas non plus dans son adresse mail.

Elle ne peut pas se connecter à CDB.

Modifier son email en supprimant le H.

**Comment by lionelB** [comment]
fait !
