### ISSUE TITLE
[Support 71] : Suppression d'un gestionnaire de structure et d'une structure

### ISSUE THREAD

**Issue by chdechamps** [gip-inclusion/carnet-de-bord#1672]
Appel recu ce jour du CD71. Ils ont fait des tests en prod et souhaite la suppression : 
- de la structure SIAE Test : 75decad0-024f-4f44-887a-8a2d91ba95bb
- du gestionnaire de structure account ID : 56484af6-882d-4fd6-bf30-1a70effcc692

**Comment by lionelB** [comment]
quid des modifs apportées sur des carnets par des pros de ces structures ?

**Comment by chdechamps** [comment]
La structure n'a pas de pro et c'est le compte du gestionnaire de structure et non du pro qui est a supprimer, donc pas de modif sur un carnet.

**Comment by lionelB** [comment]
c'est fait
