### ISSUE TITLE
ETQ référent j’ai besoin de connaître le motif de maintien d’accompagnement

### ISSUE THREAD

**Issue by chdechamps** [gip-inclusion/carnet-de-bord#1681]
## :thinking: Contexte et problème observé

En tant que référent de parcours j’ai besoin de connaître les raisons pour lesquelles je dois poursuivre le suivi du bénéficiaire afin d’adapter mon accompagnement

### :horse: Proposition de solution

Permettre au pro de consulter le motif du maintien dans l’accompagnement, saisie par le chargé d'orientation

### :ok_hand: Critères d'acceptation

**Etant donnée que** je suis sur le carnet d’un bénéficiaire dont la demande de réorientation a été refusée,
**Lorsque** je clique sur le bouton « Voir le motif de maintien d'accompagnement »,
**Alors** le système affiche le motif de maintien d’accompagnement.

### :art: Maquette

https://www.figma.com/file/LxSA1VswWm0ugNpHQ2tssG/MAQ---V1.7---PRO?node-id=1800%3A115428&t=d35fHsciye5RKQW1-1

![Image](https://user-images.githubusercontent.com/85908681/231988237-ceed1a60-0b1e-477d-879b-3f07262ce8d9.png)

![Image](https://user-images.githubusercontent.com/85908681/231993141-dc20f3a7-13f4-4512-bb20-d266e96472fd.png)

**Comment by lionelB** [comment]
fait en #1819
