### ISSUE TITLE
BUG : ETQ manager, quand j'importe un fichier XML, il est indiqué que je recevrai un mail après le traitement. Je ne recois pas ce mail

### ISSUE THREAD

**Issue by chdechamps** [gip-inclusion/carnet-de-bord#1703]
### :footprints: Étapes pour reproduire

1. Je clique sur Importer un fichier CAF/MSA
2. Je télécharge le fichier, un message apparait m'informer que le traitement est en cours et que je serai notifié par mail.

### :crying_cat_face:  Comportement observé

Il n'y a pas de mail reçu

### :dart: Comportement attendu

Mise en place de l'envoi du mail ou modification du message pour ne pas indiquer l'envoi d'un mail.

**Comment by HEYGUL** [comment]
Je viens de faire le test sur l'environnement de démo et on reçoit bien le courriel.
**Est-ce possible d'avoir plus de détails sur le contexte (type de fichier, déploiement, etc...) ?**

J'ai regardé la configuration en production et je ne vois rien qui empêcherait cet envoi de courriel.
De plus, des logs devraient être écrits lors d'un traitement de fichier CAF/MSA, mais je n'en ai pas trouvé en production.
**As-tu la date à laquelle le bug a été observé ?**

**Comment by HEYGUL** [comment]
@chdechamps le fix est déployé en production, peux-tu faire un nouvel essai avec l'utilisatrice qui rencontrait le problème ?
