### ISSUE TITLE
[Support] Corriger les bénéficiaires attachés à des structures hors du déploiement auquel ils appartiennent.

### ISSUE THREAD

**Issue by HEYGUL** [gip-inclusion/carnet-de-bord#1711]
### :footprints: Étapes pour reproduire

Suite à un bogue qui a été corrigé depuis, il a été possible de rattacher des bénéficiaires à des structures de déploiement auxquels ils n'appartiennent pas.

On le remarque notamment avec [cette question metabase](https://metabase.carnetdebord.inclusion.beta.gouv.fr/question/354-beneficiaires-attaches-a-une-structure-dun-autre-deploiement) qui liste ces bénéficiaires.

Afin de corriger ces données, il faut savoir vers quelle structure rattacher chaque bénéficiaire.
On peut aussi imaginer ajouter une contrainte technique (en base de données par exemple) qui empêcherait ce problème de survenir de nouveau.

### :crying_cat_face:  Comportement observé

La requête metabase retourne des résultats.

### :dart: Comportement attendu

La requête metabase ne retourne plus aucun résultat.

**Comment by chdechamps** [comment]
Intervention dev nécessaire pour : 

- bénéficiary ID ; ecb0a1d6-8d24-45a2-a0cd-bca9a98d96b0 => Supprimer le lien avec la structure ID : 0c017ddf-39d0-4756-bfbd-195eae802103 (n'apparait nulle part en front)
- bénéficary ID : 31e146a4-234e-43cf-878a-8e3563d9a543 => supprimer le lien avec la structure ID : 0c017ddf-39d0-4756-bfbd-195eae802103 (n'apparait nulle part en front)

Pour les deux autres bénéficiaires apparaissant dans la requête, ils font l'objet d'une future suppression (ticket #1721)
