### ISSUE TITLE
[Support] Corriger les bénéficiaires attachés à plusieurs structures au même moment.

### ISSUE THREAD

**Issue by HEYGUL** [gip-inclusion/carnet-de-bord#1712]
### :footprints: Étapes pour reproduire

En souhaitant corriger un autre bogue, on constate en regardant les données de production qu'il y a des bénéficiaires attachés à plusieurs structures au même moment ce qui ne devrait "jamais" arrivé.
Pour suivre ces cas, une [question metabase a été créée](https://metabase.carnetdebord.inclusion.beta.gouv.fr/question/355-beneficiaires-presents-dans-plusieurs-structures-au-meme-moment).

Il faut rattacher les bénéficiaires à la structure de leur référent et supprimer tout attachement à une autre structure.
Si ce n'est pas possible, alors il faudra demander aux utilisatrices / utilisateurs quelles sont les rattachement à conserver.

### :crying_cat_face:  Comportement observé

La requête metabase retourne des résultats.

### :dart: Comportement attendu

La requête metabase ne retourne pas de résultats.

**Comment by chdechamps** [comment]
2524cfa7-c036-4442-90cb-ba3665d8fd0b => Clore RDD (structure désactivée)
5f0013d7-0cdf-44db-b337-7896e28063e8 => Clore RDD (structure désactivée)
7f0c6b5b-e11f-4af7-bba6-024acec1494d => Clore RSA veille emploi
