### ISSUE TITLE
[support] Suppression de déploiements test

### ISSUE THREAD

**Issue by oblab** [gip-inclusion/carnet-de-bord#1721]
Merci de supprimer les déploiements suivants et les données qu'ils contiennent : 
671d466c-5cd1-40a2-bc04-edce77ae46c6  (Déploiement test LK)
107d1622-387e-41d7-a69d-7580e1e73dd7 (Déploiement test)

**Comment by HEYGUL** [comment]
Fait pour `Déploiement test LK`
En voulant supprimer le `Déploiement test`, j'ai vu qu'il y a une structure dans ce déploiement avec 41 professionnels.
On est sûr de vouloir tous les supprimer ?
[cf Metabase](https://metabase.carnetdebord.inclusion.beta.gouv.fr/question?objectId=8815b211-63e5-4ca9-8d65-9b0d4f44e2b3#eyJuYW1lIjpudWxsLCJkYXRhc2V0X3F1ZXJ5Ijp7ImRhdGFiYXNlIjozLCJ0eXBlIjoicXVlcnkiLCJxdWVyeSI6eyJzb3VyY2UtdGFibGUiOjMxLCJmaWx0ZXIiOlsiYW5kIixbIj0iLFsiZmllbGQiLDIzOSxudWxsXSwiMTA3ZDE2MjItMzg3ZS00MWQ3LWE2OWQtNzU4MGUxZTczZGQ3Il1dfX0sImRpc3BsYXkiOiJ0YWJsZSIsInZpc3VhbGl6YXRpb25fc2V0dGluZ3MiOnt9fQ==)

**Comment by oblab** [comment]
Merci Gul, je vérifie et te dis

**Comment by oblab** [comment]
Vu avec Charles, tu peux supprimer le `Déploiement test `malgré les 40 pro

**Comment by HEYGUL** [comment]
c'est fait
