### ISSUE TITLE
[Support] Suppression d'un compte gestionnaire de structure et création de 2 comptes manager de territoire

### ISSUE THREAD

**Issue by oblab** [gip-inclusion/carnet-de-bord#1722]
Isabelle R. (id=a16d786f-2903-4de2-a834-b1c2803fbad7) : 

- suppression de son compte gestionnaire de structure (email à réutiliser pour la création des comptes ci-dessous)
- création de comptes de manager sur le déploiement Tarn + déploiement Aveyron avec le meme email et définition d'un username différent pour permettre la connexion à l'un ou l'autre (prenom.nom81 pour le Tarn + prenom.nom12 pour l'Aveyron).

**Comment by lionelB** [comment]
Proposition: modifier la contrainte d'unicité sur le mail pour permettre à un admin d'intervenir sur plusieur territoire car le cas va exister aussi pour d'autre déploiement
