### ISSUE TITLE
Eviter d'exposer le jwt token au client

### ISSUE THREAD

**Issue by chdechamps** [gip-inclusion/carnet-de-bord#1726]
Actuellement l'authentification de l'utilisateur repose sur un token jwt stocké dans un cookies serveur. Afin de pouvoir faire des requêtes vers hasura ou l'api python, on expose ce token au client. On souhaite éviter cela afin de limiter les requêtes cross-origin. Pour fait passer toutes les requêtes par un endpoint sveltekit afin de pouvoir accéder au cookie sans avoir à l'exposer au client.

Dans un second temps, on pourra chiffrer ce jeton dans le cookie, et éventuellement le conserver dans un stockage de session côté serveur (ex. Redis) pour améliorer encore la sécurité.

**Comment by lionelB** [comment]
closed by #1698
