### ISSUE TITLE
Permettre de créer des bénéficiaires depuis RDV-I

### ISSUE THREAD

**Issue by chdechamps** [gip-inclusion/carnet-de-bord#1729]
Prerecquis : évolution sécu a merger

En tant qu'utilisateur de RDV-I, je souhaite pouvoir créer un nouveau carnet via une API, afin de pouvoir réaliser le diagnostic du bénéficiaire et l'accompagner suite à son rendez-vous d'orientation.

**Comment by lionelB** [comment]
https://www.notion.so/gip-inclusion/Journal-de-bord-247191700d384a9191e8111b8f0f2883?p=ad67490dc81943b0af509fc8b4bfaf48&pm=s
