### ISSUE TITLE
[Support 81] : création d'un pro après désactivation du profil gestionnaire

### ISSUE THREAD

**Issue by chdechamps** [gip-inclusion/carnet-de-bord#1756]
Changement de statut d'un utilisateur de gestionnaire à professionnel : https://mattermost.incubateur.net/betagouv/pl/77ocobun6pymfj3xkijsgnsjge

Un autre gestionnaire l'a supprimer de gestionnaire mais n'arrive pas a l'importer en pro.

**Comment by HEYGUL** [comment]
Le compte pro existe mais est supprimé (deleted_at = 22 mai 2023 / 10:31).
Le compte gestionnaire de structure est actif.

Cela ne correspond pas à l'explication du ticket, avant d'aller plus loin je préfère avoir une confirmation.

**Comment by HEYGUL** [comment]
J'ai eu confirmation via crisp.
J'ai donc désactivé le compte gestionnaire de structure et activé le compte professionel.
