### ISSUE TITLE
Emplacement du bandeau de cookies + couleur bouton + message

### ISSUE THREAD

**Issue by chdechamps** [gip-inclusion/carnet-de-bord#1788]
### :footprints: Étapes pour reproduire

Se connecter pour la 1ère fois depuis 15 jours (NPS) + sans avoir déjà valider ou refuser les cookies :
![image](https://github.com/gip-inclusion/carnet-de-bord/assets/117724992/61af2254-583c-4c6f-a1a4-95772d85f874)

### :crying_cat_face:  Comportement observé

- Le bandeau cookies s'affiche sur le bandeau NPS
- La couleur des boutons n'est pas vert carnet
- le message du bandeau ne permet pas de savoir que le refus de cookies empêche le système de chat

### :dart: Comportement attendu

- déplacer le bandeau cookies sur le coté droit (à l'emplacement du chat)
- mettre les bonnes couleurs pour les boutons. 
- Modifier le message affiché de `Ce site utilise des cookies et vous donne le contrôle sur ceux que vous souhaitez activer` en `Ce site utilise des cookies pour offrir une expérience optimale de support et vous donne le contrôle si vous souhaitez l'activer` (ou autre proposition).

**Comment by jujumoreau** [comment]
Voici le message que nous avons choisi de mettre dans le quoi de neuf : 

"Nous attachons une grande importance à obtenir votre consentement concernant le dépôt de cookies, c'est pourquoi nous avons mis en place un gestionnaire de cookies. 

ℹ️ Veuillez noter que si vous choisissez de désactiver les cookies, nous ne serons pas en mesure de vous donner accès au service de support (tchat)."

**Comment by lionelB** [comment]
closed by #1809
