### ISSUE TITLE
[Support 80] supprimer tous les bénéficiaires du déploiement de la somme

### ISSUE THREAD

**Issue by chdechamps** [gip-inclusion/carnet-de-bord#1789]
Le département de la somme veux réinitialiser la base bénéficiaire pour partir sur les bons chiffres en début d'expérimentation FT. 
Supprimer complètement tous les bénéficiaires pour permettre au département de réimporter les bons (sans ceux sorti) et les nouveaux.

**Comment by HEYGUL** [comment]
Fait.
