### ISSUE TITLE
[Support 86] : suppression de 4 comptes de CO

### ISSUE THREAD

**Issue by chdechamps** [gip-inclusion/carnet-de-bord#1791]
Demande du département de supprimer 4 comptes (suppression totale) : 
- b2b85bee-8424-4a2f-a4d6-18cada2e5e07
- 4bda7b97-5c36-48fd-9983-b40498f00df8
- a1a7ba81-7bb3-4216-b737-01927f6851c3
- 7f56fd79-5e2e-48d9-9f32-32b603a9d8a1

**Comment by HEYGUL** [comment]
Fait.
