### ISSUE TITLE
[Support 80] : création des dispositifs de déploiement

### ISSUE THREAD

**Issue by chdechamps** [gip-inclusion/carnet-de-bord#1793]
Demande du département pour la création des dispositifs suivants sur le déploiement (actuellement sans dispositif) : 
- Accompagnement social
- Accompagnement professionnel
- Accompagnement global PE/CD
- Coach Emploi PE

**Comment by HEYGUL** [comment]
J'ai créé les dispositifs suivants : 
- Accompagnement social (Social)
- Accompagnement professionnel (Professionnel)
- Accompagnement global PE/CD (Socio-professionnel)
- Coach Emploi PE (Professionnel)
