### ISSUE TITLE
[Bug] code ROME lors de l'import de bénéficiaires non sauvegardé

### ISSUE THREAD

**Issue by oblab** [gip-inclusion/carnet-de-bord#1796]
### :footprints: Étapes pour reproduire
Sur l'environnement de démo : 
- Je me connecte en tant qu'administrateur de territoire (manager)
- Je cliquer sur "Importer des bénéficiaires", puis sur "Importer de nouveaux bénéficiaires" ou "Importer des bénéficiaires existants"
- L'import se déroule correctement, sans message d'erreur, le code ROME apparaît bien dans la prévisualisation de l'import
![Image collée à 2023-6-5 10-02](https://github.com/gip-inclusion/carnet-de-bord/assets/251367/8f5fae82-cc56-436f-9d9f-115afe014cf9)

### :crying_cat_face:  Comportement observé
Sur la page du carnet en question, le projet professionnel n'est pas sauvegardé (ou mis à jour dans le cas d'un bénéficiaire existant)
![Image collée à 2023-6-5 10-03](https://github.com/gip-inclusion/carnet-de-bord/assets/251367/5b25d4af-a445-4f4c-97ed-dfa6f41e1827)

### :dart: Comportement attendu
Le projet professionnel devrait apparaître sur la page du Carnet

Question subsidiaire : le système permet-il d'importer plusieurs code ROME pour un seul bénéficiaire ? 

### :recycle: Environnement

Environnement de démo (pas testé en prod par crainte de suppression d'informations)

**Comment by lionelB** [comment]
Hello, le projet pro n'est pas créer car le code rome fourni correspond à une catégorie et qu'on a pas rentré les catégorie.
Il faudrait probablement les ajouter à notre base

**Comment by lionelB** [comment]
ce n'est pas possible coté pe. il faudrait voir comment filtrée / notifié les erreur en amont de l'import
