### ISSUE TITLE
[Bug] Mail automatique de création de compte aux gestionnaires de structures

### ISSUE THREAD

**Issue by oblab** [gip-inclusion/carnet-de-bord#1803]
### :footprints: Étapes pour reproduire

- ETQ Manager de territoire, j'importe un fichier de structures [import_structures.csv](https://github.com/gip-inclusion/carnet-de-bord/files/11664575/import_structures.csv)
- Je coche "Envoyer un email de creation de compte aux nouveaux gestionnaires de structure"
- je cliques sur "confirmer"

![image](https://github.com/gip-inclusion/carnet-de-bord/assets/251367/4af10805-e0ab-40e9-b2bb-d0801507f699)

> Test réalisé avec deux adresses mail différentes `olivierbourreau1@gmail.com` et avec `olivier.bourreau+structuretest@beta.gouv.fr`

### :crying_cat_face:  Comportement observé

Aucun mail n'est délivré (pas dans les indésirables non plus)

### :dart: Comportement attendu

Un mail d'avertissement devrait être envoyé au(x) gestionnaire(s) de structure(s) renseignés dans le fichier
### :recycle: Environnement

Environnement (dev, prod...) : dev

**Comment by HEYGUL** [comment]
Est-ce que le bug est également présent en production ?

Je viens de vérifier et le courriel est bien envoyé.
Attention sur l'environnement de démo, les mails ne sont pas envoyés vers le destinataires, mais on utilise mailtrap.
En vérifiant dans mailtrap, le courriel est bien reçu.
Les identifiants de connexion de mailtrap sont dans bitwarden.

**Comment by oblab** [comment]
le bug ne concerne que l’environnement de dev
