### ISSUE TITLE
Parenthèse dans le nom de famille

### ISSUE THREAD

**Issue by chdechamps** [gip-inclusion/carnet-de-bord#1833]
### :footprints: Étapes pour reproduire

1. J'accède en tant que pro a un carnet dont le nom contient des parenthèses (possible via import csv).
2. Je veux modifier une autre info perso du carnet
3. je ne peux pas sauvegarder les infos modifiées par rapport aux parenthèses :
![image](https://github.com/gip-inclusion/carnet-de-bord/assets/117724992/820b4534-6788-4952-95dd-cd1c59c37651)

### :dart: Comportement attendu

Bloquer l'import des bénéficiaires lorsque le nom comporte des parenthèses.

**Comment by lionelB** [comment]
est ce qu'on devrait pas bloquer les paranthèse à l'import plutôt ?

**Comment by chdechamps** [comment]
C'est en ready for refinement ... On s'en reparle

**Comment by chdechamps** [comment]
C'est ok pour interdire les parenthèses lors de l'import

**Comment by HadrienMP** [comment]
Comme vu ensemble, pour les données existantes, on fait une migration
- Suppression des parenthèses
- Ajout d'espaces autour des parenthèses s'il n'y en a pas (Sauf début et fin de champ)

**Comment by jonathanperret** [comment]
> * Suppression des parenthèses
> * Ajout d'espaces autour des parenthèses s'il n'y en a pas (Sauf début et fin de champ)

@HadrienMP je ne comprends pas, on supprime les parenthèses ou bien on ajoute des espaces autour ? 🤔
