### ISSUE TITLE
Je souhaite pouvoir consulter le dossier d'une personne à pole emploi

### ISSUE THREAD

**Issue by lionelB** [gip-inclusion/carnet-de-bord#1851]
## :thinking: Contexte et problème observé
Les données de diagnostique sont partagés dans différents SI selon qu'un bénéficiaire est accompagné pour le département, pole emploi ou la mission locale. Un utilisateur de carnet de bord et souvent obligé de se connecté à plusieurs systeme pour avoir accès au donnée de diagnostic du bénéficiaire. 

## :horse: Proposition de solution

Grace à l'api mise à disposition de pole emploi, on affiche les données du diagnostic saisie chez pole emploi dans une page dédiée, accessible via un lien depuis le carnet d'un bénéficiaire

## Impact métier
On pense que le partage d'information est important pour les accompagnants, on va donc s'assurer que la fonctionnalité soit utilisées en traçant son utilisation

TODO

- [x] appeler le endpoint `/individus`
- [x] stocker le résultat dans la table `external_data`
- [x] ne plus mettre à jour les situations carnet de bord
- [x]  créer une action pour récupérer le json de externalData typé 
- [x] créer une page qui affiche les external_data `peio`  (https://www.figma.com/file/LxSA1VswWm0ugNpHQ2tssG/MAQ---V1.7---PRO?type=design&node-id=3801%3A200714&mode=design&t=ORZbK0mijyJjR6Ph-1)

**Comment by JonathanRaimond** [comment]
Les icônes ont été mises à jour sur le fichier figma ;)
