### ISSUE TITLE
Ajout des dispositifs d'acompagnement aux nouveaux déploiements

### ISSUE THREAD

**Issue by oblab** [gip-inclusion/carnet-de-bord#1856]
### :footprints: Étapes pour reproduire

Lors de la création d’un nouveau déploiement, ils faut prévenir les devs pour intégrer les dispositifs d'accompagnement (Social, Professionnel, Socio-professionnel)

### :crying_cat_face:  Comportement observé

Cela n'a pas été fait pour les départements suivant
- 11 - Aude
- 45 - Loiret

Aussi cela bloque les réorientations qui ne peuvent se faire qu'en fonction du dispositif. 

### :dart: Comportement attendu

Intégrer les dispositifs : 
- Pour l'Aude : **Professionnel**, **Socio-professionnel** et **Social**
- Pour le Loiret : ...

**Comment by lionelB** [comment]
c'est fait pour l'aude et le loiret.

**Comment by oblab** [comment]
Pas dramatique mais il manque un "n" à Socio-professionel
![Screenshot_20230630_095715](https://github.com/gip-inclusion/carnet-de-bord/assets/251367/cb222625-139c-4d68-873f-b545599cfa8f)

Et pourquoi mettre entre parenthèse ? Cela ne serait-il pas mieux d'écrire directement "professionnel" "socio-professionnel" ?
