### ISSUE TITLE
[Suport] Suppression de l'historique des actions d'un BRSA

### ISSUE THREAD

**Issue by oblab** [gip-inclusion/carnet-de-bord#1861]
### :footprints: Étapes pour reproduire

Les Ardennes ont fait un test sur le carnet de FB (id=17b93e06-bbd0-4d99-ad41-2ac30a11f0ce) en ajoutant 6 actions fictives sous l'objectif Santé. Ils ont supprimé les actions en question, mais elles restent visibles dans l'historique de parcours. 

### :dart: Comportement attendu

Il faudrait supprimer ces 6 actions de l'historique de parcours
![Screenshot_20230704_154318](https://github.com/gip-inclusion/carnet-de-bord/assets/251367/548dd26f-90c1-4391-ae87-1219a875b89d)

### :recycle: Environnement

Environnement (dev, prod...) : prod

**Comment by lionelB** [comment]
fait!
