### ISSUE TITLE
Ajout des dispositifs d'acompagnement pour la Guadeloupe

### ISSUE THREAD

**Issue by oblab** [gip-inclusion/carnet-de-bord#1873]
### :crying_cat_face:  Comportement observé

La Guadeloupe (971 - id=6387b987-b3a4-430d-ad05-792f10027e83) n'a pas actuellement de dispositif d'accompagnement

### :dart: Comportement attendu

Intégrer les dispositifs suivant :
- Social
- Professionnel
- Socio – professionnel
- PE

### :recycle: Environnement

Environnement (dev, prod...) : prod

**Comment by lionelB** [comment]
fait !
