### ISSUE TITLE
Rendre possible la synchonisation PE des Axes de travail & Objectifs via une action Hasura

### ISSUE THREAD

**Issue by vjousse** [gip-inclusion/carnet-de-bord#1887]
## :thinking: Contexte et problème observé

Actuellement les Axes de travail (focus) et les Objectifs (target) sont créés directement par le frontend via une mutation Hasura ce qui rend impossible la synchronisation avec Pôle emploi.

## :horse: Proposition de solution

Passer par une action Hasura et un endpoint Python pour pouvoir, par la suite, appeler la synchronisation Pôle emploi.

**Comment by lionelB** [comment]
Prendre en compte la modif et la suppression
