### ISSUE TITLE
Suivre les modifications faites par les pro sur les carnets

### ISSUE THREAD

**Issue by lionelB** [gip-inclusion/carnet-de-bord#1890]
## :thinking: Contexte et problème observé
Il est compliqué de faire des stats sur les modifications apportées à un carnet leur nature et la personne à l'origine

## :horse: Proposition de solution

Deux points: 
- Creation d'un systeme pour tracer automatiquement les modifications faites sur un carnet 
- Créer une vue aggrégée de notebook situation / notebook event / notebook_appointement / projet pro avec à minima, 
le pro, le carnet, le type d'action (modification de situation, création d'obj / action / projet pro / changement de statut,) 
afin de pouvoir avoir un historique des modifications sur une plus grandes période

Il faudra probablement créer un référentiel pour catégoriser les entrées

Il faudrait aussi prévoir de logger la modification d'info perso, la création / suppression d'axe de travail

 
## Impact métier
Cela nous permettra de plus facilement analyser la rétention et les usages que font les pro / Co dans carnet de bord

**Comment by HadrienMP** [comment]
### Facile: 

Sur table _notebook_, créer un trigger sur la colonne _lastUpdatedAt_ qui va renseigner une table notebook_updates avec les informations suivantes :
- id_notebook
- updated_at
- account_id
- [type]
   - objectifs
   - infos personnelles
   - ... ?

(même technique que notebook_visit cf. https://github.com/gip-inclusion/carnet-de-bord/pull/1869/files#diff-c6102f99feed689dc7a1f55feb78db768b9b796bb8b04d7a2dcdedfb183b4133)
