### ISSUE TITLE
[SUPPORT] Suppression de l'historique d'un BRSA (Aveyron)

### ISSUE THREAD

**Issue by oblab** [gip-inclusion/carnet-de-bord#1901]
### :footprints: Étapes pour reproduire

L'Aveyron a fait un test sur le carnet de EF (notebook=526feacd-df8f-48b6-82fe-d690c10da3da) en ajoutant des actions fictives.

### :dart: Comportement attendu

Il faudrait supprimer les events et actions (dans le plan d'action et dans l'historique de parcours), sauf les 2 suivantes à conserver :
- Découvrir un métier ou un secteur d'activité
- Développer son entreprise

### :recycle: Environnement

Environnement (dev, prod...) : prod

**Comment by oblab** [comment]
J'ai fait supprimer les 2 actions par le pro comme demandé par @lionelB , le pro les remettra une fois que vous aurez supprimé les events

**Comment by vjousse** [comment]
Voilà j'ai supprimé les events du notebook, sauf les deux concernant : 

- Découvrir un métier ou un secteur d'activité
- Développer son entreprise
