### ISSUE TITLE
Ne pas envoyer un erreur quand le feature flag ENABLE_SITUATION_API est désactivé

### ISSUE THREAD

**Issue by lionelB** [gip-inclusion/carnet-de-bord#1906]
# 👣 Comment reproduire

- Démarrer le backend avec `ENABLE_SITUATION_API=False` (ou absent).
- Visiter le carnet de Sophie Tifour

# 🐛 Comportement observé

- Un message `graphql error!` est loggé par le code Elm. Une erreur remonte dans Sentry si configuré.

# 🎯 Comportement attendu

- Aucune erreur n'est enregistrée lors du chargement du carnet.

# 🔍 Analyse

Le comportement souhaité était présent avant l'intégration de #1862 : https://github.com/gip-inclusion/carnet-de-bord/blob/93f805f5bdf4fe555e372aff2e9065e8efa07149/backend/cdb/api/v1/routers/refresh_situations.py#L86-L95 

Quand la récupération de diagnostic PE est désactivée, le serveur doit simplement répondre qu'il n'y a rien à mettre à jour. Ainsi, le client n'a pas besoin d'être modifié en fonction de l'activation ou désactivation de l'API.

**Comment by jonathanperret** [comment]
Une correction a été intégrée dans #1884.
