### ISSUE TITLE
rattrapage dispositif d'orientation - CD08

### ISSUE THREAD

**Issue by chdechamps** [gip-inclusion/carnet-de-bord#1908]
## Contexte : 
Afin de produire les indicateurs d'usage, nous avons besoin de connaitre le dispositif d'accompagnement des bénéficiaires puisque, selon le dispositif, la fréquence des rendez-vous (et donc consultation / màj des carnets) change. 

Par ailleurs, la mise en prod des dispositifs impacte la pratique des professionnels, notamment dans le cas d'orientation en veille sociale ou santé pour lesquels il y a des structures, mais pas de pro (les bénéficiaires étant dispensé d'accompagnement). Il y a donc des modifications a réaliser également sur 6 structures (en fin de ticket). 

### Dispositifs à créer (orientation_type lié entre parenthèse) 
- [x] Pôle emploi (pro)
- [x] AG (sociopro)
- [x] Renforcé (pro)
- [x] RIA (sociopro)
- [x] RIVE (sociopro)
- [x] MiLo (sociopro)
- [x] AETI (pro)
- [x] Social (social)
- [x] Veille Emploi (pro)
- [x] Veille Santé (social)
- [x] Veille Sociale (social)
- [x] Autres (FDM, droits clos, EP) (autre)

Concernant le dispositif `Autres (FDM, droits clos, EP)`, il vise à pallier l'absence de possibilité dans carnet de bord de réaliser des sorties ou d'identifier les bénéficiaires ayant une fin de mandat du fait d'une sanction (dans ce cas, ceux-ci sont encore au RSA et doivent reprendre contact avec le CD pour être réorienté après rappel des droits et devoirs par le COA. Si ce n'est pas fait dans le délai, ils finissent par être radié (droits clos) et sorti de l'accompagnement). Ne pouvant être lié à l'orientation_type pro / sociopro / social, je propose la création d'un orientation_type supplémentaire de autre qui pourra a terme disparaitre lorsque les fonctionnalités de sortie sera développé (et sinon, je ne sais pas auquel le rattacher) 

#### AETI 
b92587ed-e0cc-41dd-9244-3c90970499af
b4546b28-543a-4b38-998e-9b422441c5a8
f47aced3-4582-4a2d-a66f-a0c20fda611c
f9f263cd-3612-413f-99a4-cd65703decfc
3ebf4806-786e-4d62-b6da-b679c257f825
98afaf98-a749-4e87-91ae-fa9ab088269a
c0d40471-043e-4eee-a91d-7c3eb31f48f6
e3425e78-5fc2-483c-ba62-f5ace7584da9
922b647a-f3cc-442c-8593-e49630e9747b
cd8a0527-a763-4b24-8a8a-c82db445d9fc
cae67367-740f-4220-86cf-522310f53fb1
d93431df-26d3-4fb0-95b0-03658bff0b9f
b8fa4072-1517-4920-bd4b-117bb6e3fe0e
0cee799f-c3e0-4d81-80d1-8cbbbddb1b94
e28d3ea5-e3ee-4910-b639-dbd94240aa20
db70d67f-5b27-4834-bfed-02ea355fab50
ddcd2423-32fa-407e-9404-2e15faf65d36

#### AG
4afa4cd5-6ae2-44fa-8a1a-a8b315f90f66
1bb447c9-97e9-4e5c-8f57-d4c08e47e508
1f93154b-2793-4abe-a9fe-8d538c3fac7d
26614497-3af4-4202-bab2-d4060ad44399
f284f3c4-538b-4a11-8954-1ede703a4ccb
2895ebb6-0033-4876-80e0-51ddfbca28e0
ce43bf32-d3db-4115-b543-5f94919321a3
f9757ad8-84b0-45f4-9d69-17b7f720fe3b
8fcf4eb3-3468-42c9-a86b-6f1a2758a2a6
2a24f42f-8673-4fce-a539-507c73b252a4
5c337a33-88aa-4f89-bfc2-e4fe38c2f7eb
6819e167-678d-4f80-a872-619e904e15ec

#### MiLo
f72b6eca-3881-42cd-a2a5-842addc30b6c
4b6033bd-63ef-4e60-a3cf-e740f3054ab4
fd2fe8b5-5e16-491b-83e6-7fd4a346c79b
1553674b-319a-4337-9af5-6dae50355a47
76e5e49e-4a99-4ed7-ac4e-74572e94588f

#### Pôle emploi
4e7d2d52-0828-430c-bb11-c9952f7b8687
140a3c7e-f44b-428a-8ad9-13070c4a7ab2
4eeceb63-4d06-4d07-a8f8-ae5e596df8f1
d3134205-8f56-4a73-a85b-e29c7090ccd2
fe86ee95-03e3-47b0-8612-5202244c5927
69472aec-f3fc-47eb-a6ee-d9f83583199f
328ab098-da26-46b8-80c7-3146579e0bb8
8dca4e37-7f38-4140-82f4-caaf9705b460
23a1a170-8887-4a4a-aaeb-ec21c856bece
a024765d-9249-4505-a3fc-10d33ea51fab
281d38d6-a643-4bef-a688-9003ffd0d345
36ca021b-7518-42b6-87c7-6fa6fb353408
ca56aeaa-29b3-4346-a958-9c34661b07bb
1468951e-2937-40f1-8aa7-07967361cd02
d58afa70-1208-482e-8ad8-0ca3e7233dff
64b761cf-47b9-4e2a-b3f0-58242c4ec6e8
0db6e309-d587-4486-b555-3329f68fbbd0
cd95d7cd-ee4b-402c-a0b0-e8b54a0e150f
7e09e29c-8d80-4737-af0a-82f80e8640db
4b6b693b-f514-4f69-80a9-07ed0dfec173
55d64f54-3191-4308-bdc2-c61fa2b87691
0135dc21-acb9-4316-95b3-58a569f47d36
e48cabf1-411e-436a-bf0e-143cada896b8
46be98e4-4fa4-42c9-a581-d60da1699922
e0502c90-cff8-43e5-b2a2-71c59b072885
989a1a35-ed8e-447f-a701-57969dd7b547
59b79b53-b50d-4f75-a48e-038657bb3631
c0c3eb13-d32e-4e19-bf73-122c0b50b2ab
b1ad718e-a1a5-4be9-8eeb-bf3fbdf48b38
5cc73148-fae5-4581-a94c-5c013511e3d7
93cba857-3a60-46b2-9b57-b182dab47379
de343999-cea2-458b-b3e6-d047147159fd
47812ed0-f46a-4163-812b-c0e5da641716
9bb38943-2b64-48aa-acc8-40b34dd23db3
5786cefb-8c28-4e00-be3e-c507f8b0efba
96ee9a76-3f21-4594-acb9-3d4843257a55
897b7f0d-902e-4d97-b0d5-1260e432c603
0204c2d8-e2d8-4fd3-9f57-9be0af692f3c
c9cc9f65-659d-44a3-842d-28afeb410b6a
ca46c08c-84af-4cdf-8c1f-6441aff2a00e
3d9e0513-20c2-41d2-b490-4e5a8f85ccc3
37d0433c-f4e6-4006-9691-e5536d9938c3
5511ecf5-1ec1-4576-99b1-dab2df74f9d9
54f593c7-a2fa-4257-9ac7-fe839bba66f5
63df3d93-8e41-48c1-b77e-d88350f11dcc
827f963c-7754-4c71-8ce7-9d32a2388958
37a6e8ab-a368-4000-87fa-4e31d1007371
4a216b7a-577c-4129-86d7-7ab5236571e1
6c7f25bf-4ba1-45e6-a6ab-adafb08935d8
d551599c-0e60-47e5-a354-76e70bc44094
aef8cf90-c0e2-4eb1-9f88-4c7e1033c2dd
1bfe4c7b-872a-4099-9daf-d7d414cacd32
274e56d1-13b5-4c75-9415-130f918fa843
419e1bb0-2a33-4192-b4c0-9a0fd53a1793
fa0d0c03-b987-4476-b9ea-fd475023c243
46020b5a-dea7-4808-b146-31ae3d4a4d5d
bb07cd20-000e-432e-a24f-2cae0679d898
8dcb51a1-88d7-4bea-a53e-3987126cef32
9ec1b3be-e05f-4955-a3bc-e7c98b030f5d
f7dfbbe1-7f7e-42e0-bf12-c2c36a8b85cf
bb65e752-bbe9-4106-b938-e49ca1249d67
2b1d5854-2ee4-4132-b5f6-eecda3ed1743
9b0875a7-a306-4df1-8c81-ed63eb13761f
feb452be-5144-407d-98c7-8b2bf93cec92
a45f4015-f56e-4671-a235-33906893b523
da8140db-afb0-4296-b0e1-322448b275fe
c5fbfa12-f056-4356-93ae-aecf054639a3
46e4f638-390c-43fa-98f2-2173a72eeb75
47a31e25-566b-49f3-9af7-5aefa80647c8
96a98467-0687-4927-b1e8-ed870aa7cbd0
c0364e0b-c7db-4594-bb76-39ff6f45ee1b
e91763ee-d123-4ff3-8876-aad39f6a94f0
21c40a7b-ca3c-4ffc-aceb-cede788efdd3
3a331ff2-cff3-4329-bd0f-9375b30aa82d
1b40b2bf-14b4-4764-b94c-8b58f324ce21
f459d0f2-4184-41db-be8e-fa88ac197762
057243a7-7732-45d1-b22c-b1593a3ed221
d07552fe-e4db-49ba-9cd2-1f08a25a6dcb
1c29324d-dc0d-4ffa-8118-2ae871957bf0
40e9fd8e-cbab-40d0-b3c9-0903e84bb5d3
91bf774d-601b-4888-82db-d0d3b8df15b9
66f203d3-cab9-457f-bd35-e069ea6fce3d
17bec6d1-61a9-43a6-8d7e-5018bd39034e
293e6b1d-5cd4-420f-adb7-ceb7b5efea66
60cf3ecb-411b-4deb-afa7-c8793e13a52c
1be74190-1b08-4900-8a56-3109c99aef39
b6e09d3f-867b-480b-b1a4-f5fc5fa52714
194fdec1-4381-4e04-88cc-a2c0a53f7b19
9fecf7aa-c6a2-4c30-a5ed-aaa47ece8f4b
0381ba1e-1063-49e0-8524-3a8c97754a00
638df99e-2c72-4758-aeac-1304403cb0e3
85667c04-6823-41d8-8ea7-e6873d7ea42e
33b3e290-82b3-4431-8494-c4756a322409
118b456b-188d-446d-b736-ca15ea0723ce
e2f70fcb-dc9d-437d-964a-b0c220ef2567
fb0d8cd7-0c7c-41c6-b97c-30a0f3502f72
886e4017-6a8c-4107-ba18-bf2217b425c6
4968b9e8-a993-4a46-b0c7-c98b19b25ec6
157550f8-7ca9-41f9-8a2d-21adcf27a18a
0c2c2e91-73dd-4c58-afe6-0e1fbd578fb0
57abc43e-b6c0-49dd-9ab7-46273964fbe9
5202dd2e-1f4a-4153-bb3a-f393ec9aa14e
7900d931-4434-4045-998b-86b69fd5ea57
91dc77f9-8684-49f7-adf2-5516e806ecb9
8124eeda-3c66-4fa8-b529-9bc4dd4cf1c0
aee9f32f-a14b-4a96-8fe7-e4c87e0be64f
abead6a7-c422-484b-bb78-95c1532fbdbf
a13fe693-f172-419d-95a9-f90a47a74a77
60a48b01-6c2f-4e18-ad95-8fc0484c119e
91738b52-4d5a-44a4-a69d-5a6b7f34f508
7c07fa6e-4c31-4dc4-a9ca-a25053ff4d99
35fa0903-085c-40c8-ab20-cf13ccbb5ebc
6d0a6a7c-892b-4283-8b3d-378cfeb4b11c
71c49be5-2edd-4b67-995f-65c725f97ce7
33fe8a63-90a5-4f31-b3a4-6cccc2189ccb
02802c67-da50-45d1-9a91-f77a6d7efbc1
cd5c2720-fba9-413e-8df7-e253d22cc20c
bdd60322-d1e3-4746-9a10-31dcebebbae0
f003e85e-0f75-4851-8803-067d3a31daaa
dc8b16b4-52ad-4a35-8e3d-c30eecc29cf8
b2c0bc77-761f-4767-9e9c-966a5c64bf4b
dc7f2573-5a77-469e-afb5-849f0ea038e5
a79851cf-a96c-48fa-9290-bfdb68248af0
270a72df-33ef-46c5-9e71-0939b2790193
783f34e5-6867-4ed7-aac0-9a1d4a04e72f
6958e809-74a3-4822-ad3a-575135d02173
e23c45d7-c07e-4e65-b293-57681c4e7695
7d734aeb-8978-4d69-a9a6-f78e2bb34e24
95c554d7-9848-4a9b-b7f2-b29fb6448126
6fcad007-c9a8-487a-8411-9d9b8e39c796
5d9624ae-a1b3-4d30-b6dc-f9e8a312e9fe
93de214c-4057-4821-8539-16e1ed65cd05
975c91f0-cd26-4d77-8e44-ac114424994b
0d8f343f-5d3c-4313-a2e9-83b0679dfb2a
4d7b1a3e-fad4-4c07-af57-046e51fe206f
7284b931-4e73-4a03-a514-b82b7e39f2e1
e8aa8e40-02d7-436d-9407-9f1a21916ec4
62c88717-7110-4c63-948e-3b72e9906175
afdfd3e3-a691-49db-9683-2e6e7794c813
14a7a4ae-de3e-4d9f-9407-0d75a9d65ef9
803657b2-5a7a-4216-9048-c6be8058e3ae
437c93a7-e19e-41eb-8c66-2495e7d9ab1a
2f5e7b88-355a-4590-9c32-855a6953381e
514e11af-e8ca-434d-98a0-6f0afea06fe8
8a1c9f02-d6bb-480e-8e3b-13acbf221a59
fedbc7f3-f588-43c1-97dc-472374db0b10
a07032a8-d8ac-4db4-8c2d-387c3387840e
2fc84ee4-192a-43c5-a405-e33f30d8ff88
411eba08-fa9b-4787-a240-5ce380894a53
f77d4cf8-59ac-41a8-acbb-d92cd09fa0da
a827c6af-7fd8-434e-8cea-8dd298fa64de
a74cab22-d03e-4068-9d30-199e1cd42b19
d84a19ff-5aa1-45e8-bb64-0b0eeab9a75e
c14f5fc9-a7db-43f5-a69a-d7a7373a85ab
49b7424d-291c-4d97-96ec-d305e2d63934
da44353e-6190-40cf-9f7b-0878b23583c3
d0bd15bb-b781-4ec1-87b9-a8bb35a3ad9f
ae01af4e-9fc0-4612-8b4c-e42279029006
fd274cec-b16a-41e6-bccc-862ef8c0471e
929aed3e-220f-4379-a902-be81e9cb569f
754067f6-6eb1-47f1-8740-71cfc6216a4f
bdbffd1d-709b-4ecb-a6ec-8cee489293f1
c2b09415-d80d-4f67-bb59-3e9fec245372
9218305a-8ee9-4ff9-9378-ef3bd02160de
95b0e159-3726-446a-92a6-4396026ec364
57ed12e9-81a1-47f8-8aba-c87cde32621f
02e84111-7f18-49b0-9ddb-5468c9b0077a
52fbc8d2-6165-4c16-a7f7-fce1a10539c6

#### Renforcé
cc5b68e1-734e-4c45-a1a3-2896e80151e7
cd46057f-48bf-4df4-9730-40f33dc41acf
bcd72963-d322-4a0c-8b22-aea9ffe5f172
8d2b7397-d9a8-4f9e-a302-0b0263cb2d3e
c9c4bdc2-39f4-4f2a-88d8-f21c62533bad
d4b8f840-e578-4edf-97a8-aa3c21b8a42d
19f27025-0626-472d-b91f-fa06fd33c30e
b62604f6-4bd2-4952-8513-b7e50336518c
cf8f12d9-03fe-4923-a6da-161743f280b7

#### RIA
42b7bdc9-c535-480e-ada0-8c146528e6e2
92771bf2-05b4-49b5-8e5b-acd038e6cb1a
a441c7b7-2ca3-4811-83a5-8aa2e5c876f4
3e1f10e9-3769-4641-8d24-3b0742119b44
fa530ef9-b48e-4148-9015-ee43ebfb7c69
5eb9a0a8-0c75-4c4b-9bd1-91530c7abbdc
bf0d3f20-6016-4107-8584-ec94e2f3e3a6
99f184c6-bce0-4956-8478-130ddcac1546
d2dba13a-2e24-4137-a748-71daf9b9cad7
bb420418-3504-48c7-a0c8-487b8da40dc5
acd178d7-821e-4a75-a460-3b93fdca0457
8350f52a-2a4d-4c00-bc6c-a72bc5e743ea
e08694d3-98f5-4562-b565-c3b4842e716d
a8034a5d-f343-4402-9215-6cf031dd4e73
491667fd-7c70-465f-b424-b805230ccb98

#### RIVE
479206eb-f83b-4e0e-9b3f-762f01f974d0
79b44e65-e810-4dbf-a339-e79c98688da0
306be86e-ca1e-4eef-b81c-59dd730e473c
3ce35a0f-daa3-4a89-81fb-d0218b9b7eeb
326f4702-ab88-4f0b-a919-aecabb9fd502
30fa514e-7693-43ea-a2cd-a6ffe0787511
72a3ed0b-a2a3-4320-82c6-f958055e7f34
1758a697-5eba-40af-865c-fee77345b566
734ac033-f345-4ca8-a602-1a369329261e
edb64cc1-4dbf-4fab-baf5-92e3c8abad3b
580325b3-e20c-48f5-9b2e-21506bf367cb
c60ad13e-8335-4b48-b598-98668ee43e75
1ce3b4a7-9ab4-4ae3-bab2-b6f884e66f58
a917184c-ba77-45ac-b2bc-c7673eadb0f2
15e542a0-3519-4e10-8b3d-5a0cc08d3ac7
cc20d24e-f4f1-4247-9d2d-9e0f24511df4

#### Social
e227c3b6-4081-4d34-8ab7-ce0f6320962c
307289fb-6400-4d75-a2db-2a57f2e73283
4264f9d0-588c-4ec2-a4a6-c3a1bd58862c
5dd98137-d298-4ca1-824a-6585b4c7f29c
d2f1de49-ee90-45b1-9dbb-8e25def93f33
a7b3f708-3d25-4478-96f7-49edb3ad44fa
37fb7ae4-dee2-4ca8-b94c-cd98258a689a
4a30d1b0-4e70-4fcf-9127-dc9236c42af5
650ff3fd-a051-4a56-98d0-2b14f11d4508
d1ffbec2-3832-4e09-b9a7-0d152f675c91
b64e9228-ac6f-450e-83e0-5fd4761909d2
838c2f62-94b8-48fa-a71d-8b48f63cb74c
af02d5b0-4475-4076-942c-6ef49e5069e9
e2a656a7-a40c-4097-baec-ee0280675161
3dafa826-d8f2-4704-ab70-66fcc93f7dc1
36ef0c89-9fdb-4091-8413-965ac68abae0
7f9eed00-7fe1-4a95-8cff-210e754c9327
82801791-b221-4933-9c4b-1546f4e0f159
78badd73-7e4b-4b41-89b3-919b014d42b2
94c4b4d0-16d5-43b5-af9a-dbda556e0202
35f81bec-c386-4fd3-aa9b-f7d3052c3812
72f00001-620e-49d7-8566-6947aaf9f623
24380ee6-a158-437c-9915-58342d9ac286
437dec7b-b8dd-4b41-b5a2-7124ac38bd1b
74ee69ea-75a9-4bf5-9044-57a675b6af32
30cad457-1d91-4adb-8784-03f4aecad017
92958990-87aa-4dbe-916f-3d0fb46314a9
596cd3a4-e595-4ef6-b0d9-c3a49c301970
3ef373ed-d7a9-46bd-bf9a-65f7391a327f
6a5e0677-cbb5-401e-a17f-fcc64fbd9d42
79c4679f-cbc6-413d-9a3f-73abe186e545
79271f6c-c637-4b13-aa27-53e9fd782ba5
c556402c-3ac0-456c-b425-50be1b968bc2
03d7bc84-0686-4fb5-a606-0814b2b1c62b
9c35b25c-4f70-4448-beca-234053072f71
21e7a153-6bd3-47f7-a576-c899edfec5cf
e08465e1-54cf-40a5-97b9-bddf6d991436
cb148840-429a-4b0a-a109-4aa1a6532b2f
4b6d2efd-126c-467c-b7f9-34be68a5d381
60d76808-2dea-41fd-b478-4ebe5f7cd644
415960d4-77c3-4c83-a776-feeb8d7beb21
07357006-33d6-4ea1-bf0f-bc1b553801da
67a76fd6-bbfd-4b99-ba34-52518ee8209b
518c10f3-c8d5-4be6-aebc-ce65af1d8770
30ee3ad6-6226-485a-8951-e9de3d5d6f7b
38e6a030-3278-4c1f-a340-b469c735522f
8ae3b723-dc64-4da3-8efe-2ea08a0adc3d
b49e7e91-844b-48f2-b191-c239d07aee0f
c7b7fc6f-7082-4a83-a59a-d43ac07bdb40
de54d187-aabc-4799-a871-9f480acf00a7
2c50e27c-a3f8-42c5-a600-719b60d8f7e5
be0739bb-e624-4f8d-ac2d-4f7cf68790c6
f045f673-956f-45ed-9e4c-87f64a067c55
be1febd2-752d-4156-b792-1347324882d3
28e9b499-cbc2-4ba8-98db-16a9a3b233b6
887cd133-c098-4ab1-a9bd-547b2b622167
528f8e94-4b66-4458-85c3-858789c69ab8
ac1415b2-defe-4491-a12f-661a59f87863
50e691f3-e45c-4f01-8455-a25361a50061
875089ae-7cac-4705-bd4a-9e4e196a290d
62ab522e-6f7c-4140-ab91-43ccab4228af
df82ad2b-61ed-4edf-9fd7-c1436b45255e
7f211cd0-aee2-4e76-b14e-0dd2a25d95b8
d8b0d169-53bc-44da-b44f-f13eb9b4715e
8e480ab1-9b4d-42f7-a010-737ee00d0f9e
cd026977-e2c9-48bb-99ee-28da5383f742
26d23b6a-80d9-4c52-9338-3fc622e9d485
12a6a9b6-edb8-45cf-b8c4-e129ce914945
8ee8fce5-824e-410f-bc40-42ca80b6445c
11b47004-dc09-4665-a78a-245183e5a68f
f1e49351-65cf-49e6-ad9d-2a72c8696d6a
92b369ff-ff87-4343-84a2-683f030e1470
94041917-574d-4f15-803f-35da1044beff
020cecd4-6547-4586-8be9-87624869b4af
2496d2f4-807f-4e15-b1c9-98862ad18eb4

#### Veille Emploi
1b6d24ec-b63b-4e77-b4b0-5db55dc4d49d
a691191c-9cc9-4266-aa60-f12f84bb104b
f855a28a-e4eb-485b-867c-37a44f3715c1
dcdcfb3b-e47c-46a9-9939-fa73457d053f

## Structure sans professionnel pour les dispositifs : 
c4dd5172-fd1e-49aa-b56c-70c761245517	MiLo
cd668310-1bd7-4c81-8967-5e35824a3291	MiLo
418bb5ce-c68e-4cde-a9d7-632dcf8335d4	Veille Sociale
d8a8dd2c-125d-450e-bb63-6ed80a727765	Veille Santé
4d8d8a2d-7360-47f7-bff5-7fc29ff0a6d7	Autres (FDM, droits clos, EP)
8d94eb5d-c1a4-49b6-a958-9576e1cbcc28	Autres (FDM, droits clos, EP)

**Comment by vjousse** [comment]
Dispositifs créés et ajoutés au Ardennes le 27/07 à 16H13 :
- Pôle emploi (pro)
- AG (sociopro)
- Renforcé (pro)
- RIA (sociopro)
- RIVE (sociopro)
- MiLo (sociopro)
- AETI (pro)
- Social (social)
- Veille Emploi (pro)
- Veille Santé (social)
- Veille Sociale (social)

**Comment by chdechamps** [comment]
Les infos entre parenthèse était pour le rattachement interne à l'orientation type et n'avaient pas particulièrement pour but d'etre affiché dans le carnet. Est-ce possible d'enlever l'orientation type depuis le front pour les utilisateurs ?

**Comment by jonathanperret** [comment]
Les données ont été insérées (journal : https://www.notion.so/gip-inclusion/2023-08-02-Rattrapage-dispositifs-orientation-Ardennes-30c491018c7042198ead31704791f9ef ).

@chdechamps L'affichage du type de dispositif (social, socio-pro…) dans le front entre parenthèse n'est pas systématique, on le voit lors de l'aperçu d'une demande (avec une faute d'orthographe ici d'ailleurs) :
> <img width="722" alt="image" src="https://github.com/gip-inclusion/carnet-de-bord/assets/300823/ffcdc755-99d5-463a-85bf-54c1d2f52ee2">
mais pas en tête de carnet :
> <img width="687" alt="image" src="https://github.com/gip-inclusion/carnet-de-bord/assets/300823/e5bd8eba-3e5e-4529-a3ad-d582fe057073">

Pourras-tu faire un ticket séparé si tu veux changer ces différents affichages ?

**Comment by chdechamps** [comment]
Si on peu l'enlever dans les Ardennes pour les référents (lorsqu'ils demandent une réo ou a l'affichage de la décision de réo) et pour les CO dans le menu déroulant + dans la demande. 

Est-ce affiché ailleurs qu'à ces endroits ?  Est-ce que c'est gérable par déploiement ou est-ce que ça concerne tout le monde ? Si c'est gérable par déploiement, je ferrai un ticket, sinon, un accompagnement au changement du département ;)
