### ISSUE TITLE
BUG 86 : ETQ CO, lorsque je consulte un carnet, je ne visualise pas le contenu du diag (situation personnelle)

### ISSUE THREAD

**Issue by chdechamps** [gip-inclusion/carnet-de-bord#1912]
BUG sur le déploiement 86 (bug absent en prod 08 et en démo). 

Dans ce déploiement, le diag est externalisé (réalisé par la CAF dans CDB). La CAF réalise le diag puis sollicite une réo au CO du CD. 
ETQ CO quand j'accède aux carnets pour lesquelles une réo est demandée, je ne vois pas les éléments situation perso saisi par le pro. 
Ces éléments sont pourtant visible pour le meme carnet par le pro qui a réalisé le diag ainsi que le manager de territoire. 

Il y a 2 CO sur le territoire, meme comportement. 

Testé en prod par l'un d'eux sur Edge + Firefox

Voir si lié avec #1913

**Comment by vjousse** [comment]
Actuellement, seul un CO faisant partie du groupe de suivi peut voir la situation personnelle d'un bénéficiaire.
Le CO du 86 ne faisant pas partie du groupe de suivi des bénéficiaires consultés, il ne voit rien dans la partie « Situation personnelle ».

Est-ce un comportement attendu ou devons nous ouvrir l'affichage de toutes les situations personnelles à tous les CO de la structure ?

**Comment by chdechamps** [comment]
Du fait de la possibilité de rattachement a nouveau opérationnel dans le 86, cloture du ticket as not planned. Un nouveau ticket devra etre créé si la consultation du carnet par un CO non rattaché est nécessaire.
