### ISSUE TITLE
BUG 86 : en tant que CO, quand j'essaye de me rattacher a un carnet, ca tourne et ne fonctionne pas.

### ISSUE THREAD

**Issue by chdechamps** [gip-inclusion/carnet-de-bord#1913]
https://mattermost.incubateur.net/betagouv/pl/tcti5a8hebbefjr1pqun9unniy

**Comment by vjousse** [comment]
Il existe 4 entrées dans la table `orientation_manager` qui n'ont pas de compte associé (ce qui est théoriquement impossible). Ce sont tous des `orientation_manager` du 86.
Je n'ai aucune idée de comment c'est possible, mais pour régler le souci il faudrait supprimer ces 4 `orientation_manager` qui ne peuvent de toute façon se connecter.

**Comment by HadrienMP** [comment]
Voici la requête qui permet de diagnostiquer ces comptes : 
```sql
SELECT orientation_manager.firstname,
       orientation_manager.lastname,
       orientation_manager.email,
       a.id,
       d.label
from orientation_manager
         LEFT JOIN account a on orientation_manager.id = a.orientation_manager_id
INNER JOIN deployment d on orientation_manager.deployment_id = d.id
where a.id is null;
```

**Comment by HadrienMP** [comment]
Le code qui pose problème est AddOrientationManagerForm.svelte ligne 27
```ts
$: orientationManagerOptions =
		$orientationManagerStore.data?.orientation_manager.map((pro) => ({
			name: pro.account.id,
			label: displayFullName(pro) || pro.email,
		})) ?? [];
```

pro.account peut être nul. Il faudrait probablement filtrer les OM qui n'ont pas de compte
