### ISSUE TITLE
Ardennes : suite mise a jour des dispositifs

### ISSUE THREAD

**Issue by chdechamps** [gip-inclusion/carnet-de-bord#1931]
Désactiver les dispositifs pro et socio pro dans les Ardennes. 

Sur un dispositif, dans la base, pouvoir activer / désactiver le dispositif. Un dispositif actif doit pouvoir être sélectionné par les pro / co / etc . Un dispositif désactivé doit être masqué (mais conservation de l'historique). 

NB : les requêtes étant nationale, le type d'orientation requeté pour les chiffres seront plutôt sur le type d'orientation (pro / social / sociopro) que sur des dispositifs locaux différents d'un territoire a l'autre..  

A réaliser après la #1932 puisqu'en attendant, l'orientation pro est utilisée pour les fins de mandat.

**Comment by jonathanperret** [comment]
La correction de #1932 est en production et le dispositif "Autre" peut donc être utilisé pour les fins de mandat.

J'ai saisi #1942 pour suivre le développement d'une fonctionnalité "dispositifs inactifs".

Dans l'immédiat, je propose de renommer les dispositifs "Professionnel" et "Socio-professionnel" des Ardennes en "[NE PLUS UTILISER] Professionnel" et "[NE PLUS UTILISER] Socio-professionnel" afin de communiquer le statut de ces dispositifs.
