### ISSUE TITLE
Relire / Refactor ajout/modification du NIR

### ISSUE THREAD

**Issue by HadrienMP** [gip-inclusion/carnet-de-bord#1948]
La PR suivante a été mergée avec une relecture très légère pour débloquer Charles. Ça vaut le coup de relire pour voir si la forme convient.

https://github.com/gip-inclusion/carnet-de-bord/pull/1943

**Comment by lionelB** [comment]
Je vois 1 soucis:
- les nir peuvent contenir des lettres (2A / 2B) ce qui fait que le validateur va bloquer les nir corses 
ET quelque remarques:
- l'utilisation de trimToNull alors que le model yup définit un transform qui fait deja cela. Il faut utiliser `schema.cast(values);` dans le submitHandler()
- on aurait pu utiliser le validateur de Luhn pour les nir à 15 caractères (et pas de validation pour les nir à 13) et utiliser  un transform pour ne garder quand les 13 premiers caractères au moment de sauver
