### ISSUE TITLE
Support Aveyron : soucis de connexion avec conflit username / email

### ISSUE THREAD

**Issue by chdechamps** [gip-inclusion/carnet-de-bord#1954]
**Contexte :** 
Suite à la création de 4 profils manager sur le territoire de l'Aveyron pour des utilisateurs ayant déjà 1 ou 2 autres types de profil (CO / Pro) associé a leurs email, ces derniers rencontrent un problème lors de la connexion : 
- un pro ne peut plus se connecter en tant que CO (email en username alors que le mail part sur l'email de manager). 
- un autre indique ne plus avoir accès a ses autres comptes 
- les deux autres sont en congés et n'ont pas pu etre contactée par la correspondante du CD.

**Solution :** 

Pour les accounts ID suivant, modifier l'username en supprimant @ et ce qui suit. Pas la peine d'ajouter un numéro, les autres comptes de ces personnes sont le préfixe de l'email suivi d'un numéro. L'username sans le numéro est donc disponible. 

- c36fc2cf-c9bd-4a92-953a-e4b86f900702
- c00945d8-0dc3-4a0f-afc4-13d1c7d04260
- 8731be51-5f11-4375-b541-17a312496b1d
- cab85784-8386-46ac-900d-89b36c9ddc4f

**Comment by vjousse** [comment]
C'est fait !
