### ISSUE TITLE
Support 12 : création de dispositif d'accompagnement

### ISSUE THREAD

**Issue by chdechamps** [gip-inclusion/carnet-de-bord#1956]
Création de nouveau dispositif sur le déploiement de l'Aveyron (entre parenthèse le orientation type correspondant) : 
- Accompagnement global (sociopro)
- France Travail - Equilibre (sociopro)
- France Travail - Dominante sociale (social)
- France Travail - Dominante professionnelle (professionnel)

**Comment by chdechamps** [comment]
Note pour Charles : Voir Julies Gares a son retour de congés pour la répartition des structures / pro

**Comment by lionelB** [comment]
c'est fait !
