### ISSUE TITLE
Support Corse : Création d'un compte pro a partir d'un email déjà utilisé en manager / gestionnaire de structure et CO

### ISSUE THREAD

**Issue by chdechamps** [gip-inclusion/carnet-de-bord#1963]
**Contexte et problème :** 
VR est actuellement manager / gestionnaire de structure et CO dans un CIAS. Elle exerce différente mission allant de la gestion d'équipe, orientation des publics, gestions des structures jusqu'à la réalisation d'ateliers numériques avec des bénéficiaires. 
Afin de saisir les actions réalisée durant ces ateliers (création de compte france connect, création d'un espace de stockage en ligne, réalisation de démarches en ligne, ...), elle a besoin d'un compte de professionnel, ce qui lui permettra également d'accéder a la liste de ses suivis dans ce cadre. 

Pour cela, elle a essayé depuis son compte de gestionnaire de structure de créer un professionnel avec son propre email. Un message d'erreur lors de l'upload du fichier csv apparait : `Une erreur s'est produite, le professionnel n'a pas été importé. (un compte associé à l'email existe déjà)`.

**Solution :** 
Sur la base des mêmes infos que Account ID : `a2f213de-4254-46c1-be6f-56294d93582f`
créer au sein de la structure (ID structure : `1a7e58d6-b4d4-4d6b-9a56-77c0b20c5c9a`) un pro avec le meme email que l'account mentionné. 
Concernant l'username, le numéro a la fin de devra etre `3` au lieu de 2 sur l'account mentionné (email déjà utilisé pour manager / gestionnaire de structure et CO, d'ou le 3).

**Pour aller plus loin :** 
Lors de la création d'un pro, CdB s'assure du fait qu'aucun compte n'existe avec ce mail, or ce n'est pas le cas pour les autres types de profil. En effet, pour le Vaucluse, j'avais d'abord créer les comptes de pro avant de créer ceux de manager ou CO selon les profils et c'était passé (mais il n'y avait pas de données préexistante).

Ne pourrions nous pas modifier la règle de vérification comme suit : 
Permettre la création d'un pro au sein d'une structure **sauf** si un autre compte non supprimé (deleted_at = vide) existe avec le meme email et est associé a un compte de PRO (pour écarter les comptes CO / gestionnaire / ....) ?

**Comment by lionelB** [comment]
c'est bon. Est ce que j'enchaine avec le refacto de l'import de pro comme proposé en fin de ticket ?

**Comment by chdechamps** [comment]
Ok si niveau tech ça semble pertinent avec les choix qui ont été fait à la base ?

**Comment by lionelB** [comment]
c'est cohérent mais peut etre pas  le plus urgent

**Comment by lionelB** [comment]
Je cloture la demande de support et j'ai ouvert une autre ticket pour la suite #1978
