### ISSUE TITLE
BUG : horaire des rdvs

### ISSUE THREAD

**Issue by chdechamps** [gip-inclusion/carnet-de-bord#1974]
ETQ pro, quand j'ajoute un rdv dans carnet de bord, celui ci apparait a H+2 lors de la sauvegarde. 

Par exemple, si j'indique ETQ Pierre Chevalier avoir rdv avec Sophie a 10h00, l'horaire affiché après enregistrement sera 12h00.

**Comment by lionelB** [comment]
je pense que c'est lié à https://github.com/gip-inclusion/carnet-de-bord/pull/1935 :/
