### ISSUE TITLE
supprimer les colonnes "orientation"

### ISSUE THREAD

**Issue by chdechamps** [gip-inclusion/carnet-de-bord#1982]
### Contexte : 
Il existe le statut d'orientation (orienté / a orienter) dans carnet de bord. Ce statut semble etre calculé selon le fichier d'import csv. 
Dans les fait, il est faux puisque nous voyons des bénéficiaires a orienter qui sont orientés vers une structure. 
Ce statut devrait pouvoir etre calculé selon les infos dans CdB. En l'état, il est inutile voire confusant. 

Proposition de suppression des colonnes orientation dans la vue manager et dans la vue gestionnaire de structure.

### A supprimer depuis l'interface manager : 
![Image](https://user-images.githubusercontent.com/117724992/263954295-8b7e9b52-183d-43f8-82ff-0d198061d760.png)

### A supprimer depuis l'interface gestionnaire de structure : 
![Image](https://user-images.githubusercontent.com/117724992/263954581-99dfa854-2af3-4e91-bc77-2dcbf9e6083c.png)

**Comment by lionelB** [comment]
Est ce qu'on doit supprimer la colonne de la base ? 
Sachant que la colonne est alimenté par un booléen lors de l'import de bénéficiaires
![image](https://github.com/gip-inclusion/carnet-de-bord/assets/160320/fa80727d-1d34-4554-8a44-f52209a911c8)

Doit on aussi supprimer cette fonctionnalité ?

**Comment by HadrienMP** [comment]
Comme vu avec @JonathanRaimond, un bénéficiaire peut être réorienté si le benéficiaire a une structure
