### ISSUE TITLE
Afficher le dispositif d'accompagnement du bénéficiaire dans carnet de bord

### ISSUE THREAD

**Issue by chdechamps** [gip-inclusion/carnet-de-bord#1983]
### Contexte : 
Dans carnet de bord, nous n'affichons pas les types de dispositif vers lequel le bénéficiaire est orientés.
Pour gagner en lisibilité, il nous a été demandé d'afficher le dispositif d'accompagnement du bénéficiaire dans le carnet ainsi que dans les listes pour tous les professionnels (manager, CO, professionnel). 

### Dans le carnet : 
![Image](https://user-images.githubusercontent.com/85908681/263952338-94c02566-9e03-46be-a337-6d25b871542a.png)

### Pour les pro (quand ils sont référents du bénéficiaire) : 
![Image](https://user-images.githubusercontent.com/117724992/263948172-32f0c1d3-37ad-4266-836f-08abc8fe182c.png)

### Pour les CO :
![Image](https://user-images.githubusercontent.com/117724992/263951754-2408d309-5e72-4a86-930c-2944062f9d15.png)

### Pour les gestionnaire de strucutre : 
![Image](https://user-images.githubusercontent.com/117724992/263956203-cf14cedb-2611-4f56-b9b5-70b1113e49ec.png)

### Pour les manager : 
![Image](https://user-images.githubusercontent.com/117724992/263957409-d5278081-76a8-4875-b99c-8d92bf020f6d.png)

**Comment by lionelB** [comment]
Je sais pas si c'est prévu, mais ca serait bien d'historiser quelque part le dispositif du bénéficiaire

**Comment by lionelB** [comment]
> Je sais pas si c'est prévu, mais ca serait bien d'historiser quelque part le dispositif du bénéficiaire

ok je viens de voir #1984 😅
