### ISSUE TITLE
[support] Correction de profils (Aveyron)

### ISSUE THREAD

**Issue by oblab** [gip-inclusion/carnet-de-bord#2011]
### :footprints: Étapes pour reproduire
 Plusieurs double profils CO/pro ont été créés sur le déploiement de l'Aveyron, en créant d'abord le profil CO puis le profil pro. 

### :crying_cat_face:  Comportement observé

Or, créés dans cet ordre, l'identifiant CO reste l'email, tandis que l'identifiant pro est de type "prenom+nom1". Il en résulte une impossibilité de se connecter au profil CO. 

### :dart: Comportement attendu

corriger les identifiants des 12 profils CO concernés

**Comment by lionelB** [comment]
c'est fait
