### ISSUE TITLE
 [BUG] Carnet d'un bénéficiaire qui ne s'affiche pas (Aveyron)

### ISSUE THREAD

**Issue by oblab** [gip-inclusion/carnet-de-bord#2019]
### :footprints: Étapes pour reproduire

L'Aveyron a créé le carnet d'un bénéficiaire PC (id= d8d993b5-e75a-4aae-996e-7ca911f7f48a)

### :crying_cat_face:  Comportement observé

Lorsqu'on tente d'ouvrir le carnet (ETQ admin de territoire ou ETQ que pro) de cette personne une page vide s'affiche avec le message "Une erreur s'est produite. Si le problème persiste, veuillez nous contacter." :  https://carnetdebord.inclusion.beta.gouv.fr/manager/carnets/%20678cbf54-0d2d-4519-b04b-1d0f95fa1913

 ![Screenshot_20230925_115600](https://github.com/gip-inclusion/carnet-de-bord/assets/251367/fd45c47b-0f9e-4c73-8a0c-724cbf580025) 

### :dart: Comportement attendu

rétablir le carnet de ce bénéficiaire

**Comment by oblab** [comment]
ajout d'un compte admin pour vincent avec email "+admin12"

**Comment by vjousse** [comment]
Le pro auquel est rattaché ce bénéficiaire est rattaché à l'agence PE "Agence Pôle emploi Viry-Châtillon" d'où le souci.
