### ISSUE TITLE
[Bug] Impossible de consulter la liste des BRSA accompagnés par des pros (Creuse)

### ISSUE THREAD

**Issue by oblab** [gip-inclusion/carnet-de-bord#2029]
### :footprints: Étapes pour reproduire
Sur le déploiement de la Creuse, ETQ admin de territoire, je consulte la liste des pros. 

### :crying_cat_face:  Comportement observé
Pour deux pros, AB (73bdbf86-7a7b-43cc-8ebb-fa3fdae6ab3a) et EdM (9a25ab8e-1ae0-41d3-9253-068e502864b7) lorsque je veux consulter la liste des bénéficiaires qu'ils suivent, j'arrive sur une page sans résultat. 

![image](https://github.com/gip-inclusion/carnet-de-bord/assets/251367/47b1e37d-9e82-4f59-900b-725e9d9379b6)
![image](https://github.com/gip-inclusion/carnet-de-bord/assets/251367/1d37f580-945f-45e2-a3fc-8ac66ecac609)

### :dart: Comportement attendu

Corriger ce comportement pour pouvoir visualiser la liste des BRSA accompagnés par ces deux pros

**Comment by chdechamps** [comment]
Ajout de Vincent sur l'admin du déploiement avec email spécifique ajout de "+admin23" dans l'email.

**Comment by vjousse** [comment]
Le souci est réglé. Les deux pros avaient un espace d'ajouté à leur email. On cherchait donc les utilisateurs ayant un accompagnateur avec l'email "toto@creuse.fr" alors qu'ils avaient des emails en "toto@creuse.fr " (notez l'espace à la fin).
Il faudrait comprendre comment la saisie d'email avec des espaces à la fin est possible et/ou ne pas chercher par email mais par ID de pro. CdB étant en mode maintenance, ça ne sera pas développé.
