### ISSUE TITLE
Modification username

### ISSUE THREAD

**Issue by chdechamps** [gip-inclusion/carnet-de-bord#2040]
Modification des usernames suivants : 
- d0ae09fd-7653-45b3-8ce1-0c6f5b783152 de celine.bousquet@aveyron.fr en celine.bousquet.co
- fcff3e6e-88d1-4ebc-8301-274387028593 de celine.bousquet1 en celine.bousquet.pro
- e9786a68-51a0-4e92-b2a2-408e7b3d420a de jeremie.saillan@aveyron.fr en jeremie.saillan.co
- f7fb1979-8654-4db3-9abb-136820b95bed de jeremie.saillan1 en jeremie.saillan.pro

**Comment by vjousse** [comment]
C'est fait !
