### ISSUE TITLE
Modifier l'email d'un pro supprimé

### ISSUE THREAD

**Issue by chdechamps** [gip-inclusion/carnet-de-bord#2043]
### Situation : 

L'email utilisé par l'account ID : f6ee01fc-e1a5-4472-96f4-38f2f575b597 est un email générique. Au départ du pro, le compte a été supprimé. Sa remplaçante à pris ses fonctions et récupérer cet email générique. 

### Solution : 
Afin de pouvoir créer le nouveau compte, il faut modifier l'email de l'account ID f6ee01fc-e1a5-4472-96f4-38f2f575b597 en y ajoutant .deleted à la fin (nous n'avons pas la date de suppression). 

Ainsi la structure sera en mesure de créer le nouveau compte pour le nouveau professionnel sur ce poste. 

Voir #2030 pour éviter de nouvelles demandes à l'avenir.

### Note pour Charles 
Prévenir Céline quand c'est fait pour qu'elle puisse créer le nouveau compte.

**Comment by vjousse** [comment]
C'est fait.
