### ISSUE TITLE
Modification d'username (.pro et .co)

### ISSUE THREAD

**Issue by chdechamps** [gip-inclusion/carnet-de-bord#2045]
Modification de l'username : 
- account ID : 870d4d8a-e6ba-4898-8c23-f74ca49e60d6 de peuch.celine@***.***.fr en peuch.celine.co
- account ID : 8beb9323-d84d-48a2-b81e-76c112ca7d29 de peuch.celine en peuch.celine.pro 

En lien avec #2039 pour éviter d'avoir à traiter de nouvelles demandes en ce sens (PI, l'Aveyron est en train de recruter des agents qui auront besoin de plusieurs profils)

Prévenir Aurélie quand c'est ok (support crisp)

**Comment by vjousse** [comment]
C'est fait.
