### ISSUE TITLE
BUG 81 : Orientation / réorientation impossible

### ISSUE THREAD

**Issue by chdechamps** [gip-inclusion/carnet-de-bord#2047]
ETQ manager ou CO du déploiement du Tarn (81), quand j'accède à un bénéficiaire et que je souhaite le réorienter, je sélectionne le type d'orientation puis la page se fige et je suis totalement bloqué. 

Même comportement sur tous les bénéficiaires du territoire. 

Pour mémoire : la dernière fois qu'il y a eu ce soucis, c'était suite à un import de bénéficiaire sur une structure d'un autre département (problème fichier d'import en .csv). Toutefois, le collègue me dit que son dernier import date de début octobre... A voir s'il y a le meme soucis suite a l'import par un autre manager ? 

### Quand ce sera réglé (support) : 
- faire réo des bénéficiaire de Mme LIPPENS => Mme TOURNERY. 
- Prévenir Fabrice

**Comment by JonathanRaimond** [comment]
vincent.jousse+81@beta.gouv.fr

**Comment by vjousse** [comment]
Deux pro n'avaient pas d'account associé ce qui faisait planter la requête. Supprimer les entrées correspondantes dans la table pro a réglé le souci. Certainement du à une suppression d'entrée dans la table account. Être vigilant quand on supprime dans account à bien supprimer dans pro/benef/co etc car il semble qu'il n'y ait pas de on delete cascade.
