### ISSUE TITLE
Suppression en masse de compte gestionnnaire de structure

### ISSUE THREAD

**Issue by oblab** [gip-inclusion/carnet-de-bord#2049]
### :footprints: Étapes pour reproduire
 ENTQ admin CDB, je me suis créé de très nombreux comptes de gestionnaire de structure sur CDB 

### :crying_cat_face:  Comportement observé

Ayant quitté mes fonctions, je continue de recevoir toutes les alertes mails relatives à mes multiples comptes gestionnaire de structure

### :dart: Comportement attendu

Supprimer en masse tous les comptes gestionnaire se structure attachés à l'adresse mail prenom.nom+structurexx@beta.gouv.fr

**Comment by vjousse** [comment]
C'est fait.

**Comment by oblab** [comment]
Merci @vjousse !
