### ISSUE TITLE
support 45 : modifier NIR + N° interne beneficiary

### ISSUE THREAD

**Issue by chdechamps** [gip-inclusion/carnet-de-bord#2051]
Lors de l'import du bénéficiaire, le département a fait une erreur dans le NIR qui est également utilisé comme external ID. 
Il faut modifier en base pour les bonnes valeurs afin de pouvoir permettre au département de créer l'autre bénéficiaire avec le bon NIR.

### Solution

Pour le beneficiary ID : 51cea25e-4d69-4af7-9660-977438e4ff9d 

Modifier l'extranal ID et le NIR de ce bénéficiaire (voir ancienne et nouvelle valeur ici) :  https://mattermost.incubateur.net/betagouv/pl/xhjxrmrfkpy1x8xtr7sjdr36xy

Pour @JonathanRaimond quand c'est fait => Prévenir Aline pour qu'elle puisse créer l'autre bénéficiaire.

**Comment by vjousse** [comment]
C'est fait.
