### ISSUE TITLE
Support Creuse (23) - Erreur de saisie du numéro d'identification de bénéficiaires

### ISSUE THREAD

**Issue by JonathanRaimond** [gip-inclusion/carnet-de-bord#2052]
## Contexte : 
Certains bénéficiaires ont "l'external id" d'un autre bénéficiaire ce qui bloque la création du carnet depuis RDVI 

Etant donné que le bénéficiaire "A" a l'external id du bénéficiaire "B"
Lorsque je clique sur "Créer le carnet" pour le bénéficiaire "B" depuis RDVI
Alors, le carnet du bénéficiaire "B" ne peut être créé.

## Liste des bénéficiaire concernés :

BOUTEAU E. - NIR: 2040823096063 - External id à remplacer : 38489 -> 41107
HAG HASAN M. - NIR: 1810499206052 - External id à remplacer : 83412 ->83413
BENOIT E. - NIR: 1880194081071 - External id à remplacer : 038595 -> 80997
BENOIT M. - NIR: 2900277305018 - External id à ajouter : 80996

**Comment by vjousse** [comment]
C'est fait.
