### ISSUE TITLE
Support Creuse (23) - Erreur d'import

### ISSUE THREAD

**Issue by JonathanRaimond** [gip-inclusion/carnet-de-bord#2055]
## Contexte : 
Aurélie Pichot est une professionnelle qui a été importée dans la mauvaise structure. Il semblerait quelle est été désactivée et que le préfixe "deleted." est été ajouté au début de son adresse mail. Cependant quand le gestionnaire de structure essaie de l'importer dans une nouvelle structure le système affiche une erreur.

![Image](https://github.com/gip-inclusion/carnet-de-bord/assets/85908681/d8a224c3-6cf4-46b0-a2b6-984f9fe4db02)

![Image](https://github.com/gip-inclusion/carnet-de-bord/assets/85908681/044b4a41-788d-4c83-87ea-3c1b7954ae61)

## Solution attendu
Supprimer Aurélie Pichot de la structure "CD UTAS AUBUSSON"
Ajouter Aurélie Pichot dans la structure "CD UTAS"

**Comment by vjousse** [comment]
J'ai réactivé son compte et je l'ai passée dans la bonne structure.
