### ISSUE TITLE
Supprimer les comptes des ex membres de l'équipe

### ISSUE THREAD

**Issue by JonathanRaimond** [gip-inclusion/carnet-de-bord#2059]
## Contexte : 
Suite au départ des membres e l'équipe des comptes sont restés actifs sur CDB

## Solution : 
Supprimer les comptes restants 

### Olivier Bourreau

Admin CDB :

olivier.bourreau@beta.gouv.fr

Manager : OK

Admin structure : 

[[olivierbourreau1+structure12@gmail.com](mailto:olivierbourreau1+structure12@gmail.com)](mailto:olivierbourreau1+structure12@gmail.com)

[[olivierbourreau1+structure43@gmail.com](mailto:olivierbourreau1+structure43@gmail.com)](mailto:olivierbourreau1+structure43@gmail.com)

[[olivierbourreau1+structure20@gmail.com](mailto:olivierbourreau1+structure20@gmail.com)](mailto:olivierbourreau1+structure20@gmail.com)

CO : OK

PRO :

[[olivier.bourreau+sortiersa11@beta.gouv.fr](mailto:olivier.bourreau+sortiersa11@beta.gouv.fr)](mailto:olivier.bourreau+sortiersa11@beta.gouv.fr)

### Charles Dechamps

Admin CDB :

[[charles.dechamps@beta.gouv.fr](mailto:charles.dechamps@beta.gouv.fr)](mailto:charles.dechamps@beta.gouv.fr) 

Manager : OK

Admin structure : 

[[pdi@cd08.fr](mailto:pdi@cd08.fr)](mailto:pdi@cd08.fr)

[[charles.dechamps+s91@ik.me](mailto:charles.dechamps+s91@ik.me)](mailto:charles.dechamps+s91@ik.me)

[[charles.dechamps+structure43@ik.me](mailto:charles.dechamps+structure43@ik.me)](mailto:charles.dechamps+structure43@ik.me)

[[charles.dechamps+structure91@ik.me](mailto:charles.dechamps+structure91@ik.me)](mailto:charles.dechamps+structure91@ik.me)

[[charles.dechamps+s08@ik.me](mailto:charles.dechamps+s08@ik.me)](mailto:charles.dechamps+s08@ik.me)

[[charles.dechamps+structure92@ik.me](mailto:charles.dechamps+structure92@ik.me)](mailto:charles.dechamps+structure92@ik.me)

**[[charles.dechamps+s84@beta.gouv.fr](mailto:charles.dechamps+s84@beta.gouv.fr)](mailto:charles.dechamps+s84@beta.gouv.fr)**

[[charles.dechamps+s02@beta.gouv.fr](mailto:charles.dechamps+s02@beta.gouv.fr)](mailto:charles.dechamps+s02@beta.gouv.fr)

**[[charles.dechamps+s46@beta.gouv.fr](mailto:charles.dechamps+s46@beta.gouv.fr)](mailto:charles.dechamps+s46@beta.gouv.fr)**

[[charles.dechamps+s12@beta.gouv.fr](mailto:charles.dechamps+s12@beta.gouv.fr)](mailto:charles.dechamps+s12@beta.gouv.fr)

**[[charle.dechamps+s81@beta.gouv.fr](mailto:charle.dechamps+s81@beta.gouv.fr)](mailto:charle.dechamps+s81@beta.gouv.fr)**

CO : OK

PRO :

[[charles.dechamps@cd08.fr](mailto:charles.dechamps@cd08.fr)](mailto:charles.dechamps@cd08.fr)

### Ronan James

Admin CDB : OK

Admin Manager : OK

Admin structure : 

[[ronan.atomic+cd35@gmail.com](mailto:ronan.atomic+cd35@gmail.com)](mailto:ronan.atomic+cd35@gmail.com)

CO : OK

PRO : OK

### Laetitia Kouadria

Admin CDB : OK

Manager : OK

Admin structure : OK

CO : OK

PRO : OK

### Lionel Breduillieard

Admin CDB :

[[lionel.breduillieard@beta.gouv.fr](mailto:lionel.breduillieard@beta.gouv.fr)](mailto:lionel.breduillieard@beta.gouv.fr)

Manager : OK

Admin structure : OK

CO : OK

PRO : OK

### Jonathan Perret

Admin CDB : OK

Manager :

[[jonathan.perret@beta.gouv.fr](mailto:jonathan.perret@beta.gouv.fr)](mailto:jonathan.perret@beta.gouv.fr)

Admin structure : OK

CO : OK

PRO : OK

### Justine Moreau

Admin CDB : OK

Manager : OK

Admin structure : OK

CO : OK

PRO : OK

### Hadrien Mens-Pellen

Admin CDB : OK

Manager : OK

Admin structure : OK

CO : OK

PRO : OK

### Benoît Chiquet

Admin CDB : OK

Manager : OK

Admin structure : OK

CO : OK

PRO : OK

### Guillaume Lagorce

Admin CDB : OK

Manager : OK

Admin structure : OK

CO : Ok

PRO : OK

### Amaury Dubaut

Admin CDB :

[[amaury.dubot@beta.gouv.fr](mailto:amaury.dubot@beta.gouv.fr)](mailto:amaury.dubot@beta.gouv.fr)

Manager : OK

Admin structure : OK

CO : OK

PRO : Ok

### Paul d’Oliveira da costa

Admin CDB : OK

Manager : OK

Admin structure : OK

CO : OK

PRO : OK

**Comment by vjousse** [comment]
C'est fait.
