### ISSUE TITLE
SUPPORT - Modifier l'adresse mail d'un admin structure

### ISSUE THREAD

**Issue by JonathanRaimond** [gip-inclusion/carnet-de-bord#2060]
## Contexte : 
Arnaud C. est admin de structure et a besoin de modifier son adresse mai, mais le système ne le permet pas.

## Solution : 
Remplacer "a.collignon@ardennes.cci.fr" par "a.collignon@marneardennes.cci.fr"

**Comment by vjousse** [comment]
C'est fait.
