### ISSUE TITLE
SUPPORT - Modifier l'adresse mail d'un pro

### ISSUE THREAD

**Issue by JonathanRaimond** [gip-inclusion/carnet-de-bord#2062]
## Contexte : 
Laurence V. est une professionnelle qui a besoin de modifier son adresse mail, mais le système ne le permet pas.

## Solution : 
Remplacer "laurence.vignol@formaon.fr" par "laurence.boucheraa@formaon.fr"

**Comment by vjousse** [comment]
C'est fait.
