### ISSUE TITLE
SUPPORT (Loiret) - Supprimer compte de test

### ISSUE THREAD

**Issue by JonathanRaimond** [gip-inclusion/carnet-de-bord#2063]
## Contexte : 
Lors d'un test avec Aline B. du Loiret un pro a été ajouté pour faire un test.

## Solution : 
Supprimer le compte "jonathanetraimond@gmail.com" de la structure "ADS Montargis" dans le déploiement du Loiret.

**Comment by vjousse** [comment]
C'est fait.
