### ISSUE TITLE
[Indic-Impact] Créer un composant de sondage NPS

### ISSUE THREAD

**Issue by Augustin82** [gip-inclusion/carnet-de-bord#340]
## :thinking: Contexte et problème observé

Aujourd'hui, nous mesurons le NPS grâce à une enquête envoyé par mail, de façon ponctuelle et non régulière.
Nous avons remarqué qu'un faible pourcentage d'utilisateur répondait à l'enquête et que le résultat était biaisé du fait du mode d'envoi.
La mise en place d'un NPS directement sur le site (pour les utilisateurs connecté (hors profil bénéficiaire) pourrait permettre d'améliorer la fiabilité du calcul et de répondre aux bonnes pratiques du GIP. 

## :horse: Proposition de solution

Intégrer dans les pages carnet de bord, pour les utilisateurs connectés (hors profil bénéficiaire et hors environnement de démo), un calcul du NPS (travaux commun outil du GIP : https://www.notion.so/gip-inclusion/NPS-Quelle-m-thode-suivre-7c3b5727d138417ca9a25e4f31a98dfe).

Le NPS comporte obligatoirement la question : " Quelle est la probabilité que vous recommandiez Carnet de Bord à un collègue ?" avec une note a donner allant de 0 à 10 ou 0 correspond à "peu probable" et 10 "très probable". 

Afficher la question dans un encart (voir ci-dessous) en faisant en sorte que le chiffre se colore lorsque la souris passe dessus (rouge de 0 à 3, orange de 4 à 6, jaune pour 7 et 8 et vert pour 9 et 10).
Possibilité pour l'utilisateur de fermer l'encart à sa convenance. Dans ce cas, ne plus l'afficher lors de sa visite en cours (mais le remettre dès la prochaine).

Possibilité de placer l'encart en bas a gauche pour ne pas interféré avec la bulle Crisp.

Récupérer en base sur matomo les résultats et prévoir une fois par mois de les exporter dans un Google Sheet (a créer dans https://drive.google.com/drive/folders/1Ko_1zq61qoVY29uZafPuMwOen5YT9RCj) pour permettre au GIP de produire une données globales et un suivi du NPS sur son site.  

Identifier les utilisateurs répondant afin de ne plus afficher la question pendant 15 jours après qu'il y ait répondu.

##  Maquettes
https://www.figma.com/file/LxSA1VswWm0ugNpHQ2tssG/MAQ---V1.7---PRO?node-id=1614%3A114795&t=bgdELuSaqRdk7arq-1
![NPS](https://user-images.githubusercontent.com/115156041/221549543-b6a78815-7136-45cd-978f-8ce31a340447.gif)

## :robot: Critères d'acceptation
**Etant donnée que** je suis un utilisateur, hors bénéficiaire de "carnet de bord"
**Et que** Je n'ai pas répondu répondu à l'enquête NPS sur "carnet de bord" depuis au moins 30 jours
**Lorsque** Je me connecte
**Alors** Un encart s'affiche pour me demander si je recommanderais  "carnet de bord" à un collègue

**Etant donnée que** L'encart s'affiche 
**Lorsque** ma souris passe sur les notes (hover) 
**Alors** les notes apparaissent en couleur
**Lorsque** je clique sur une note
**Alors** l'icône reste en couleur  
**Et** Le bouton "envoyer"  s'active

**Comment by JonathanRaimond** [comment]
Est-ce qu'on ne devrait pas plutôt afficher le btn "Valider" et afficher un message si la personne n'a pas sélectionnée de smiley. "Veuillez sélectionner un smiley puis valider votre réponse"

**Comment by chdechamps** [comment]
Update : mise à jour de la durée à 15 jours entre deux vote au lieux de 30 (j'avais lu en diagonale le notion, mais la pratique adoptée est de 15 jours). 
A noter : il y a un débat sur la durée, gardons en tête qu'il faille pouvoir la changer dans le temps

**Comment by francoisfreitag** [comment]
Est-ce que l’encart est toujours dans un état ouvert (tel que présenté sur la maquette), ou est-ce qu’on le minimise dans une sorte d’onglet pour éviter qu’il ne recouvre les éléments du site ?

Je serais assez frustré si l’encart couvrait l’élément auquel je souhaite accéder. Par exemple, sur la maquette, l’encart masque le profil visité le plus récemment.

**Comment by lionelB** [comment]
Je pense qu'on veut pouvoir l'afficher à la personne et laisser la personne le fermer une fois répondu (ou pas si elle ne souhaite pas répondre)

**Comment by francoisfreitag** [comment]
Discuté au quotidien, peut-être mettre un _feature flag_ pour désactiver le scoreur en prod pour tout le monde ?
