### ISSUE TITLE
Fil rouge - Ajouter des tests codecept

### ISSUE THREAD

**Issue by Augustin82** [gip-inclusion/carnet-de-bord#433]

**Comment by lionelB** [comment]
liste des "happy path"

### Pro

- [ ] Recherche d'un bénéficiaire
- [ ] Voir un carnet de bord
- [ ] Ajouter un membre au groupe de suivi
- [ ] Modifier les infos d'un bénéficiaire
- [ ] Modifier les infos sociopro d'un bénéficiaire 
- [ ] Ajouter un axe de travail, un objectif, une action

### manager

- [ ] Ajouter un structure

### admin

- [ ] Importer des structures, accompagnateur, beneficiaire

**Comment by lkouad** [comment]
@lionelB on cloture?

**Comment by lionelB** [comment]
oui c'est fait
