### ISSUE TITLE
[pro] Rattachement à un carnet

### ISSUE THREAD

**Issue by lionelB** [gip-inclusion/carnet-de-bord#454]
Actuellement, le seul moyen de se rattacher à un carnet, c'est d'être invité par un membre du groupe de suivi. 
- un pro peut il se rattacher à n'importe quel carnet du déploiement
- un pro peut il se rattacher à n'importe quel carnet dont un membre du groupe de suivi appartient à la même structure 
- autre ?

related to https://github.com/SocialGouv/carnet-de-bord/issues/424

**Comment by lkouad** [comment]
Retour Agence IMILO Reims. les agents on accès à tous les bénéficiaires suivis dans l'agence IMILO de Reims. Un conseiller peut demander le rattachement à un groupe de suivi sans accord du responsable d'agence. Dans la même agence il peut y avoir 3 conseillers. Exemple: 1 santé, 1emploi, 1 logement. Certains vont avoir un suivi "Long" exemple emploi d'autre temporaire exemple logement

**Comment by lkouad** [comment]
Retour Pole emploi: dans le flux transmis par pole emploi le bénéficiaire à des sa signature de PPAE un conseillé rattaché. Le flux va être hebdomadaire les conseiller pole emploi sont donc rattaché automatiquement donc pas certaine qu'ils doivent se raccrocher seul?

**Comment by lkouad** [comment]
Retour Ardenne, le conseille départemental délègue entièrement l'accompagnement. L'accompagnateur est donc nommé dans le flux que va nous transmettre le département. Idem pas certaine que les accompagnateurs doivent se rattacher seul au bénéficiaire

**Comment by lkouad** [comment]
Retour Marne: département décomposé en agence de proximité; les conseillers de l'agence de proximité on accès à tous les bénéficiaire de l'agence de proximité. Mais un conseiller est référent du suivi d'un bénéficiaire.

**Comment by lionelB** [comment]
on peut fermer @lkouad
