### ISSUE TITLE
ETQ Manager je peux mettre à jour les données des bénéficiaires déjà importer en réimportant les nouvelle données 

### ISSUE THREAD

**Issue by lkouad** [gip-inclusion/carnet-de-bord#524]
## Problématique
Aujourd'hui l'import ne permet met pas la mise à jour
## Proposition de travail
Réimporter un fichier avec les nouvelles données et mettre à jour la donnée "TO DO décrire les donnée par la team produit"
pour les bénéficiaires déjà existant 

Nous nous basons sur les 2 contraintes d'unicité ( internal ID, nom +prenom+date de naissance)

# Designs

[Maquette Admin Cohorte PDI](https://www.figma.com/file/YsikssTwIOl9OaSZMaeybe/MAQ-ADMIN-PDI-V2?node-id=0%3A1)

# Alternatives envisagées

Dressez la liste de toutes les alternatives à cette approche que vous avez envisagées. Expliquez pourquoi vous ne les avez pas utilisées.

# Documents connexes
https://instinctive-tarragon-76f.notion.site/V1-Import-Donn-e-parcours-BRSA-f5fb585ecee0486bad5be1eab2ff59f2

**Comment by JonathanRaimond** [comment]
[WIREFRAME_ADMIN_PDI.pdf](https://github.com/SocialGouv/carnet-de-bord/files/7913937/WIREFRAME_ADMIN_PDI.pdf)

**Comment by lionelB** [comment]
Est ce qu'il serait possible de préciser le scope de cette issue ?

**Comment by lkouad** [comment]
Yep lors du réimport d'un bénéficiaire si structure différente mettre à jour
Résultat : le bénéficiaire est dans la liste de 2 structures (on assume)
In scope
Ajouter la structure
Out scope
Retirer l'ancienne structure (trop top pour comprendre le fonctionnement on reviendra dessus quand le cas se présentera)
