### ISSUE TITLE
Importer Axe de Travail

### ISSUE THREAD

**Issue by JonathanRaimond** [gip-inclusion/carnet-de-bord#531]
### Présentation
ETQ gestionnaire de structure je peux importer l’ajout des données d’axe de travail dans ma liste de bénéficiaire
## Problématique
Certaine structure on leur propre logiciel de suivi de parcours gestionnaire de structure on leur propre logiciel afin de pouvoir rattacher les bénéficiaires à X accompagnateurs de sa structure mais le choix du rattachement peut être fait selon certain critere
Le plan d’actions matérialise les étapes-clés d’un parcours il diffère selon les chargés d’insertion et les structures  
## Proposition de travail
Depuis son espace gestionnaire de structure l'utilisateur doit pouvoir accéder à la liste de des bénéficiaire rattaché à sa structure et identifier rapidement ceux qui ne son pas pris en charge afin de leur rattacher un accompagnateur dans la marne par attribution selon les lettres de l’alphabet, dans d’autre structure attribution selon la localisation, selon l’âge, le type d’accompagnement, le type de frein… Le gestionnaire de structure doit pouvoir s’assurer que la prise en charge du bénéficiaire est bien effective
<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:w="urn:schemas-microsoft-com:office:word"
xmlns:m="http://schemas.microsoft.com/office/2004/12/omml"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Word.Document>
<meta name=Generator content="Microsoft Word 15">
<meta name=Originator content="Microsoft Word 15">
<link rel=File-List
href="file:///C:/Users/kouadria/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<link rel=themeData
href="file:///C:/Users/kouadria/AppData/Local/Temp/msohtmlclip1/01/clip_themedata.thmx">
<link rel=colorSchemeMapping
href="file:///C:/Users/kouadria/AppData/Local/Temp/msohtmlclip1/01/clip_colorschememapping.xml">

<style>

</style>

</head>

<body lang=FR style='tab-interval:35.4pt;word-wrap:break-word'>

Thè me co nce rné | Actio   ns | Da te de dé but | Eché a nce ﬁna le | Sta   tut | Fin e ﬀe ctive
-- | -- | -- | -- | -- | --

</body>

</html>

# Critères de réussite
1.	Pouvoir ajouter des actions au bénéficiaire
2.	Rattacher les actions aux thèmes
3.	Rattacher les actions à l’accompagnateur actuel de la structure
# Exigences
1.	Le système permet d’identifier l’accompagnateur 
2.	Le système permet d’identifier la date de création
# Evolution envisagé
1.	Ajouter et mettre a jour une date de début
2.	Attribuer l’action à un opérateur ou au bénéficiaire
3.	Ajouter une échéance 
4.	Permettre la mise a jour du statut par le bénéficiaire ou l’opérateur prescrit pour l’action
5.	Mettre a jour une date de fin quand statut terminé

Design
[Maquette Gestionnaire de structure](https://www.figma.com/file/BzTnRSf5KczPTuQeFEgQft/MAQ-GEST-STRUCTURE-V2?node-id=0%3A1)

**Comment by JonathanRaimond** [comment]
WIREFRAME
https://www.figma.com/file/BzTnRSf5KczPTuQeFEgQft/WF-GESTIONNAIRE-DE-STRUCTURE-V2?node-id=0%3A1

**Comment by ronanjames** [comment]
A votre disposition pour contribuer sur cette issue, en identifiant les DSI et territoires pour tester.  
Voici des questions qui sont poser svt qd la question est abordée avec eux :  
1/ quel est le format du fichier ? 
1/ quels traitement les structures doivent faire pour remplir nos fichiers d'import selon les sources (milo, solis, autres…) ? 
2/ comment les structures nous envoient leurs fichiers (sftp ?)
4/ quelles données va où (mapping lié au parser) 

Dans la maquette, la partie sur importer un axe de travail correspond plutôt à importer un bénéficiaire (fichier csv nvx 1 est affiché). Ca change pas l'ui, mais y'a la question du format du fichier
