### ISSUE TITLE
Protection contre une politique de nommage de compte faible ou non-appliqué

### ISSUE THREAD

**Issue by lkouad** [gip-inclusion/carnet-de-bord#553]
- Creer la politique de nommage des comptes dans la documentation projet - P3

**Comment by lionelB** [comment]
La politique de nommage des comptes
- pour les pro, le `username` est fait de manière automatique, en prenant la partie avant l'`@` et en y ajoutant un compteur.
- pour les admins de structures le `username` est un uuid generé.
