### ISSUE TITLE
Protection contre l'énumération de comptes

### ISSUE THREAD

**Issue by lkouad** [gip-inclusion/carnet-de-bord#554]
- Supprimer l’erreur et modifier le wording - P1

**Comment by Augustin82** [comment]
@lkouad @lionelB est-ce que vous confirmez qu'on veut bien :
- répondre un truc du genre "si votre compte a été trouvé, vous recevrez un email avec un lien de connexion" quand les gens tentent de se connecter à CdB ;
- ne plus envoyer de message d'erreur quand le compte n'a pas été trouvé, au risque d'avoir des utilisateurs qui persistent à utiliser le même mail erroné ?

Si oui, le changement est plutôt simple et rapide.

**Comment by lionelB** [comment]
pour moi c'est ok. @lkouad  ?

**Comment by lkouad** [comment]
Ok pour moi aussi @lionelB @Augustin82

**Comment by jonathanperret** [comment]
Pour clarifier le statut de cette issue, je la mets plutôt en "Closed as not planned" puisque ça n'a finalement pas été fait.
