### ISSUE TITLE
Historiser le début et la fin du suivi d'un pro

### ISSUE THREAD

**Issue by JonathanRaimond** [gip-inclusion/carnet-de-bord#566]
### **Problématique**
Le professionnel a besoin d'identifier le début et la fin du suivi d'un un pro, il ne peux pas consulter les remplacements des pro en charge du suivi d'un bénéficiaire dans l'historique de parcours.

### **Proposition de travail**
Historiser le début et la fin fin du suivi d'un pro dans l'historique de parcours

### **Design**
Wireframe à terminer

### **Origine**
Atelier Utisateur
Pratique metier logiciel

### **Business Value**
Attendu par les utilisateurs, 
Diminue l’attrait du produit si fonctionnalité non incluse

**Comment by chdechamps** [comment]
réalisé avec #1984
