### ISSUE TITLE
Améliorations login

### ISSUE THREAD

**Issue by Augustin82** [gip-inclusion/carnet-de-bord#616]
- [x] désactiver le bouton "Se connecter" après le premier clic
- [x] ~~quand on arrive sur un magic link avec un cookie valide, on devrait être loggé~~ c'est déjà le cas !
- [ ] ajouter une expiration sur les jwt (15min ? 1h ? 24h ?)
- [ ] ajouter des refreshTokens qui permettent d'obtenir des nouveaux tokens auprès de la base, sauf révocation de sécurité

**Comment by lkouad** [comment]
@lionelB on ferme?

**Comment by lionelB** [comment]
oui on fera le point avec le multicompte
