### ISSUE TITLE
Date d'ajout et crée par

### ISSUE THREAD

**Issue by lkouad** [gip-inclusion/carnet-de-bord#697]
#### Problème
Le diagnostic  " Situation" peut être fait à différent moment du parcours et par différente personne. ETQ utilisateur j'ai besoin d'avoir la date d'ajout pour juger de la pertinence de l'information, de l'évolution de la situation. J'ai aussi besoin de savoir qui à ajouté cette information afin de pouvoir contacter la personne pour comprendre les actions mise en place

#### Solution
V0 pour test: ajouté le/ par nom prenom ou structure

#### Maquette
![image](https://user-images.githubusercontent.com/83343517/159268651-3a952fd9-202c-4606-987b-403ccd76006b.png)

**Comment by Lotphy** [comment]
Je viens de voir qu'on a deja ces informations en bas de l'écran, partie "créé par" et lorsqu'on clique sur la carte on a encore plus d'info (date de création y compris) :
Du coup, faut-il juste déplacer ces infos dans le volet principal ?

<img width="520" alt="image" src="https://user-images.githubusercontent.com/31065028/173025158-54227075-b62a-49f3-84f5-b42b22c077ed.png">

**Comment by lkouad** [comment]
@Lotphy nous parlons pas du bloc axe mais de situation

**Comment by lkouad** [comment]
ETQ utilisateur j'ai besoin d'avoir la date d'ajout pour juger de la pertinence de l'information, de l'évolution de la situation. J'ai aussi besoin de savoir qui à ajouté cette information afin de pouvoir contacter la personne pour comprendre les actions mise en place
