### ISSUE TITLE
[Tech] auth/jwt/uuid est une route Svelte, ça devrait être une route back ?

### ISSUE THREAD

**Issue by Augustin82** [gip-inclusion/carnet-de-bord#706]

**Comment by Lotphy** [comment]
C'est le chemin du magic link, on peut potentiellement le rename un peu pour expliciter son taf (landing page du magic link, ex. /auth/link/uuid). Mais ce lien pointera forcément sur une page Svelte, puis celle-ci faira appel à son équivalent en back (REST POST /auth/jwt, avec uuid dans le body) pour générer le jwt. C'est le meme principe que dans la partie redirect uri d'une oauth2, notre uuid faisant office d'authentication code et le jwt pour l'authorization

**Comment by lionelB** [comment]
on se demandait si justement, ca devrait pas etre juste une route back (validation du token, creation du cookie, et redirection vers la page)

**Comment by lkouad** [comment]
@lionelB encore moi, on cloture?

**Comment by lionelB** [comment]
c'est le cas maintenant
