### ISSUE TITLE
Créer le lien bénéficiaire / structure lors de l'import des beneficiaires

### ISSUE THREAD

**Issue by lionelB** [gip-inclusion/carnet-de-bord#723]
Actuellement, on permet l'association d'une structure, d'un pro ou des 2 lors de l'import d'un bénéficiaire.
On propose d'ajouter la règle suivante 
- si on a un pro mais pas de structure, alors on ajoute le lien `beneficiary_structure` en récupérant la structure du pro

**Comment by lkouad** [comment]
@lionelB il me semble que c'est ok ça?

**Comment by lionelB** [comment]
toutafé
