### ISSUE TITLE
L'import d'une liste de rattachement de pro affiche une check verte (success) quand le pro n'éxiste pas

### ISSUE THREAD

**Issue by Lotphy** [gip-inclusion/carnet-de-bord#742]
En tant qu'admin de structure, lorsque j'importe une liste de rattachement avec un pro qui n'éxiste pas encore dans le système, l'opération aboutie avec succès (check verte et message "1 rattachement importé sur 1 demandé."), malgré le fait que le rattachement ne se fait pas.

Exemple de csv d'import :
id; nom; prénom; date de naissance; emails des professionnels
b7e43c7c-7c3e-464b-80de-f4926d4bb1e0;Marc;Saintpa;1982-02-01;ceci-n-est-pas-un-vrai-pro@scam.org

**Comment by lkouad** [comment]
@lionelB je ferme? Nous l'avions résolu ce bug

**Comment by lionelB** [comment]
ca me dit rien. je vais testé
