### ISSUE TITLE
PE - Traitement du fichier principal

### ISSUE THREAD

**Issue by lionelB** [gip-inclusion/carnet-de-bord#774]
le fichier contient une colone BRSA (la derniere) qui permet d'exclure les lignes avec Non
La colonne identifiant unique va servir de clef avec le fichier actions
nom / prénom / date de naissance / lieu de naissance (à venir) vont nous permettre d'identifier la personne dans cdb

- [x] Code Rome : https://github.com/SocialGouv/carnet-de-bord/issues/808
- [x] Axes de travail : https://github.com/SocialGouv/carnet-de-bord/issues/809
- [ ] Dernier entretien : https://github.com/SocialGouv/carnet-de-bord/issues/810
- [ ] Inscription : https://github.com/SocialGouv/carnet-de-bord/issues/811
- [ ] Comptes & structures : https://github.com/SocialGouv/carnet-de-bord/issues/812
- [ ] Difficultées : https://github.com/SocialGouv/carnet-de-bord/issues/813

### modalite_accompagnement
en attente de laeticia

**Comment by lkouad** [comment]
@lionelB pour le nom c'est le nom d'usage ou le nom de naissance? Important si nous voulons appareiller avec les données du cd

**Comment by lkouad** [comment]
der_entretien_ppae
Si un contrat PPAE est lié au bénéficiaire, si la date du fichier est plus récente, on met à jour la date de signature du contrat PPAE (Si pas de contrat, on crée le contrat et on met la date de der_entretien_ppae comme date de signature)
il n'y pas de date de fin pour un PPAE

@lionelB donc si il à un CER on cree une deuxieme info PPAE sans écraser CER c'est ça?

**Comment by lionelB** [comment]
> pour le nom c'est le nom d'usage ou le nom de naissance? Important si nous voulons appareiller avec les données du cd

aucune idée. à vérifier auprès de paul

**Comment by lionelB** [comment]
> @lionelB donc si il à un CER on cree une deuxieme info PPAE sans écraser CER c'est ça?

je veux bien qu'on clarifie ce point

**Comment by lionelB** [comment]
je ferme l'issue, de nouvelles viendront la remplacer poke @vjousse
