### ISSUE TITLE
Problème d'installation du projet sous Mac 

### ISSUE THREAD

**Issue by jbuget** [gip-inclusion/carnet-de-bord#838]
## Problème

J'essaye d'installer la plateforme en local.
Je suis la procédure du fichier README.
J'ai des soucis au moment de lancer le docker-compose.
Le service Hasura ne démarre pas jusqu'au bout.
Il échoue au moment de vérifier la disponibilité du service (en cherchant à taper sur `localhost:5000/v1/version`), cf. capture ci-dessous.

<img width="809" alt="image" src="https://user-images.githubusercontent.com/265963/171834536-3cf8bbb8-9067-4676-8868-51aaf2c361c2.png">

## Analyse

Je pense que c'est un souci de réseau docker sous Mac.

A noter que IntelliJIDEA me remonte une erreur de syntaxe (l. 25).

Même en remplaçant l'écriture (l. 27) - je ne conserver bien qu'une ligne sur mon poste ^^ - ça ne fonctionne pas.

<img width="371" alt="image" src="https://user-images.githubusercontent.com/265963/171835327-f1c3838d-4e6b-47c1-ae7e-fb63529947e8.png">

Pistes : 
- Il y a peut-être un truc à creuser du côté du ficier `/hasura/config.yml` (en remplaçant `localhost` par `hasura` ou un truc du genre).
- peut-être déclarer un driver ou network spécifique dans le docker-compose

## Environnement

OS : macOS Monterey 12.3.1
Docker : 20.10.11
Terminal : zsh

**Comment by lionelB** [comment]
Hello, 
est ce qu'a tout hasard tu n'aurais pas un mac avec les nouvelle puces M2 ? 
il me semble que l'image d'hasura avait un soucis avec la nouvelle archi
