### ISSUE TITLE
ETQ Manager je peux supprimer le filtre professionnel de la vue

### ISSUE THREAD

**Issue by lionelB** [gip-inclusion/carnet-de-bord#941]
ETQ Manager je peux supprimer le filtre professionnel de la vue
```gherkin
Soit un manager sur la liste des professionnels
Alors je clique sur le nombre de bénéficiaires rattaché pour le pro pierre chevalier
Alors je vois la page bénéficiaires filtré avec seulement les bénéficiaires auquel le pro est rattaché
Alors je peux cliquer sur supprimer le filtre 
Alors je vois la liste des bénéficiaires non filtré
```

![Liste Bénéficiaires](https://user-images.githubusercontent.com/85908681/179753738-1a78b641-c660-4a50-871f-debc55729192.png)

point d'attention: cette liste etant partagé avec les profils admin structure et chargé d'orientation, on souhaite que cela fonctionne aussi sur ces profils !

**Comment by lkouad** [comment]
![image](https://user-images.githubusercontent.com/83343517/203640172-4e4f1319-3042-43fb-81a4-fba9b98dd54c.png)

@lionelB nouas l'avons pas fermé à cause de ça? "point d'attention: cette liste étant partagé avec les profils admin structure et chargé d'orientation, on souhaite que cela fonctionne aussi sur ces profils !'

**Comment by lionelB** [comment]
on peut fermer. ca fonctionne pour le manager / admin de structure. Depuis la liste a été modifié pour les COA
