### ISSUE TITLE
Améliorer les champs de date

### ISSUE THREAD

**Issue by JonathanRaimond** [gip-inclusion/carnet-de-bord#959]
Problème :
Lorsque je clique sur un champ de date le jour n'est pas sélectionné par défaut.

Observation test utilisateur :
Je clique au milieu du champ, le mois est sélectionné donc je suis obligé d'utiliser la souris ou les flèches de mon clavier pour sélectionner le jour et commencer ma saisie.

Solution :
Lorsque je clique sur un champ date le jour est sélectionné par défaut.

**Comment by lkouad** [comment]
@JonathanRaimond il me semble que c'est résolu avec le date picker ? Si oui, peux tu clôturer?
![image](https://user-images.githubusercontent.com/83343517/203648539-d7dcc37c-9f1c-48f9-be85-43cc76b01b5e.png)
